bazelbuild/rules_swift

.travis.yml, .travis/bazelrc.linux, .travis/bazelrc.osx, .travis/build.sh, .travis/install.sh
This will fail currently on Linux because of #10. I'm merging it now so I can test the workflow with the fix about to come in.
=> Add Travis CI configuration.

BUILD
=> Add WORKSPACE to the //:for_bazel_tests target.

.travis.yml, .travis/install.sh, README.md, swift/internal/swift_binary_test.bzl
=> Fixes to support Bazel 0.14.1.

swift/internal/swift_protoc_gen_aspect.bzl
When using descriptor_set_in, protoc expects files as named when
creating it. While File.short_path is supposed to do the trick, it is
not working for extenal `WORKSPACE`s. In turn, Well Known Types and
direct source build fail to compile because they are not recognized
by protoc.
Fixes #23
=> Use WORKSPACE relative file paths when using direct sources and WKTs

swift/internal/swift_protoc_gen_aspect.bzl
=> Fix cross-repository proto_library dependencies.

swift/internal/api.bzl
=> Serialize debug options into .swiftmodules in dbg/fastbuild modes.

swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/swift_import.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/utils.bzl
Fix issue where --swiftcopt flags would interact incorrectly with targets with -wmo in their copts.
=> Fix issue where --swiftcopt flags would interact incorrectly with targets with -wmo in their copts.

swift/internal/api.bzl, swift/internal/features.bzl, swift/internal/xcode_swift_toolchain.bzl
Support batch compilation for Xcode 10 and higher.
=> Support batch compilation for Xcode 10 and higher.

swift/internal/swift_protoc_gen_aspect.bzl
Use no generated header feature constant
=> Use no generated header feature constant

swift/internal/api.bzl
Use to_list on depset
This was found using `--all_incompatible_changes` with 0.19.0
=> Use to_list on depset

.travis.yml, swift/repositories.bzl
Update Travis to use Bazel 0.19; Update protobuf to 3.6.1
=> Update Travis to use Bazel 0.19; Update protobuf to 3.6.1

.travis.yml, .travis/build.sh, swift/internal/compiling.bzl, swift/internal/linking.bzl, swift/internal/utils.bzl
Run buildifier to check formatting and lint issues on travis.
=> Run buildifier to check formatting and lint issues on travis.

.travis.yml, .travis/build.sh, README.md
Add WORKSPACE to the things checked by buildifier.
=> Add WORKSPACE to the things checked by buildifier.

swift/internal/api.bzl, swift/internal/archiving.bzl, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl
Add descriptive progress messages to most actions.
=> Add descriptive progress messages to most actions.

.travis/build.sh
buildifier 0.20.0 sets the exist status for lint issues.
=> buildifier 0.20.0 sets the exist status for lint issues.

swift/internal/api.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/xcode_swift_toolchain.bzl
Fix new lint warning from buildifier 0.20.0
=> Fix new lint warning from buildifier 0.20.0

.travis/build.sh, swift/internal/swift_c_module.bzl
Reorder dictionary keys per buildifier.
=> Reorder dictionary keys per buildifier.

.bazelci/presubmit.yml, .travis.yml, .travis/build.sh, .travis/install.sh, README.md, swift/repositories.bzl
Document that the apple_support hook needs to be called.
=> Document that the apple_support hook needs to be called.

swift/repositories.bzl
Update apple_support version dependency.
=> Update apple_support version dependency.

.bazelci/presubmit.yml, swift/internal/actions.bzl, swift/internal/api.bzl, swift/internal/swift_library.bzl, swift/internal/swift_toolchain.bzl, swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl
Add ObjC bridging header to swift_library output.
=> Add ObjC bridging header to swift_library output.

.travis/build.sh, swift/internal/api.bzl, swift/internal/attrs.bzl, swift/internal/compiling.bzl, swift/internal/deps.bzl, swift/internal/features.bzl, swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_c_module.bzl, swift/internal/swift_c_module_aspect.bzl, swift/internal/swift_cc_libs_aspect.bzl, swift/internal/swift_info_through_non_swift_targets_aspect.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl, swift/repositories.bzl
=> Update Skylib, remove some attributes, migrate to CcInfo.

README.md, swift/internal/swift_binary_test.bzl, swift/internal/swift_library.bzl, swift/repositories.bzl
Fix documentation link
Fixes https://github.com/bazelbuild/rules_swift/issues/143
Closes #144.
=> Fix doc link; migrate to InstrumentedFilesInfo, update apple_support

swift/internal/api.bzl, swift/internal/features.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Project import generated by Copybara.
=> Introduce our own dbg/fastbuild/opt features.

swift/repositories.bzl
=> Remove unused import.

README.md, swift/internal/api.bzl
Update setup instructions in README.md.
=> Update setup instructions in README.md.

doc/api.md, doc/providers.md, doc/rules.md
Gets the api changes and grpc rule that just landed on master.
=> Update the docs.

tools/BUILD, tools/common/BUILD, tools/worker/BUILD
Add some for_bazel_tests targets to keep things complete.
=> Add some for_bazel_tests targets to keep things complete.

swift/internal/compiling.bzl, swift/internal/linking.bzl
Convert to struct fields in post-cleanup APIs
=> Convert to struct fields in post-cleanup APIs

swift/internal/deps.bzl, swift/internal/swift_binary_test.bzl
Add `malloc` attribute to `swift_binary`.
=> Add `malloc` attribute to `swift_binary`.

tools/wrappers/swift_wrapper.sh
Automated g4 rollback of commit b1c51a16cf12ee6723786d476ff4a498edc9a3a5.
Xcode 10.2.1 fixes this issue
Force -fmodule-map-file= flags to be absolute paths to fix debugging in Swift 5.0.
Forcing the paths to be absolute seems like the opposite of what we want, and long-term it is. But lldb in Swift 5.0 does not remap relative -fmodule-map-file= paths correctly, so in order to salvage the debugging experience we have to do this temporarily.
=> Automated g4 rollback of commit b1c51a16cf12ee6723786d476ff4a498edc9a3a5.

swift/internal/linking.bzl
Use to_list() for depset iteration.
Fixes #201
=> Use to_list() for depset iteration.

swift/internal/swift_module_alias.bzl
Migrate `swift_module_alias` to `swift_common.compile`.
=> Migrate `swift_module_alias` to `swift_common.compile`.

swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl
Migrate `swift_{binary,test}` to `swift_common.compile`.
=> Migrate `swift_{binary,test}` to `swift_common.compile`.

.bazelci/presubmit.yml
New buildifier release includes some needed fixes.
=> New buildifier release includes some needed fixes.

.bazelci/presubmit.yml, .bazelci/update_workspace_to_deps_heads.sh
Add config to test some deps at their heads.
Add a helper script and new ci config to run the script modifying the
WORKSPACE to get head versions of some dependencies to help catch if
they were to land something that would break the build.
=> Add config to test some deps at their heads.

swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
=> Update rules_swift for --incompatible_enable_cc_toolchain_resolution

swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_toolchain.bzl, swift/repositories.bzl
Support autoconf-like feature discovery for the Linux toolchain.
Fixes #35.
=> Support autoconf-like feature discovery for the Linux toolchain.

tools/worker/swift_runner.cc
Use the correct error stream in persistent mode.
=> Use the correct error stream in persistent mode.

swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_toolchain.bzl
=> Internal cleanup.

tools/common/temp_file.h
Make sure ephemeral module caches are created inside $TMPDIR.
=> Make sure ephemeral module caches are created inside $TMPDIR.

swift/internal/compiling.bzl
=> Add cc_library deps to the force_load list if they have a .lo extension

swift/internal/api.bzl, swift/internal/derived_files.bzl, swift/internal/features.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/utils.bzl, swift/stats.bzl, tools/compile_stats/README.md, tools/compile_stats/build.sh
Add an aspect and script to collect timing information for Swift builds.
=> Add an aspect and script to collect timing information for Swift builds.

swift/repositories.bzl
=> Bump apple_support to 0.7.0.

swift/repositories.bzl
=> Bump skylib to 0.9.0

swift/repositories.bzl
=> Bump swift-protobuf to 1.6.0

swift/repositories.bzl
=> Bump apple_support to 0.7.1

swift/internal/debugging.bzl
Set -target for swift modulewrap.
=> Set -target for swift modulewrap.

swift/internal/api.bzl
Add Bazel's `-bin` output directory to the quote include paths searched by ClangImporter.
genfiles_dir is already searched but is deprecated (https://github.com/bazelbuild/bazel/issues/6761) and the C rules have been adding bin_dir to their quote include paths since June 2018, so we should catch up.
=> Add Bazel's `-bin` output directory to the quote include paths searched by ClangImporter.

examples/xplatform/grpc/BUILD, examples/xplatform/grpc/client_main.swift, examples/xplatform/grpc/echo.proto
Use WKTs from the example.
As an example, but also to exercise more of the rule's handling since WKTs get
some additional work.
=> Use WKTs from the example.

swift/BUILD, swift/internal/api.bzl, swift/internal/derived_files.bzl, swift/internal/features.bzl, swift/internal/providers.bzl, swift/internal/swift_library.bzl, swift/internal/xcode_swift_toolchain.bzl
Add support for swiftinterface files to swift_library.
=> Add support for swiftinterface files to swift_library.

swift/internal/compiling.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl
Factor out common output group logic into a helper function.
=> Factor out common output group logic into a helper function.

swift/repositories.bzl
=> Update skylib to 1.0.2

swift/repositories.bzl
=> Update apple_support to 0.7.2

swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl
=> Internal change.

test/rules/provider_test.bzl
Strengthen provider_test:
- Use unittest.fail, not asserts.expect_failure
- Add support to `expected_files` to name files that should be excluded, or to say that the expectation should be a subset instead of an exact match
- Project field path evaluation across depsets/lists to we can test things like `CcInfo.linking_context.libraries_to_link.static_library`, where `static_library` is evaluated on each element of `libraries_to_link` rather than the collection itself
=> Strengthen provider_test:

third_party/com_github_grpc_grpc_swift/BUILD.overlay
Remove unused glob,
Fixes #357
RELNOTES: None
=> Remove unused glob,

swift/internal/compiling.bzl, swift/internal/swift_grpc_library.bzl
Internal change
RELNOTES: None
=> Internal change

swift/internal/swift_c_module.bzl
Add `module_name` attribute to `swift_c_module`.
This will be mandatory to support precompiled modules, since the `swift_c_module` target is where precompilation will occur. Therefore, targets with module maps that define multiple modules will need to be split into multiple targets, each referencing a single module name and the appropriate subset of headers for that module.
=> Add `module_name` attribute to `swift_c_module`.

swift/internal/swift_import.bzl
Limit `swift_import` targets to a single module and require its name be specified.
This is a prerequisite for migrating Swift module propagation to the new `swift_common.create_module` structure.
=> Limit `swift_import` targets to a single module and require its name be specified.

doc/api.md, doc/providers.md, doc/rules.md
=> Docs updates.

.bazelci/presubmit.yml, .bazelci/update_workspace_to_deps_heads.sh, swift/repositories.bzl
Mostly a revert of commit 1e6557b09841a360d6e3a247d73746bd0c0d337d.
=> Enable more CI configs again.

WORKSPACE
This is required to run some of the tests
=> Add skylib toolchain to WORKSPACE

WORKSPACE, swift/repositories.bzl
I should have added to repositories.bzl instead of the WORKSPACE in the
first place.
=> Add rules_cc as dependency

swift/internal/swift_autoconfiguration.bzl
RELNOTES: None
PiperOrigin-RevId: 330801521
=> Remove unused value.

swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_import.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/utils.bzl, test/private_deps_tests.bzl, test/rules/provider_test.bzl, test/split_derived_files_tests.bzl
See https://github.com/bazelbuild/bazel/issues/10860.
=> Migrate to the modern Starlark linker input API.

swift/internal/providers.bzl, test/generated_header_tests.bzl
RELNOTES: None
PiperOrigin-RevId: 344857866
(cherry picked from commit 5167ae9ddde9c663e193da0bb1bb4b83073dded7)
=> Stop computing transitive_generated_headers.

swift/internal/compiling.bzl
Module map files being propagated through different providers seem to end up being treated like different modules, even though they point to the same .modulemap files. Swift compilation in targets with a lot of objc_library dependencies were getting a lot of duplicate `-fmodule-map-file` flags which can slow down the compilation. This fixes that by deduplicating the module map list before passing them to the compiler.
=> Deduplicate module map flags in Swift compilation

swift/internal/xcode_swift_toolchain.bzl
Added in Xcode 12, `StoreKitTest.framework` is in a new Developer directory hierarchy under the SDK root (not to be confused with the one under the `.platform` root), except on macOS where it *does* live in the `.platform`'s Developer directory.
A small cleanup here means we also no longer pass a non-existent developer frameworks path when targeting watchOS.
PiperOrigin-RevId: 346784495
(cherry picked from commit 0ec7a5783be1e5daf02f1d1748cf03c07e0fcc0e)
=> Add the SDK's `Developer/Library/Frameworks` directory to the compiler and linker search paths on platforms that have it.

swift/internal/compiling.bzl, swift/internal/providers.bzl
They are already exposed in the modules, so use them directly from there instead.
This also means they union doesn't have to keep being computed going up the
build graph, which will save some cycles.
RELNOTES: None
PiperOrigin-RevId: 351588940
(cherry picked from commit 52b9ffae47f39df35826448ecfabc04c4cccb8c1)
=> Stop computing/tracking defines.

swift/internal/compiling.bzl
If we're compiling a `swift_library` with explicit modules enabled but some dependency subtree doesn't propagate explicit modules, we weren't collecting the right headers; we need the full transitive set for that subtree, not just the direct headers.
Also cleaned up the comments and control flow in this function, which had gotten out-of-date and confusing, which no doubt contributed to the problem.
PiperOrigin-RevId: 354142943
(cherry picked from commit 0ad70ff0a551675508d4e83c5abca7ff27506435)
=> Fix header selection when falling back to implicit modules.

swift/internal/derived_files.bzl, test/private_deps_tests.bzl
PiperOrigin-RevId: 354172938
(cherry picked from commit 6dc76fe2400aac4aa4ddf1ba22866693ff181c63)
=> Automated rollback of commit 71998c865b827828c17dbd24bf48bb856523d4f5.

swift/internal/xcode_swift_toolchain.bzl
RELNOTES: None
PiperOrigin-RevId: 364797902
(cherry picked from commit aeb56dc0b633b0175b2f04a0c4a476eb647302a4)
=> Switch to XcodeVersionConfig.execution_info().

WORKSPACE, doc/BUILD.bazel, doc/rules.md, swift/internal/attrs.bzl, swift/swift.bzl
=> Add first stardoc API docgen target

swift/internal/swift_clang_module_aspect.bzl
- Require all dependencies' `SwiftInfo`s to be passed instead of implicitly (and unconditionally) traversing `deps`.
- Add `requested_features` and `unsupported_features` parameters so rule implementations can provide these values (to be automatically added to the values on the target) as if they were supplying the feature configuration themselves.
- Correctly derive a module name if it is not provided.
PiperOrigin-RevId: 368653094
(cherry picked from commit 24a044900b655dc6b14354cd2d924b9688e6b213)
=> API changes to `create_swift_interop_info`.

.pre-commit-config.yaml, CONTRIBUTING.md
Matches the one just landed in rules_apple: bazelbuild/rules_apple@61bc7c0
=> Add buildifier pre-commit hook

swift/internal/swift_binary_test.bzl
Also set `alwayslink = True`, and don't pass the compilation outputs to
`register_link_binary_action` since they will be propagated from the
said linking context.
This avoids the possible symbol duplication, as previously the same
object files would be passed to the linker twice.
=> Unconditionally create linking context from `swift_{binary,test}`'s direct `srcs`.

.bazelci/presubmit.yml
This reverts commit a2f5d1910bae3aa3efa26fde367cdbf7dd166a45.
=> Revert "Test with Bazel 4.2.0rc4 for now"

examples/xplatform/grpc/client_main.swift, examples/xplatform/grpc/client_unit_test.swift, examples/xplatform/grpc/echo.proto, examples/xplatform/grpc/server_main.swift, examples/xplatform/proto/example.proto, examples/xplatform/proto/main.swift
=> Add a proto package to the example files.

swift/internal/build_settings.bzl
This reverts commit 51a8f827d8aa6f2de2a1897aff4a1906d8b2f7c3.
=> Revert "Disable allow_multiple for per_module_swiftcopt_flag"

swift/internal/compiling.bzl
This reverts commit bb2efe2ca973ab087bf6c323f247ead9cc021c58.
=> Revert "Disable generated_header_rewriter for now"

swift/internal/compiling.bzl
Fixes TODOs from https://github.com/bazelbuild/rules_swift/pull/569.
=> Use lambdas to match upstream

swift/internal/module_maps.bzl, swift/internal/swift_clang_module_aspect.bzl
This reverts commit b1cc2123c44d9763e5e7fb902181cff0dfa87fc8.
=> Revert "Remove top level functions for now"

swift/internal/actions.bzl, swift/internal/swift_toolchain.bzl, swift/internal/toolchain_config.bzl, swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 403188177
(cherry picked from commit 18c26cda3004a6aa97f0405b4d800fa256f3d637)
=> Correctly propagate runfiles of toolchain configured tools.

.bazelci/presubmit.yml
Since Bazel 5.0.0 has been released.
=> Test with latest Bazel instead of last_rc

BUILD
Still required https://buildkite.com/bazel/rules-apple-darwin/builds/5156#6aaa7643-d162-4aea-85c6-9fb99fc01cbc
=> Add WORKSPACE back to for_bazel_tests

tools/common/process.cc
Add a Windows port for the subprocess handling.  This is fairly brittle,
does not perform job control (which means runaway processes potentially
on interrupt), and does not perform the proper handling for Unicode.
However, the logic is complex enough that adding in an additional
encoding conversion for the initial version may not be the wisest idea.
Subsequent passes could clean up the implementation.
=> common: add subprocess support for Windows

swift/internal/swift_autoconfiguration.bzl
This replicates the macOS and Linux toolchain auto-configuration as a
starting point.  There are multiple subsequent things which will be
needed to be adjusted to make this usable but this provides a starting
point to being identifying those pieces.
=> swift: begin sketching out a toolchain config for Windows

tools/common/process.cc
Close the main thread handle earlier as we do not need it.  This avoids
the duplicated cleanup on the error path.  Move variable declaration
closer to initial use.
=> common: minor cleanup for Windows `RunSubProcess`

doc/api.md, swift/internal/compiling.bzl, swift/internal/providers.bzl, swift/internal/swift_common.bzl
This reverts commit ba15ded0570e7793818d58efd8ef9ef77313e564.
=> Revert "Revert "Add `compilation_context` to `SwiftInfo` (#815)""

tools/worker/work_processor.cc
When you cancel an action, some of the incremental outputs may be
produced while some may not. Since Swift 5.6 outputs from swift are not
always created if nothing has changed, which lead to subsequent actions
failing. Now before copying over any incremental inputs, we first
validate that all the expected files exist, otherwise we don't copy any
to force swift to recreate everything.
Fixes https://github.com/bazelbuild/rules_swift/issues/819
=> Fix incomplete incremental inputs

swift/internal/features.bzl
This treats the requested and disabled features as coming from different layers, with the more general layers providing defaults that are overridden by more specific layers. Features unsupported by the toolchain are treated as the most specific layer of all. The result more closely matches Bazel's treatment of features.
This will allow explicit modules to be enabled at the toolchain level, with per-package overrides in the toolchain configuration that can be overridden again at the target level.
PiperOrigin-RevId: 444273296
(cherry picked from commit 8b3732bfad7e70b7056f5a412302b0d1e279d0c8)
=> Use a more flexible approach when determining which features are enabled or disabled.

README.md
This is covered in the bottom of the README now
=> Remove compatibility readme section

.bazelci/presubmit.yml
https://github.com/bazelbuild/bazel/issues/16446
=> Workaround CI issue temporarily

tools/worker/output_file_map.cc, tools/worker/output_file_map.h, tools/worker/swift_runner.cc, tools/worker/work_processor.cc
Fixes https://github.com/bazelbuild/rules_swift/issues/921
=> Handle objc header path with incremental compiles

.bazelci/presubmit.yml
Now that latest is 6.x we need a new job
=> Add bazel 5.x CI

swift/internal/feature_names.bzl, swift/internal/linking.bzl, swift/internal/swift_autoconfiguration.bzl
This is what SwiftPM does now as well.
=> Add workaround for Swift + lld bug

.bazelci/presubmit.yml
This reverts commit 1e40718597287572e638aa71f8e27b42d7d7b20d.
=> Revert "Avoid doc test failure (#1021)"

tools/common/bazel_substitutions.cc
=> Fix toolchain xcrun path

swift/internal/BUILD, tools/worker/BUILD
Fixes https://github.com/bazelbuild/rules_swift/issues/1052
=> Switch to upstream apple config_settings

.bazelci/presubmit.yml
Seems like CI is doing this so this reflects reality
=> Update CI to Xcode 14.3

tools/common/process.cc
=> Remove unnecessary define

swift/internal/compiling.bzl, swift/internal/linking.bzl, swift/internal/xcode_swift_toolchain.bzl, test/fixtures/linking/fake_framework.bzl, test/imported_framework_tests.bzl
Fixes https://github.com/bazelbuild/rules_swift/issues/1142
=> Fix compatibility with --incompatible_objc_provider_remove_linking_info

.bcr/presubmit.yml
I accidentally used this as a target
=> Fix bcr presubmit flags

test/fixtures/basic/BUILD
Imports failed because of incorrect module names.
=> Fix compilation of `//test/fixtures/basic`

swift/internal/xcode_swift_toolchain.bzl
This reverts commit e71ae0881d2751a30a1119eadbb4be2376ed30d7.
=> Revert "Add 5.x compat"

MODULE.bazel, swift/repositories.bzl
Brings some Bazel @ HEAD fixes
=> Update apple_support to 1.15.1

swift/internal/swift_import.bzl
PiperOrigin-RevId: 440112752
(cherry picked from commit 89534ae57c7afaa47361bf7aec14cc30bc4b8b56)
=> Make `swift_import` depend on the Swift toolchain.

swift/BUILD, swift/internal/BUILD
PiperOrigin-RevId: 440100294
(cherry picked from commit a712262924e0c051cc59f42bfe846e8ce3f72f24)
=> Build out the bzl_library targets

swift/internal/actions.bzl, swift/internal/toolchain_config.bzl, swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 449761479
(cherry picked from commit fcc3a59f5b06f592ce1efe84d7cf20f37894f987)
=> Define resource_set for SwiftCompile action

swift/swift_library.bzl
PiperOrigin-RevId: 639094610
(cherry picked from commit cda5365f4457d8e7ff0537c2713cfdbd181e5f11)
=> Fix message formatting.

.bcr/presubmit.yml
Missed in 8736e61f225ff306aeedc47cf825b8edf406e3bf.
=> Upgrade Swift version in BCR presubmit as well

.bazelci/presubmit.yml
Fixes https://github.com/bazelbuild/rules_swift/issues/1303
=> Explicitly add `--enable_workspace=true` to `doc_tests`

swift/toolchains/config/compile_config.bzl
PiperOrigin-RevId: 505112308
(cherry picked from commit 0ac265a14ff3cea4a667987ef36b64b930097e02)
=> Formatting cherry-pick

swift/internal/swift_symbol_graph_aspect.bzl
PiperOrigin-RevId: 513564459
(cherry picked from commit 33cb26e9926eb17e0425fe456398af9bc611b7e3)
=> Cherry-pick formatting change

README.md, proto/BUILD, test/BUILD, test/fixtures/BUILD, test/rules/BUILD, third_party/com_github_apple_swift_argument_parser/BUILD.overlay, third_party/com_github_apple_swift_atomics/BUILD.overlay, third_party/com_github_apple_swift_collections/BUILD.overlay, third_party/com_github_apple_swift_docc_symbolkit/BUILD.overlay, third_party/com_github_apple_swift_log/BUILD.overlay, third_party/com_github_apple_swift_nio/BUILD.overlay, third_party/com_github_apple_swift_nio_extras/BUILD.overlay, third_party/com_github_apple_swift_nio_http2/BUILD.overlay, third_party/com_github_apple_swift_nio_ssl/BUILD.overlay, third_party/com_github_apple_swift_nio_transport_services/BUILD.overlay, third_party/com_github_apple_swift_protobuf/BUILD.overlay, third_party/com_github_grpc_grpc_swift/BUILD.overlay
It will be going away in the future.
=> Remove more references to `swift.bzl`

examples/xplatform/macros/BUILD
Our CI can properly check these now.
=> Remove `--define=supports_macros=1` check

swift/BUILD
PiperOrigin-RevId: 512976463
(cherry picked from commit 3a2954192fd2439ce0b5decfa2c47ef98e3a9c8c)
=> Remove `force_apple_target` Starlark flag

swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl
(cherry picked from commit 460779ddd0c295a5949df98ce6d35c9a1e3147bd)
=> Update docs from upstream

swift/swift_library.bzl
PiperOrigin-RevId: 662500535
(cherry picked from commit 9a4bcc0c847c78c806d928067f09a5031daf8d4d)
=> Apply upstream code formatting

swift/internal/target_triples.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 517189082
(cherry picked from commit 9abd062b07a61ae7cf027cc80e4c41f80ada7386)
=> Move `bazel_apple_platform` into `target_triples`

swift/internal/explicit_module_map_file.bzl
PiperOrigin-RevId: 542275780
(cherry picked from commit 216707274467f4de1b8436a7f7f97537ccff8ef2)
=> Write entries for clang modules in explicit swift module map

swift/providers.bzl
This reverts commit 9ef2a1fe2c5d51b49a60b57fea599cd459c722fb.
=> Remove old `SwiftInfo` arguments

doc/BUILD, doc/doc.bzl, doc/rules.md, examples/xplatform/overlay/BUILD, examples/xplatform/overlay/Orientation.swift, examples/xplatform/overlay/RetroLibraryOverlay.swift, examples/xplatform/overlay/RetroTest.swift, examples/xplatform/overlay/retro_library.c, examples/xplatform/overlay/retro_library.h, swift/BUILD, swift/internal/BUILD, swift/internal/binary_attrs.bzl, swift/internal/linking.bzl, swift/internal/output_groups.bzl, swift/internal/providers.bzl, swift/providers.bzl, swift/swift_binary.bzl, swift/swift_clang_module_aspect.bzl, swift/swift_compiler_plugin.bzl, swift/swift_library.bzl, swift/swift_overlay.bzl, swift/swift_test.bzl
PiperOrigin-RevId: 631412228
(cherry picked from commit 8e001a5431685310f34830f58acd0ac6f432b0d2 and 3fcc22be62fb8d173bd411bcf144a19a6d1ccc03)
=> Add `swift_overlay` rule

doc/BUILD, doc/api.md, doc/doc.bzl, swift/BUILD, swift/swift_overlay_helpers.bzl
PiperOrigin-RevId: 668406915
(cherry picked from commit b01724715c0d72ccda8df1080f5c9b234490970f)
=> Add an API that lets aspects ask whether a target is a `swift_overlay`

CODEOWNERS
see also:
bazelbuild/apple_support#349
bazelbuild/rules_apple#2602
=> Add Aaron to `CODEOWNERS`

.bazelci/presubmit.yml
=> Run stardoc with older bazel

swift/internal/swift_autoconfiguration.bzl
Now that rules_swift is using the toolchains API, we can always create all of our toolchains. This enables cross-platform RBE builds.
=> Always create all toolchains

.bazelci/presubmit.yml, .bcr/presubmit.yml
Needed to unblock some upstream changed.
=> Swift 6.0.3 for Linux

MODULE.bazel, swift/repositories.bzl
=> Update apple_support to latest

MODULE.bazel
=> Increase compatibility_level to 3
