bazelbuild/rules_swift

swift/repositories.bzl
This will improve the situation if multiple repositories define the
same dependencies (such as someone depending on rules_apple and
rules_swift, and then rules_apple also itself depending on
rules_swift). It does not address the situation where the same
dependency is used but with different versions; Bazel does not have
a great answer to this at this moment, as far as I know.
=> Only define repository dependencies if they haven't been already.

swift/internal/api.bzl
Eventually --incompatible_disallow_old_style_args_add will be flipped, making old style use an error.
The new API encourages efficiency by trying to make common use cases convenient and elegant. Some functionality has been moved around and renamed, some functionality is new.
List of changes that have been used in the migration:
* Key-value overloads are used over multiple calls or formats. This ensures your command line arguments are kept together in code, and is efficient.
Instead of:
args.add("--output")
args.add(output)
or
args.add(["--output", output])
or (still acceptable but not preferred)
args.add(output, format="--output=%s")
or (worst, inefficient, creates and retains redundant strings)
args.add("--output=%s" % output.path)
use:
args.add("--output", output)
* args.add_all and …
=> Migrate to new style ctx.actions.args.

swift/internal/api.bzl
Module names cannot contain "."
```
(cd /private/var/tmp/_bazel_aamand/6e9e094d4711fb7bbf6e809ecba4fd6c/execroot/co_znly_protodefs && \
exec env - \
APPLE_SDK_PLATFORM=iPhoneSimulator \
APPLE_SDK_VERSION_OVERRIDE=11.3 \
XCODE_VERSION_OVERRIDE=9.3.0 \
bazel-out/host/bin/external/bazel_tools/tools/objc/xcrunwrapper swiftc -target x86_64-apple-ios11.3 -sdk __BAZEL_XCODE_SDKROOT__ -F __BAZEL_XCODE_DEVELOPER_DIR__/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -emit-object -output-file-map bazel-out/darwin-fastbuild/bin/external/gogo_special_proto/github.com/gogo/protobuf/gogoproto/gogoproto.output_file_map.json -emit-module-path bazel-out/darwin-fastbuild/bin/external/gogo_special_proto/github.com/gogo/protobuf/gogoproto/github.com_gogo_protobuf_gogoproto_gogoproto.swiftmodule …
```
=> Fix module name derivation

swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/features.bzl, swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Allow toolchains to specify default enabled/disabled features.
This is the first part of a refactoring that will restate support for things like debug prefix map and response files as Bazel features instead of separate fields in the provider, which keeps the provider from becoming bloated and also gives users some finer control if needed.
=> Allow toolchains to specify default enabled/disabled features.

swift/internal/actions.bzl, swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/features.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_toolchain.bzl, swift/internal/wrappers.bzl, swift/internal/xcode_swift_toolchain.bzl, tools/wrappers/BUILD, tools/wrappers/bazel_xcode_wrapper.sh, tools/wrappers/swift_wrapper.sh
Add wrapper scripts for swift/swiftc.
Currently, only wrapper_swiftc is used; it provides an option to use an ephemeral
module cache directory in an attempt to get rid of flakiness with the default
module cache that causes compiler crashes after some configuration changes or
repository syncs.
=> Add wrapper scripts for swift/swiftc.

.travis.yml
Update Travis to ignore the Copybara release branch.
=> Update Travis to ignore the Copybara release branch.

swift/internal/api.bzl
Use param file for library copts.
This Args object gets passed to the Swift compiler. In order to support
persistent workers, it must be a param file.
=> Use param file for library copts.

swift/internal/api.bzl
Change Args file format from multiline to shell
With the shell file format arguments on each line are quoted, which
makes these use cases compatible with files with spaces in their paths.
=> Change Args file format from multiline to shell

swift/internal/swift_protoc_gen_aspect.bzl
Remove "requires-darwin" requirement for Swift proto generating action.
=> Remove "requires-darwin" requirement for Swift proto generating action.

swift/repositories.bzl
Use replacement git/http external repo rules
This update moves away from the deprecated external repo rules to use their recommended replacements. `rules_apple` uses the new rules too. See: https://docs.bazel.build/versions/master/be/workspace.html#git_repository
=> Use replacement git/http external repo rules

tools/xctest_runner/xctest_runner.sh.template
Use basename for macOS test bundle binaries
When using swift_test on macOS, the resulting bundle must have this
layout: `foo.xctest/Contents/MacOS/foo`. Previously using `dirname` to
create the `.xctest` directory resulted in the parent directory of the
module, which doesn't necessarily match the binary's name.
=> Use basename for macOS test bundle binaries

swift/internal/api.bzl
Don't add duplicate -emit-object flag
The `-emit-object` flag was being added twice to `compile_args`. Once directly, and another time via `_swiftc_command_line_and_inputs()`. This removes the one being added in `_swiftc_command_line_and_inputs()`.
=> Don't add duplicate -emit-object flag

swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/swift_library.bzl
Add support for force loading libraries
ld doesn't have an -ObjC type flag for Swift. Because of this there are
common cases you can get in to that require the library to be force
loaded by any dependents.
This patch relies on the existing force_load_library behavior from the
ObjCProvider https://docs.bazel.build/versions/master/skylark/lib/ObjcProvider.html#force_load_library
More details: https://bugs.swift.org/browse/SR-6004
Once some fix for https://github.com/bazelbuild/rules_swift/pull/38 is merged, we can also add this there.
=> Add support for force loading libraries

examples/xplatform/c_from_swift/BUILD, examples/xplatform/c_from_swift/module.modulemap, swift/internal/api.bzl, swift/internal/attrs.bzl, swift/internal/derived_files.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_c_module_aspect.bzl, swift/internal/swift_import.bzl, swift/internal/swift_library.bzl
Generate module maps for direct `cc_library` deps.
RELNOTES: The Swift build rules now automatically generate Swift-compatible
module maps for any `cc_library` targets that are direct dependencies of a
Swift target so that C definitions in those libraries can be imported.
By default, the module name will be derived from the `cc_library` target
label using the same logic used for Swift targets. This can be overridden
by specifying `tags = ["swift_module=Foo"]` on the `cc_library`,
replacing `Foo` with the desired module name.
=> Generate module maps for direct `cc_library` deps.

swift/internal/api.bzl, swift/internal/compiling.bzl
Propagate simple defines between Swift and Objective-C targets.
=> Propagate simple defines between Swift and Objective-C targets.

swift/internal/swift_binary_test.bzl
Merge list and depset without plus
Previously using `depset + list` was supported, with
`--all_incompatible_changes` in 0.19.0 it isn't anymore. Instead we need
to construct a new depset passing both.
=> Merge list and depset without plus

README.md, swift/internal/compiling.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_c_module_aspect.bzl, swift/internal/swift_cc_libs_aspect.bzl
Ensure that headers from transitive dependencies are passed as action inputs when exposing a `cc_library` to Swift.
=> Ensure that headers from transitive dependencies are passed as action inputs when exposing a `cc_library` to Swift.

swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/linking.bzl
Address `buildifier --lint=warn` issues.
swift/internal/compiling.bzl:24: load: Loaded symbol "SwiftToolchainInfo" is unused. Please remove it.
To disable the warning, add '@unused' in a comment. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#load)
swift/internal/debugging.bzl:19: load: Loaded symbol "SwiftToolchainInfo" is unused. Please remove it.
To disable the warning, add '@unused' in a comment. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#load)
swift/internal/linking.bzl:19: load: Loaded symbol "SwiftToolchainInfo" is unused. Please remove it.
To disable the warning, add '@unused' in a comment. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#load)
swift/internal/swift_c_module.bzl:180: attr-single-file: single_file is …
=> Address `buildifier --lint=warn` issues.

swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/linking.bzl, swift/internal/swift_import.bzl
Support swift_import in ObjC rules
Previously it was not possible to use a `swift_import` in upstream rules
such as `ios_unit_test` since it was not propagating a compatible
provider. Now `swift_import` propagates Objective-C providers so it can
correctly be linked.
This fixes https://github.com/bazelbuild/rules_swift/issues/37
=> Support swift_import in ObjC rules

.travis/bazelrc.linux, .travis/bazelrc.osx, swift/repositories.bzl
Bump versions of rules_swift dependencies:
* bazel-skylib -> 0.5.0
* swift-protobuf -> 1.2.0
* protobuf -> 3.6.1.2
=> Bump versions of rules_swift dependencies:

swift/internal/api.bzl, swift/repositories.bzl
Move skylib to the 0.6.0 release (Nov 2018)
This isn't directly need by this repo, but it clears the way for
anyone that needs this repo and something in that skylib release.
=> Move skylib to 0.6.0; remove resources/structured_resources attributes

.travis.yml, .travis/build.sh
Update Travis to Xcode 10.1 (Apple) and Swift 4.2.1 (Linux).
Closes #130.
Fixes #119.
=> Update Travis to Xcode 10.1 (Apple) and Swift 4.2.1 (Linux).

BUILD, examples/apple/objc_interop/BUILD, examples/xplatform/c_from_swift/BUILD, examples/xplatform/dispatch/BUILD, examples/xplatform/hello_world/BUILD, examples/xplatform/proto/BUILD, examples/xplatform/xctest/BUILD, swift/BUILD, swift/internal/BUILD, tools/BUILD, tools/mkdir_and_run/BUILD, tools/wrappers/BUILD, tools/xctest_runner/BUILD
Bazel trips up on visibility with @repository references.
Avoiding https://github.com/bazelbuild/bazel/issues/7180
=> Bazel trips up on visibility with @repository references.

CODEOWNERS, swift/internal/swift_module_alias.bzl, swift/internal/swift_proto_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl
Migrate the provider containing information about protocol buffers from the old-style 'dep.proto' pattern to the new-style 'dep[ProtoInfo]' one.
=> Migrate the provider containing information about protocol buffers from the old-style 'dep.proto' pattern to the new-style 'dep[ProtoInfo]' one.

.bazelci/presubmit.yml, .travis.yml, .travis/bazelrc.linux, .travis/bazelrc.osx, .travis/build.sh, swift/internal/swift_binary_test.bzl
Stop testing against Bazel release on Travis.
BuildKite does this much faster, so we'll lighten the load on Travis by only testing against HEAD.
=> Stop testing against Bazel release on Travis.

.bazelci/presubmit.yml
Label Buildkite tasks so they can be differentiated.
=> Label Buildkite tasks so they can be differentiated.

.bazelci/presubmit.yml
Fix Buildifier version
"buildifier: true" has been deprecated by https://github.com/bazelbuild/continuous-integration/pull/542
Closes #155.
=> Fix Buildifier version

swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl
Remove old-style provider support from collect_transitive
No callers of `collect_transitive()` pass old string provider references.
Closes #160.
=> Remove old-style provider support from collect_transitive

swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/features.bzl, swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_import.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl, swift/repositories.bzl, tools/wrappers/swift_wrapper.sh
Force -fmodule-map-file= flags to be absolute paths to fix debugging in Swift 5.0.
Forcing the paths to be absolute seems like the opposite of what we want, and long-term it is. But lldb in Swift 5.0 does not remap relative -fmodule-map-file= paths correctly, so in order to salvage the debugging experience we have to do this temporarily.
=> Force -fmodule-map-file= flags to be absolute paths to fix debugging in Swift 5.0.

CONTRIBUTING.md, swift/internal/api.bzl, swift/internal/xcode_swift_toolchain.bzl, swift/repositories.bzl
Don't eval tools for truth, just fail if it wasn't the right type.
Newer buildifiers were still flagging tools as not always being set,
but the real issue was if the value in the args was say an empty
string, then that last if would have still failed because an empty
string is False. Instead fail if someone passes anything that isn't
a list or depset no mater what the value is.
=> Don't eval tools for truth, just fail if it wasn't the right type.

examples/xplatform/grpc/BUILD, examples/xplatform/grpc/client_main.swift, examples/xplatform/grpc/client_unit_test.swift, examples/xplatform/grpc/echo.proto, examples/xplatform/grpc/server_main.swift, swift/internal/swift_grpc_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/repositories.bzl, swift/swift.bzl, third_party/com_github_apple_swift_protobuf/BUILD.overlay, third_party/com_github_grpc_grpc_swift/BUILD.overlay
Make `swift_grpc_library` available to Bazel users.
RELNOTES: The `swift_grpc_library` rule has been added, which can be used to generate Swift code for gRPC clients/servers. Necessary dependencies (gRPC and gRPC-Swift) are automatically added to the workspace.
=> Make `swift_grpc_library` available to Bazel users.

README.md, swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/providers.bzl, swift/internal/swift_toolchain.bzl, swift/internal/wrappers.bzl, swift/internal/xcode_swift_toolchain.bzl, swift/repositories.bzl, third_party/bazel_protos/BUILD, third_party/bazel_protos/README.md, third_party/bazel_protos/worker_protocol.proto, third_party/com_github_nlohmann_json/BUILD.overlay, tools/common/BUILD, tools/common/file_system.cc, tools/common/file_system.h, tools/common/path_utils.cc, tools/common/path_utils.h, tools/common/process.cc, tools/common/process.h, tools/common/string_utils.cc, tools/common/string_utils.h, tools/common/temp_file.h, tools/worker/BUILD, tools/worker/main.cc, tools/worker/output_file_map.cc, tools/worker/output_file_map.h, tools/worker/work_processor.cc, tools/worker/work_processor.h, tools/wrappers/swift_wrapper.sh
Add a persistent worker to support `swiftc` incremental compilation.
To perform incremental builds, pass the `--strategy=SwiftCompile=worker` flag to Bazel (or add it to your .bazelrc file).
Fixes #48.
=> Add a persistent worker to support `swiftc` incremental compilation.

tools/worker/BUILD, tools/worker/dummy_main.cc
Create a "dummy worker" for upstream integration tests.
The external dependencies used by the persistent worker are fairly heavyweight, and upstream integration tests (like those in rules_apple) should not be forced to mock them all out in their test workspace (which they would have to, because the worker is an implicit dependency of all toolchains). This change provides a flag that they can pass to Bazel to build a dummy executable that is dependency-free instead.
=> Create a "dummy worker" for upstream integration tests.

tools/worker/work_processor.cc
This function is only used on macOS so it produced this warning on Linux:
```
external/build_bazel_rules_swift/tools/worker/work_processor.cc:37:13: error: unused function 'GetMandatoryEnvVar' [-Werror,-Wunused-function]
std::string GetMandatoryEnvVar(const std::string &var_name) {
^
1 error generated.
```
=> Fix unused function warning on Linux

swift/internal/api.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/swift.bzl
API cleanup: Remove compile_options field from SwiftInfo and remove SwiftBinaryInfo.
=> API cleanup: Remove compile_options field from SwiftInfo and remove SwiftBinaryInfo.

swift/internal/swift_grpc_library.bzl
Pass all tools as 'tools' and not 'inputs'.
Fixes #181
=> Pass all tools as 'tools' and not 'inputs'.

swift/internal/compiling.bzl
Use `to_list()` for depset iteration.
Found via --incompatible_depset_is_not_iterable looking at the logs
linked off of https://github.com/bazelbuild/rules_swift/issues/181
=> Use `to_list()` for depset iteration.

swift/internal/api.bzl, swift/internal/swift_binary_test.bzl
Make the Swift module cache path explicitly different from Clang's.
The cached modules aren't actually shared anyway—the Clang invocation used to generate them from Objective-C differs from the Clang invocation used by Swift's ClangImporter, so they hash to different paths (this is not just a Bazel characteristic, it happens with Xcode as well). At best, this makes sharing the location worthless; at worst, it opens the possibility for corruption or collision.
=> Make the Swift module cache path explicitly different from Clang's.

README.md
Show the build status only for the master branch.
Otherwise a test_* branch that doesn't currently pass turns the badge red
because it was the "most recent" build on buildkite.
=> Show the build status only for the master branch.

third_party/com_github_grpc_grpc_swift/BUILD.overlay
Without this these warnings are produced at link time:
```
ld: warning: pointer not aligned at address 0x1004354AA (_grpc_lb_v1_ClientStats_fields + 106 from bazel-out/ios_x86_64-fastbuild/bin/external/com_github_grpc_grpc_swift/libCgRPC.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x10043544B (_grpc_lb_v1_ClientStats_fields + 11 from bazel-out/ios_x86_64-fastbuild/bin/external/com_github_grpc_grpc_swift/libCgRPC.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x1004354EE (_grpc_lb_v1_LoadBalanceRequest_fields + 30 from bazel-out/ios_x86_64-fastbuild/bin/external/com_github_grpc_grpc_swift/libCgRPC.a(load_balancer.pb.o))
ld: warning: pointer not aligned at address 0x1004354DB (_grpc_lb_v1_LoadBalanceRequest_fields + 11 from …
```
=> Fix CgRPC linker warnings

swift/internal/api.bzl, swift/internal/archiving.bzl, swift/internal/providers.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Use the C++ toolchain to register static archive actions.
This lets us leverage any platform-specific flags and wrappers that might be present in CROSSTOOL, instead of replicating that functionality here.
=> Use the C++ toolchain to register static archive actions.

swift/internal/api.bzl, swift/internal/archiving.bzl, swift/internal/providers.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Rollback of commit 522cd9d4e8f88fb5caac2945b3f6d38bd0cddba3
Broke some internal targets.
Use the C++ toolchain to register static archive actions.
This lets us leverage any platform-specific flags and wrappers that might be present in CROSSTOOL, instead of replicating that functionality here.
=> Rollback of commit 522cd9d4e8f88fb5caac2945b3f6d38bd0cddba3

swift/internal/api.bzl, swift/internal/xcode_swift_toolchain.bzl, tools/wrappers/swift_wrapper.sh
Support -debug-prefix-map for Xcode 10.2 (Swift 5.0) and higher.
=> Support -debug-prefix-map for Xcode 10.2 (Swift 5.0) and higher.

swift/internal/derived_files.bzl
Fix filenames with spaces after switching to the CROSSTOOL archive action.
=> Fix filenames with spaces after switching to the CROSSTOOL archive action.

swift/internal/xcode_swift_toolchain.bzl
Work around a bug in DottedVersion.compare_to.
It appears that the comparator erroneously reports that `10.0.0.10A255 >= 10.2.0.10E125`; the problem is in the handling of the last component. To avoid this, we trim the version number down to at most three components until the bug is fixed.
=> Work around a bug in DottedVersion.compare_to.

swift/internal/swift_binary_test.bzl
Currently, if you have some `--linkopt=...` options specified on the Bazel command line, `swift_binary`/swift_test targets will NOT get these in their final link. This means that you cannot reliably use e.g. `-fsanitize=address` with your cpp transitive dependencies, because the final link might not pass that option to clang and it won't include the library support necessary to define some of the symbols that were inserted earlier in the compile by ASan. This PR attempts to fix this by adding `ctx.fragments.cpp.linkopts` to the list of linker options in these targets, so that the requested linkopts are respected in the final link. First time contributor, so let me know if this is the right way to do this, or if there's a better way.
=> Use cpp command-line linkopts during final link

third_party/com_github_grpc_grpc_swift/BUILD.overlay
This is the only warning produced by this library. It seems like
upstream they have this off, or they compile things that we're not that
use these other functions.
=> Disable -Wunused-function for BoringSSL

swift/internal/swift_library.bzl
Migrate `swift_library` to `swift_common.compile`.
=> Migrate `swift_library` to `swift_common.compile`.

swift/internal/swift_library.bzl
Fix `defines` being dropped after migration to the new API.
=> Fix `defines` being dropped after migration to the new API.

README.md, swift/internal/xcode_swift_toolchain.bzl
This allows you to pass `--define=SWIFT_CUSTOM_TOOLCHAIN=toolchain.id`
to specify a custom swift toolchain like the ones downloaded from
https://swift.org/download/#snapshots to use.
=> Add custom macOS Swift toolchain support

README.md, tools/dump_toolchains/BUILD, tools/dump_toolchains/dump_toolchains.sh
This is useful in combination with https://github.com/bazelbuild/rules_swift/pull/214
=> Add CLI for dumping Swift toolchain bundle ids

swift/internal/xcode_swift_toolchain.bzl
When using ld through clang on macOS with TOOLCHAINS set, since bazel
restricts the PATH, ld cannot be found since it's not part of the Swift
toolchain, and you get this error:
```
clang-7: error: unable to execute command: Executable "ld" doesn't exist!
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```
This now only adds this environment variable to Swift invocations.
=> Fix custom Swift toolchain when linking

swift/repositories.bzl
Bump up the SwiftProtobuf and Swift gRPC versions to support Swift 5.
=> Bump up the SwiftProtobuf and Swift gRPC versions to support Swift 5.

swift/internal/swift_module_alias.bzl
Add missing "cpp" fragment to `swift_module_alias`.
=> Add missing "cpp" fragment to `swift_module_alias`.

swift/internal/swift_import.bzl
Add ctx argument to cc_common.configure_features
In order to migrate C++ rules to platforms, we need the access to the C++
configuration fragment in Starlark APIs. All existing APIs have already access
to it, but cc_common.configure_features doesn't. This change adds a
ctx argument to configure_features.
This is the migration needed for
https://github.com/bazelbuild/bazel/issues/7793, and is part of the effort for
https://github.com/bazelbuild/bazel/issues/6516.
If the rule doesn't depend on cpp fragment yet, you will have to add `fragments
=['cpp']` argument to the rule() call.
Note that this behavior is only available in Bazel 0.25 (to be released this month).
=> Add ctx argument to cc_common.configure_features

tools/common/file_system.cc, tools/worker/work_processor.cc
This should be a safe simple addition. From man `copyfile(3)`:
> Try to clone the file instead.  This is a best try flag i.e. if cloning fails, fallback to copying the file.
=> Request cloning using COPYFILE_CLONE

swift/internal/swift_proto_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl
Avoid accidentally pulling in CcInfo providers from proto_library dependencies by not calling new_objc_provider in compiling.bzl.
=> Avoid accidentally pulling in CcInfo providers from proto_library dependencies by not calling new_objc_provider in compiling.bzl.

swift/internal/swift_library.bzl
In https://github.com/bazelbuild/rules_swift/commit/32275ca0536eca5610a915f7b26cb841ca0031a3 when the additional_input local variable was introduced, this went from passing `ctx.attr.swiftc_inputs` to passing `ctx.files.swiftc_inputs` into `expand_locations`. This breaks, since the underlying `expand_location` only allows `Target` types, resulting in the following error when passing any file-like target to `swiftc_inputs`:
```
expected type 'Target' for 'targets' element but got type 'File' instead
```
This switches the two `expand_locations` calls back to using `ctx.attr.swiftc_inputs`.
=> Fix copts and linkopts relying on input files

tools/worker/work_processor.cc
Follow up to #232. If copying output files fails, mark the worker response as having failed.
=> Set worker exit_code to failure if copying files fails

swift/internal/linking.bzl
Remove the `-Wl,-z,notext` workaround.
=> Remove the `-Wl,-z,notext` workaround.

swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl
Get the C++ runtime to link from CcToolchainInfo, if necessary.
=> Get the C++ runtime to link from CcToolchainInfo, if necessary.

swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Remove the SwiftToolchainInfo.cc_toolchain_files field.
CcToolchainInfo now provides a field for these, so we no longer have to pass them around separately.
=> Remove the SwiftToolchainInfo.cc_toolchain_files field.

swift/internal/utils.bzl
Fix iterating over depsets
Iterating over depsets will be prohibited soon, they need to be converted to lists explicitly using the `to_list()` method.
=> Fix iterating over depsets

swift/internal/swift_module_alias.bzl
Make `swift_module_alias` not print a warning.
=> Make `swift_module_alias` not print a warning.

swift/internal/compiling.bzl
Rollback of commit bf376ebec2c0328b207769f41b591a0873883879
Broke some projects.
Copybara import of the project:
- b5a410a0a560dd48d3305b22607370c6d2f5279a Add cc_library deps to the force_load list if they have a... by Josh Faust <josh@torch3d.com>
- ece6f4f117999e955493e96ab2bb730a553db840 Merge b5a410a0a560dd48d3305b22607370c6d2f5279a into d0e5f... by Josh Faust <jfaust@users.noreply.github.com>
=> Rollback of commit bf376ebec2c0328b207769f41b591a0873883879

swift/stats.bzl, tools/compile_stats/BUILD, tools/compile_stats/README.md, tools/compile_stats/build.sh, tools/compile_stats/main.swift
Add a report generator to the compile stats collector.
Now when running tools/compile_stats/build.sh, the output will be a Markdown-formatted report of every compilation in the build, sorted from slowest to fastest.
=> Add a report generator to the compile stats collector.

swift/internal/swift_module_alias.bzl
Have swift_module_alias correctly set the module name in the SwiftInfo provider it creates
=> Have swift_module_alias correctly set the module name in the SwiftInfo provider it creates

tools/compile_stats/build.sh
Use an explicit loop instead of xargs when collecting compile stats.
xargs fails when a path is very long (over 255 characters).
=> Use an explicit loop instead of xargs when collecting compile stats.

swift/internal/xcode_swift_toolchain.bzl
As of Xcode 11 beta 4, the Swift libraries no longer exist in the
toolchain, so Xcode passes this as well.
=> Add /usr/lib/swift to library search paths

README.md
I think many people just copy and paste the README into their WORKSPACE file. It should use the latest version. It would be ideal to automate updating it on every release, but I don't know how releases are cut. Are they cut manually?
=> Use latest version in README

swift/internal/features.bzl
Ensure that `-g` gets passed to `swiftc` even for opt builds that want full debug symbols (for dSYMs).
=> Ensure that `-g` gets passed to `swiftc` even for opt builds that want full debug symbols (for dSYMs).

swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Refactor (and properly support) link stamping for Swift binaries.
=> Refactor (and properly support) link stamping for Swift binaries.

swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Rollback of commit a00d8558d868f75632cdb980c76a38a1405a9a68
Broke some projects.
Refactor (and properly support) link stamping for Swift binaries.
=> Rollback of commit a00d8558d868f75632cdb980c76a38a1405a9a68

swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Rollback of commit f0c12e6354cf6bd7d8a8e56200cff03e9965f6e1
Still broke some targets.
Refactor (and properly support) link stamping for Swift binaries.
=> Rollback of commit f0c12e6354cf6bd7d8a8e56200cff03e9965f6e1

swift/internal/linking.bzl
Make sure that embedded runtimes are also included in the inputs of the link action.
=> Make sure that embedded runtimes are also included in the inputs of the link action.

swift/internal/swift_protoc_gen_aspect.bzl
Just pass a name, not a target.
=> Just pass a name, not a target.

examples/xplatform/proto/BUILD, examples/xplatform/proto/example.proto, examples/xplatform/proto/main.swift
Expand the example to include WKT usage.
Not only shows using the WKT a little, but also servers to exercise
more of swift_proto_library since the WKTs get pulled in thru the runtime
and thus are special handled in the rule's implementation.
=> Expand the example to include WKT usage.

swift/internal/swift_c_module.bzl, swift/internal/utils.bzl
Remove reference to non-existent `includes` attribute in `swift_c_module` implementation.
Also clean up the rule in general, and permit it to now have multiple dependencies instead of just a single one (a restriction that can be lifted since the new `CcInfo` providers have been properly mergeable in Starlark).
Fixes #286.
=> Remove reference to non-existent `includes` attribute in `swift_c_module` implementation.

swift/internal/compiling.bzl
When index_while_building is enabled, if a target has customized `-index-store-path` via its `copts`, then this change will prevent rules_swift from adding its own `-index-store-path`. In particular, this allows turning on indexing globally while also disabling indexing of specific modules by specifying `copts = ["-index-store-path", ""]`.
=> Disable index_while_building when providing -index-store-path

swift/internal/proto_gen_utils.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/utils.bzl
This is necessary for the rule set to work with
`--incompatible_generated_protos_in_virtual_imports` (and also with
`proto_library` rules with `strip_import_prefix` / `import_prefix`)
=> Make rules_swift work with virtual import directories.

swift/internal/api.bzl, swift/internal/compiling.bzl
Previously there were 2 checks to see if WMO was enabled, but one wasn't
checking the features. This resulted in build failures because not all
outputs were created. Now there is 1 source of truth for this and the
determination is passed along.
=> Fix compilation with opt_uses_wmo

swift/internal/swift_usage_aspect.bzl
With the changes in https://github.com/bazelbuild/rules_apple/pull/566, the `swift_usage_aspect` needs to handle a new case.
If a rule and an aspect both provide the same provider type, bazel raises this error:
[src/main/java/com/google/devtools/build/lib/analysis/configuredtargets/MergedConfiguredTarget.java#L167](https://github.com/bazelbuild/bazel/blob/efb3f1595ee897484c477168b8da42b67602e10e/src/main/java/com/google/devtools/build/lib/analysis/configuredtargets/MergedConfiguredTarget.java#L167)
This changes `swift_usage_aspect` to not propagate a `SwiftUsageInfo` if the target already does. Specifically, this makes the updated `apple_static_framework_import` work in apps that have other swift deps.
=> Stop propagating duplicate SwiftUsageInfo providers from swift_usage_aspect

.bazelci/presubmit.yml
Disable a bunch of buildifier warnings until we migrate.
=> Disable a bunch of buildifier warnings until we migrate.

swift/internal/xcode_swift_toolchain.bzl
Fix the `TOOLCHAINS` env var for custom Xcode toolchains.
This was previously set in a separate dictionary to prevent conflicts with static library archiving actions, but now those go through the C++ APIs and those conflicts no longer occur. Unfortunately, that change also broke this, because the new dictionary was no longer being used anywhere, so this variable never makes it through. The fix is to just set it on the original `env` dictionary again.
=> Fix the `TOOLCHAINS` env var for custom Xcode toolchains.

swift/internal/xcode_swift_toolchain.bzl
Remove some workarounds that no longer apply for old bugs.
- Bazel's DottedVersion used to be broken when an interior component was zero.
- Remove a check for an incompatible flag that has been flipped to true for a few months.
=> Remove some workarounds that no longer apply for old bugs.

swift/internal/swift_binary_test.bzl, tools/xctest_runner/xctest_runner.sh.template
Make the actual output of a `swift_test` target the `.xctest` bundle (for Xcode toolchains, when the feature is not disabled).
=> Make the actual output of a `swift_test` target the `.xctest` bundle (for Xcode toolchains, when the feature is not disabled).

swift/internal/compiling.bzl
Avoid introducing duplicate entries in the import search path when there are multiple swiftmodules in a single directory
=> Avoid introducing duplicate entries in the import search path when there are multiple swiftmodules in a single directory

swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/xcode_swift_toolchain.bzl
Update `swift_{binary,test}` to use `cc_common.link`.
This simplifies the logic used to link executables and removes potential divergence between behaviors of the Swift rules and the C++ rules. It also makes it easier to support emitting dynamic libraries in the future.
=> Update `swift_{binary,test}` to use `cc_common.link`.

test/rules/BUILD, test/rules/provider_test.bzl
Add an analysis test rule to check the values of file-based provider fields.
=> Add an analysis test rule to check the values of file-based provider fields.

test/rules/provider_test.bzl
More provider_test fixes:
- Actually pass config_settings through to analysistest.make.
- Make sure the implementation handles the transition and non-transition case.
=> More provider_test fixes:

test/rules/provider_test.bzl
config_settings must default to {}, not None.
=> config_settings must default to {}, not None.

swift/internal/attrs.bzl, swift/internal/features.bzl, swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_library.bzl, swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl, test/BUILD, test/fixtures/BUILD, test/fixtures/common.bzl, test/fixtures/private_deps/BUILD, test/fixtures/private_deps/Empty.swift, test/fixtures/private_deps/private.h, test/fixtures/private_deps/public.h, test/private_deps_tests.bzl
Add support for implementation-only imports via the `private_deps` attribute when using Swift 5.1 or higher.
Targets in `private_deps` make their swiftmodules available to direct dependents but do not propagate them further up the graph.
=> Add support for implementation-only imports via the `private_deps` attribute when using Swift 5.1 or higher.

swift/internal/api.bzl, swift/internal/features.bzl
This adds a feature to use `-Osize` instead of `-O` which apparently
should rarely have a major impact on "normal" apps' performance
https://forums.swift.org/t/performance-impact-of-swift-compiler-optimization-level/30170/2
=> Add -Osize support

swift/internal/actions.bzl, swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/providers.bzl, swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Refactor slightly how actions are registered in the Swift rules.
Swift toolchains now have a `swift_executable` attribute that lets the configurator replace the Swift driver used by the rules with a custom executable in their workspace. This can be useful for testing the build rules alongside compiler development, and since that file is part of the workspace and a proper input of actions, it also works correctly across remote build environments.
Also remove the no-longer-used `SwiftToolchainInfo.clang_executable` field, now that linking has migrated to the `cc_common.link` API.
=> Refactor slightly how actions are registered in the Swift rules.

swift/BUILD, swift/internal/attrs.bzl, swift/internal/swift_toolchain.bzl, swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl
Allow the Swift driver to be overridden by a command line flag.
This will not work with Bazel until repository-prefixed command line flags are working (https://github.com/bazelbuild/bazel/issues/9177).
=> Allow the Swift driver to be overridden by a command line flag.

swift/internal/compiling.bzl
Use depset(direct=...) not depset(items=...)
Fixes #360
RELNOTES: None
=> Use depset(direct=...) not depset(items=...)

swift/repositories.bzl
Update the version of protobuf being used.
This will make some progress on #361, but there are still some directly
proto_library usages within swift_protobuf that will need updating also.
RELNOTES: None
=> Update the version of protobuf being used.

swift/internal/xcode_swift_toolchain.bzl
Add execution requirements based on Xcode availability to Swift rules that care about Xcodes.
This is part of a series of changes to enable Xcode autodetection, but this does not currently change behavior.
=> Add execution requirements based on Xcode availability to Swift rules that care about Xcodes.

swift/internal/actions.bzl, swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/features.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_toolchain.bzl, swift/internal/toolchain_config.bzl, swift/internal/xcode_swift_toolchain.bzl
Start refactoring action registration to be more "modular".
Inspired loosely by CROSSTOOL, this lets us split out various parts of toolchain and action configuration so that they can be shared among multiple actions. This will be critical when the build rules start supporting actions other than SwiftCompile, such as emitting precompiled modules for C/Obj-C dependencies.
There are two concepts: a tool config and an action config. A tool config describes an executable and some of its properties (its environment, execution requirements, etc.). This means these can now differ between different tools in the same toolchain (previously, all tools shared the same environment and exec reqs). An action config describes how args and inputs are decided for an action, based on which features are set …
=> Start refactoring action registration to be more "modular".

swift/internal/api.bzl, swift/internal/autolinking.bzl, swift/internal/compiling.bzl, swift/internal/swift_toolchain.bzl
Move autolink-related logic out of compiling.bzl and into its own file.
Also clean up the parameter names slightly, and make a minor tweak to the behavior so that objects output by modulewrap don't get passed to autolink-extract (they aren't harmful, but they aren't helpful either).
=> Move autolink-related logic out of compiling.bzl and into its own file.

swift/internal/xcode_swift_toolchain.bzl
Correct spelling of `-embed-bitcode-marker` flag (not `markers`).
=> Correct spelling of `-embed-bitcode-marker` flag (not `markers`).

swift/internal/actions.bzl, swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/swift_toolchain.bzl, swift/internal/toolchain_config.bzl, swift/internal/xcode_swift_toolchain.bzl
Migrate a number of feature-driven compilation flags to the action config model.
This change removes `swiftc_command_line_and_inputs` as a public API (there are no users currently within Google, which gives us an opportunity to rethink its design under the new model). Then, we move the majority of its feature checks that control command line flags to equivalent COMPILE action configs.
This got slightly awkward around the current treatment of WMO, since we need to check both the feature configuration and the user compile flags to determine what kind of outputs are needed, so in some cases, the check had to be split—for example, the action config already filters based on feature, so the configurator function needs to check the user compile flags for the presence of WMO based only if …
=> Migrate a number of feature-driven compilation flags to the action config model.

swift/internal/compiling.bzl
Previously this list would be interpreted backwards
Fixes https://github.com/bazelbuild/rules_swift/issues/338
This is also how this is done in rules_apple https://github.com/bazelbuild/rules_apple/blob/53282252b393e451634d4f410d555df3f295c00e/apple/internal/swift_support.bzl#L84
=> Fix swift_library linkopts ordering for ObjC

swift/internal/api.bzl, swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/swift_library.bzl, test/BUILD, test/fixtures/generated_header/BUILD, test/fixtures/generated_header/Empty.swift, test/generated_header_tests.bzl, test/rules/analysis_failure_test.bzl, test/rules/provider_test.bzl
Add a `generated_header` attribute to `swift_library`.
Co-authored-by: Samuel Giddins <segiddins@users.noreply.github.com>
Closes #350.
=> Add a `generated_header` attribute to `swift_library`.

swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_toolchain.bzl
This fixes an issue where if you update the version of Swift on a Linux machine you share caches with previous Swift versions which can cause builds to fail incorrectly. Now the output of `swiftc -version` is included as an input of all compile actions. This is analogous to how the Xcode version is provided for macOS actions.
=> Add `swiftc -version` as input to Linux actions

.bazelci/presubmit.yml
bzl-visibility is no longer in the defaults.
Looking at the issue mentioned, it doesn't sound like it can be made to
generally work, so it got removed from the default set in
bazelbuild/buildtools#721
RELNOTES: None
=> bzl-visibility is no longer in the defaults.

swift/internal/module_maps.bzl, swift/internal/non_swift_target_aspect.bzl, test/fixtures/private_deps/BUILD
Require the `swift_module` tag on `cc_library` targets that are
(direct or transitive) dependencies of `swift_*` targets to generate
module maps for them and import them into Swift.
This wasn't a hard requirement before because, even if we created a
module map for a library that didn't contain Swift-compatible C code,
as long as no Swift code actually tried to import it, no harm was
done. This will no longer be true when we start precompiling explicit
modules for C dependencies, at which point we **must** be able to
distinguish which ones are Swift-compatible and which are not (i.e.,
currently most of them).
RELNOTES: `cc_library` targets must have `swift_module` or
`swift_module=ModuleName` in their `tags` in order to be imported into
Swift.
=> Require the `swift_module` tag on `cc_library` targets that are

swift/internal/compiling.bzl, swift/internal/swift_library.bzl
Allow `.swiftinterface` files to be emitted without library evolution enabled by adding `--features=swift.emit_swiftinterface` to the build.
Note that doing so causes the compiler to emit a warning that `.swiftinterface` files are not supported without library evolution. However, the file is still emitted and has what appears to be somewhat valid content.
These interface files should not be used as inputs for upstream builds, and certainly not used for the creation of distributed libraries. The purpose of this change is to allow the creation of other source tooling that loads `.swiftinterface` files, when that tooling may be built from sources of the compiler that don't match the version that was used to build the module itself.
=> Allow `.swiftinterface` files to be emitted without library evolution enabled by adding `--features=swift.emit_swiftinterface` to the build.

test/BUILD, test/fixtures/swift_through_non_swift/BUILD, test/fixtures/swift_through_non_swift/Empty.h, test/fixtures/swift_through_non_swift/Empty.swift, test/swift_through_non_swift_tests.bzl
Add a test to verify that `.swiftmodules` are propagated through non-Swift targets, like `objc_library`.
=> Add a test to verify that `.swiftmodules` are propagated through non-Swift targets, like `objc_library`.

swift/internal/actions.bzl, swift/internal/compiling.bzl, swift/internal/toolchain_config.bzl
We noticed that `swiftc` command lines were containing offsetting flags when enabling the `cacheable_swiftmodules` feature.
```
-Xfrontend -no-serialize-debugging-options -Xfrontend -serialize-debugging-option
```
The cause is the `not_features` used in this case: https://github.com/bazelbuild/rules_swift/blob/657eda57a097980848dbb3c880b94faeddaa3cd1/swift/internal/compiling.bzl#L211-L223
Which says to add `-serialize-debugging-option` using this logic:
```py
if not (opt and cacheable_swiftmodules):
```
but the logic should be:
```py
if not (opt or cacheable_swiftmodules):
```
This fix changes `not_features` to match `features` in structure and meaning. Now, the `or` can be expressed using a list of list of feature names:
```
not_features = [
[SWIFT_FEATURE_OPT], …
```
=> Allow cacheable_swiftmodule feature independent of compilation mode

swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/utils.bzl
Migrate Objc compile info to CcCompilationContext
Step 1 of 3-step plan:
1. Migrate the definitions.
2. Migrate the uses.
3. Delete old ObjcProvider definitions.
See https://github.com/bazelbuild/bazel/issues/10674.
RELNOTES: None
=> Migrate Objc compile info to CcCompilationContext

.bazelci/presubmit.yml
Turn off the bzl-visibility check
It was added back to the defaults: https://github.com/bazelbuild/buildtools/pull/795
But the report issue still seems to be open: https://github.com/bazelbuild/buildtools/issues/718
RELNOTES: None
=> Turn off the bzl-visibility check

swift/internal/swift_binary_test.bzl, swift/internal/swift_clang_module_aspect.bzl, swift/internal/swift_common.bzl, swift/internal/swift_library.bzl
Rename `non_swift_target_aspect` to `swift_clang_module_aspect`.
This is already the public name of the aspect as exposed through `swift_common`; this change makes its internal name consistent with that.
=> Rename `non_swift_target_aspect` to `swift_clang_module_aspect`.

swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
Replace custom implementation of link stamping with the new `cc_common.link` stamp argument.
This also changes the `stamp` attribute on `swift_{binary,test}` from a Boolean to an integer, in order to support tri-state values (1, 0, -1). The default for `swift_binary` has changed from `True` to `-1`, which means "behavior is determined by the `--[no]stamp` flag". In other words, the interface and behavior are now identical to `cc_binary`.
RELNOTES: Link stamping is now supported uniformly across all toolchains, including Xcode toolchains.
=> Replace custom implementation of link stamping with the new `cc_common.link` stamp argument.

swift/internal/compiling.bzl
Some Xcode integrations need these, and by having them as output groups (along with the use of aspects) remote build without the bytes can be enabled properly.
=> Add swiftmodule and swiftdoc to output_groups

swift/internal/swift_autoconfiguration.bzl
This was incorrectly passing the source file as a params file producing
this error:
```
DEBUG: .../swift_autoconfiguration.bzl:65:5: 1 <unknown>:0: error: no such file or directory: '@_implementationOnly'
<unknown>:0: error: no such file or directory: 'import'
<unknown>:0: error: no such file or directory: 'Foundation'
<unknown>:0: error: no such file or directory: 'print(Hello)'
```
=> Fix checking for @_implementationOnly support

swift/internal/compiling.bzl
Previously the assumption was that if `-num-threads` is `1`, only a
single object is emitted. It turns out in swiftc there is a difference
between 0 and 1 to this value, so even with 1 multiple objects are
emitted.
Without this change linking fails when passing this flag like:
```
bazel build examples/xplatform/xctest --swiftcopt=-num-threads --swiftcopt=1 --swiftcopt=-wmo
```
=> Fix passing -num-threads with -wmo

swift/internal/compiling.bzl, test/debug_settings_tests.bzl
We've seen cases with envoy-mobile where, when producing a static framework artifact, neither serialize debugging options flag is passed, but `-fdebug-prefix-map=/private/var/tmp/...` is embedded in the swiftmodule file from the C++ libraries it depends on. This appears to be because the default in the Swift compiler prefers embedding them in some cases.
=> Allow cacheable swiftmodules option with opt

swift/internal/feature_names.bzl
According to the actual implementation [line 1091 of compiling.bzl](https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/compiling.bzl#L1091), deciding whether to generate module map depends on whether we have generated headers to start with. In practice we have this feature enabled without the need to pass `no_generated_header`, therefore the documentation is stated the opposite.
**I know I suppose to create an issue but this is trivial (?) that I decide to just open up a PR instead. Let me know what should I do since I am newbie to contributing to open source :)**
=> Fix incorrect doc for `no_generated_module_map` feature

swift/internal/BUILD
This must exist within google but not publicly. But this file is marked
as exports_files
=> Update action_names path

.bazelci/presubmit.yml, WORKSPACE, examples/apple/objc_interop/BUILD, examples/xplatform/c_from_swift/BUILD, examples/xplatform/grpc/BUILD, examples/xplatform/proto/BUILD, swift/internal/swift_grpc_library.bzl, swift/internal/swift_proto_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl, test/debug_settings_tests.bzl, test/fixtures/private_deps/BUILD, test/fixtures/swift_through_non_swift/BUILD, test/generated_header_tests.bzl, test/private_deps_tests.bzl, test/swift_through_non_swift_tests.bzl, third_party/bazel_protos/BUILD, third_party/com_github_grpc_grpc_swift/BUILD.overlay, third_party/com_github_nlohmann_json/BUILD.overlay, tools/common/BUILD, tools/worker/BUILD
Some of these are imports that were being avoided. The name warning is still an issue https://github.com/bazelbuild/buildtools/issues/821 but I think it's preferred to move it to the default arg instead of having a disable for it.
=> Fix buildifier warnings

swift/internal/swift_autoconfiguration.bzl
Fixes https://github.com/bazelbuild/rules_swift/issues/16
=> Add error for no Linux swiftc path

tools/dump_toolchains/dump_toolchains.sh
Before:
```
swift-DEVELOPMENT-SNAPSHOT-2020-01-29-a.xctoolchain -> org.swift.50202001291a
swift-TEST-SNAPSHOT-2020-01-23-a.xctoolchain -> org.swift.50202001231a
swift-latest.xctoolchain -> org.swift.50202001291a
```
After:
```
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2020-01-29-a.xctoolchain -> org.swift.50202001291a
/Library/Developer/Toolchains/swift-TEST-SNAPSHOT-2020-01-23-a.xctoolchain -> org.swift.50202001231a
/Library/Developer/Toolchains/swift-latest.xctoolchain -> org.swift.50202001291a
/Users/ksmiley/Library/Developer/Toolchains/swift-5.2-DEVELOPMENT-SNAPSHOT-2020-04-28-a.xctoolchain -> org.swift.52202004281a
/Users/ksmiley/Library/Developer/Toolchains/swift-latest.xctoolchain -> org.swift.52202004281a
```
=> Update dump_toolchains to support home dir

swift/internal/compiling.bzl, test/fixtures/generated_header/BUILD, test/generated_header_tests.bzl
E.g., I work on a large project which has always used `#import <SomeModule/SomeModule-Swift.h>` for swift-to-objc, but using `SomeModule/SomeModule-Swift.h` as the generated header for our bazel migration causes it to fail
=> Allow generated headers with path separators

swift/internal/linking.bzl, swift/internal/providers.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
This is to prevent the linking failures if a `swift_library` target has
too many files that can cause its linking args to become longer than the
system's command length limits. This does not change the behavior when
building on Linux yet, since `ar` does not support passing arguments
using a parameter file.
Redo of https://github.com/bazelbuild/rules_swift/pull/349 with platform-awareness. This is critical if you have a very large Swift target.
=> Use a parameter file when linking Swift libraries when the host machine is macOS

swift/internal/swift_binary_test.bzl
=> Read the `custom_malloc` configuration field in `swift_{binary,test}` to use an allocator provided by the `--custom_malloc` flag, if any.

swift/internal/derived_files.bzl
This was already handled for basenames, but not for directory names between the target's package and the file; for example, if one had `swift_library(name = "ArgumentParser", ...)` in a `BUILD` file that also contained `Sources/ArgumentParser/Parsable Types/ParsableCommand.swift`.
PiperOrigin-RevId: 329799243
=> Ensure that intermediate outputs created for Swift source files (such as object files) do not have spaces in their names.

swift/BUILD, swift/internal/BUILD, swift/repositories.bzl, test/fixtures/BUILD
Mostly so depending on them from a stardoc rule works now we load rules_proto
Mostly autogenerated & then tweaked based on the gazelle in bazelbuild/bazel-skylib#271
=> Update bzl_library targets

swift/internal/feature_names.bzl, swift/internal/proto_gen_utils.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/utils.bzl
The DescriptorSets ProtoInfo exposes don't have source info, so the generated
source don't have the comment. https://github.com/bazelbuild/bazel/issues/9337
is open to attempt to get that, but this provides a way to opt into forcing it.
This does come with a minor risk for cross repository and/or generated proto
files where the protoc command line might not be crafted correctly, so it
remains opt in.
RELNOTES: None
PiperOrigin-RevId: 330538313
=> Add a feature flag to enable generation from raw proto sources.

swift/internal/swift_grpc_library.bzl
The DescriptorSets ProtoInfo exposes don't have source info, so the generated
source don't have the comment. https://github.com/bazelbuild/bazel/issues/9337
is open to attempt to get that, but this provides a way to opt into forcing it.
This does come with a minor risk for cross repository and/or generated proto
files where the protoc command line might not be crafted correctly, so it
remains opt in.
This is followup to the previous change that did this for swift_proto_library.
NOTE: The current version of swift grpc depended on doesn't include comments,
but the NIO version appears to support it for methods, so landing the work
in advance of things updating to that version.
RELNOTES: None
PiperOrigin-RevId: 330729710
=> Honor the feature flag to enable generation from raw proto sources.

README.md, swift/extras.bzl
I first saw this pattern in [@com_github_grpc//bazel:grpc_extra_deps.bzl](https://github.com/grpc/grpc/blob/master/bazel/grpc_extra_deps.bzl) and thought it was a great way to group dependencies. Should any dependencies be added or removed in future changes, users will more seamlessly be able to update.
Sorry, I didn't file an issue ticket first. I should have read `CONTRIBUTING.md` before opening the pull request 😅. I feel the changes here are small and straight forward enough that any discussion can happen here. Though I expect this to either be rejected or merged potential pending some name changes.
=> Added helper macro for declaring transitive dependencies

swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
This is phase 2 of of the switch to toolchain transitions. See https://github.com/bazelbuild/bazel/issues/11584 for details.
This shouldn't be merged into rules_swift's master branch until https://cs.opensource.google/bazel/bazel/+/58fdf63d81cc71f0315918b111fc56f4c039f1a5 is in a Bazel release (which should be 3.7, https://github.com/bazelbuild/bazel/issues/12188).
PiperOrigin-RevId: 334610489
=> Update rules_swift to use the toolchain transition.

swift/internal/actions.bzl, swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl, test/BUILD, test/split_derived_files_tests.bzl
theoretically this would speed up incremental builds but cause slightly worse clean build time
=> Introduce feature to register a separate action to generate swift derived files

swift/internal/compiling.bzl, test/split_derived_files_tests.bzl
The swiftmodule generation should not attempt to perform indexing.
=> Fix index while building with derived files

swift/internal/xcode_swift_toolchain.bzl, test/BUILD, test/split_derived_files_tests.bzl
The bitcode flags should not be passed to these actions otherwise you
get this warning:
```
ignoring -embed-bitcode since no object file is being generated
```
=> Fix derive files with bitcode

test/rules/action_command_line_test.bzl
This is helpful when debugging what does or doesn't exist
=> Output command lines of failed action command line tests

swift/internal/feature_names.bzl, swift/internal/xcode_swift_toolchain.bzl, test/coverage_settings_tests.bzl, test/debug_settings_tests.bzl
This is analogous to https://github.com/bazelbuild/bazel/commit/bc5883a04ef5148038edd0080e1565a0cb1688b0
It leads to more hermetic binaries and shouldn't have any impact on
debugging.
=> Add swift.remap_xcode_path feature

tools/worker/work_processor.cc
The output_file_map is only written to disk in a transformed state if an incremental build is happening. This change causes the output_file_map to only be read and processed in that case as well, leading to less work in the WMO case.
This was part of #413, but since that's dropped I'm proposing we include it on its own.
=> Only read output_file_map if it's going to be written

swift/BUILD, swift/internal/BUILD, swift/internal/attrs.bzl
PiperOrigin-RevId: 339779917
(cherry picked from commit e4ad1cc258a33946d506f1ed8805b2bdbcaeff17)
=> Create a build setting to allow forcing a Swift target to Apple with bazel transitions.

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/swift_autoconfiguration.bzl
This feature permitted an odd three-state situation around the way the implicit module cache is handled:
1. The so-called "global module cache", which is placed in `bazel-out`
2. The ephemeral module cache, which is created and destroyed around each compile action
3. A state where no flags related to the implicit module cache are passed to the compiler, meaning "do whatever the compiler does by default".
This third state is the one we want to get rid of, since the default is to place the module cache in a temp location outside the sandbox.
PiperOrigin-RevId: 344942165
(cherry picked from commit 575b819f0bc7d06e1844c0721b8470707a7b4239)
=> Remove the `swift.implicit_modules` feature.

test/fixtures/BUILD
RELNOTES: None
PiperOrigin-RevId: 345024048
(cherry picked from commit d5fa2f5d711b81c5c0b7aecf97ce07ac2dd98b58)
=> Format visibility

swift/internal/attrs.bzl, swift/internal/swift_binary_test.bzl
PiperOrigin-RevId: 345120894
(cherry picked from commit c21080442fe664cfa3f4a35fc654e10af8791b37)
=> Make the `srcs` attribute of `swift_library` mandatory and non-empty.

swift/internal/providers.bzl, swift/internal/swift_module_alias.bzl
- Make module alias use the direct modules instead with legacy fall back for the
existing support.
- Validate during creation of SwiftInfo that any provided module_name matches the
first module (if any modules are provided).
RELNOTES: None
PiperOrigin-RevId: 345237478
(cherry picked from commit 46613b2f6056cfd9b0c491f72f1faa57c938e3db)
=> Migration off SwiftInfo.module_name.

swift/internal/providers.bzl
RELNOTES: None
PiperOrigin-RevId: 347033042
(cherry picked from commit 3355e61c8cddd33e2e3158d61a3ddefd06368b38)
=> Require `name` to be a named argument.

swift/internal/providers.bzl
RELNOTES: None
PiperOrigin-RevId: 347035229
(cherry picked from commit 6e4e3ca24f5d927828cc2b115fc64b75b8b0ab52)
=> Retire `module_name` from create_swift_info.

swift/internal/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 347841955
(cherry picked from commit 875de9fc0b08bedb30e7de2e3f992cd9f818e40d)
=> Allow `optional_implicit_deps` and `required_implicit_deps` to be set on an `xcode_swift_toolchain` target.

swift/internal/xcode_swift_toolchain.bzl
In 768bfe3fe885f92fbaea75488268e2612ab9ef9c this was moved and this wasn't added (since it isn't used inside Google)
=> Fix XCTest -I for derived files

swift/internal/compiling.bzl
In some cases (e.g., if a module map defines multiple modules and both or more were present in the dependency graph), the `depset` won't deduplicate the module structures because their values are distinct (they contain different module names). That's the behavior we want, but it also resulted in the `-fmodule-map-file=` for that module map appearing multiple times on the command line.
PiperOrigin-RevId: 348139990
(cherry picked from commit df1198b3826b7d10ab91b04250f672d812acfb0f)
=> Uniquify `-fmodule-map-file=` flags passed to `swiftc`.

swift/internal/attrs.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_grpc_library.bzl
Markdown bullet lists work fine in the general descriptions block of macros/rules/providers, but for rule attributes and provider fields the the markdown is a table, and `*` has no means (and stardoc transforms the content to remove newlines). The above issue is to support catch these and marking html bullet lists out of them, but until that is done, adding a blank line between each bullet gets slightly more readable generated/render documents.
PiperOrigin-RevId: 348682502
(cherry picked from commit 5383052ecc5e008dd9e4a42edf2570c60bd6dc5c)
=> Work around https://github.com/bazelbuild/stardoc/issues/78.

swift/internal/compiling.bzl, swift/internal/providers.bzl
System modules differ from non-system modules in that we don't pass the module map to the compiler via `-fmodule-map-file` for system modules in implicit module builds, only in explicit module builds. This is because module maps passed via `-fmodule-map-file` are always treated as non-system modules, which affects how diagnostics are emitted when their headers are parsed, and some Swift modules like `SwiftOverlayShims` don't declare themselves as `[system]` in their module map file but contain small nullability issues. Such headers *must* be found through a standard header search via a system path like `-isystem` so that they don't cause builds to fail if they treat warnings more severely.
PiperOrigin-RevId: 351896080
(cherry picked from commit 214061922f68fbf4f0f7fcf4df9d54af5b279cf5)
=> Allow modules propagated by `SwiftInfo` to indicate whether they are system modules.

swift/internal/compiling.bzl, swift/internal/providers.bzl, swift/internal/swift_library.bzl
It was deprecated a while ago, and it avoids the collection in swift_library now.
RELNOTES: None
PiperOrigin-RevId: 351595739
(cherry picked from commit 5b1aabd92e93e38d0e98dcaa6ce062f9476d9d86)
=> Remove swift_version.

swift/internal/compiling.bzl
- Allow Swift compiles to use implicit modules even if `swift.use_c_modules` is enabled (a necessary fallback if some dependencies don't emit explicit modules).
- Continue to disallow usage of implicit modules when compiling explicit C/Objective-C modules because those implicit module paths would become embedded in the `.pcm` files, making them immovable.
PiperOrigin-RevId: 353665654
(cherry picked from commit 2711a2b930108e48c1b22541efb5408989d2eac0)
=> Lessen restrictions on when implicit modules can be used:

swift/internal/derived_files.bzl, test/private_deps_tests.bzl
Since we pass these module maps directly to the compiler with `-fmodule-map-file`, we don't need them to be named exactly `module.modulemap`, so the extra subdirectory is also unnecessary.
PiperOrigin-RevId: 354151400
(cherry picked from commit 71998c865b827828c17dbd24bf48bb856523d4f5)
=> Simplify the paths to module maps generated by the Swift build rules.

WORKSPACE, swift/extras.bzl, swift/repositories.bzl
This updates `rules_proto`, which has been configured to use released
protoc binaries where it can.
This can be a breaking change if users have a call to `protobuf_deps()`
_before_ `swift_rules_extra_dependencies()` in their WORKSPACE. To
fix, remove `load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")`
and `protobuf_deps()` from the WORKSPACE file, and use the following
instead:
```
load(
"@build_bazel_rules_swift//swift:extras.bzl",
"swift_rules_extra_dependencies",
)
swift_rules_extra_dependencies()
```
=> Use released protoc binaries where possible

swift/internal/module_maps.bzl, swift/internal/swift_clang_module_aspect.bzl
This was an unintentional change in behavior from https://github.com/bazelbuild/rules_swift/commit/5f51ca9c5149122f41cada6122c61788d880fee9; this puts us back to the original behavior, but leaves an API in place for finer-grained control over re-exporting modules in the future. (But the BUILD rules today don't really have the flexibility to support it yet.)
PiperOrigin-RevId: 356338982
(cherry picked from commit f45eea8c02a87c3077e5209f471fe4a193b5b0ba)
=> Don't re-export the modules imported by a Swift generated header.

swift/internal/actions.bzl, swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/providers.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
This change removes of the `SwiftToolchainInfo.command_line_copts` field, no longer treating those command line flags as an odd special case. It also ensures that flags from the toolchain are passed in a unified manner regardless of which rule registers the action.
For example, Bazel-legacy Objective-C flags determined by compilation mode, like `-fstack-protector`, affect the compatibility of Clang modules and need to be passed both when compiling an explicit module and when compiling the Swift code that consumes those modules.
This required a bit more shuffling around of the way we need to handle differing outptus for WMO, since the `--swiftcopt` flags would no longer be able to be scanned directly after the toolchain configuration.
PiperOrigin-RevId: 355451642
(cherry picked from commit …
=> Move toolchain- and command-line-provided compiler flags into action configurators.

swift/internal/compiling.bzl
We've always supported this, but `swiftc` today doesn't accept the version with the equal sign and briefly looking through the history of Options.td I can't find any evidence that it ever did. We continue to support space-separated `-num-threads X`.
PiperOrigin-RevId: 355647561
(cherry picked from commit d26868fee498495a5ac66a54a540b4c50014380b)
=> No longer scan for `-num-threads=X` (specifically the form with the equal sign).

swift/internal/compiling.bzl
A small number of rules use `umbrella_header` to propagate an umbrella header for their module map that they don't propagate in any other header field. Since there is no `direct_*` version of this field, `swift_clang_module_aspect` can't easily extract the one umbrella header from the `depset` in the provider that may also include transitive umbrella headers.
PiperOrigin-RevId: 355667496
(cherry picked from commit bd8c7d45f3616c83fc54645a069f5aa76e6f3612)
=> Unconditionally add `ObjcProvider.umbrella_header` files to compiler inputs, even when preferring explicit modules.

swift/internal/compiling.bzl, swift/internal/providers.bzl, swift/internal/swift_library.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
The notion of "implicit compile-time dependencies for generated header modules only" has been added to the toolchain because generated Obj-C headers always import Foundation and Darwin, but we don't necessarily want to force those as dependencies of every Swift compilation. Likewise, the private (implementation-only) dependencies of a module shouldn't be included when generating the module map `use` decls for the Obj-C header module, because by definition, they can't be exported.
PiperOrigin-RevId: 358406043
(cherry picked from commit ab1c5cd0038c76a88738d8aff7397e728ccad3cf)
=> Compile an explicit module for the generated header of a `swift_library`.

swift/internal/compiling.bzl
This is needed since swiftc doesn't pass the framework search paths to clang, causing issues with framework style imports in headers.
=> Pass framework search paths directly to clang for pcms

swift/internal/compiling.bzl, swift/internal/feature_names.bzl
This adds a feature `swift.embed_clang_module_breadcrumbs`, if enabled,
embed absolute paths to the dependent pcm files in the debug info. This
is used as a fallback path for LLDB to reconstruct Clang types from
DWARF, when it wasn't able to import a dependent Clang module from
source. This feature is disabled by default (by passing `-Xfrontend
-no-clang-module-breadcrumbs` to swiftc) to make the compilation
outputs more cacheable.
=> Pass `-no-clang-module-breadcrumbs` to frontend jobs by default

doc/rules.md, swift/internal/attrs.bzl, swift/internal/swift_library.bzl, swift/internal/utils.bzl
This adds support for expanding make vars in copts, related: https://github.com/bazelbuild/rules_swift/issues/314
Validation of expanding a make var and location at the same time:
```
DEBUG: /private/var/tmp/_bazel_omarzl/91ff9aed2e6c366b80f6e754063967bb/external/build_bazel_rules_swift/swift/internal/swift_library.bzl:105:10: ["$(GENDIR)", "$(location //:Alamofire/Source/AFError.swift)"]
DEBUG: /private/var/tmp/_bazel_omarzl/91ff9aed2e6c366b80f6e754063967bb/external/build_bazel_rules_swift/swift/internal/swift_library.bzl:110:10: ["bazel-out/ios_arm64-fastbuild/bin", "Alamofire/Source/AFError.swift"]
```
=> make vars support in copts

swift/internal/attrs.bzl, swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/feature_names.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/swift_toolchain.bzl, test/fixtures/generated_header/BUILD, test/fixtures/private_deps/BUILD, test/generated_header_tests.bzl
Today, `swift_library` unconditionally generates a header and module map for all targets (unless rarely-used features are applied), even if the library has no APIs exported to Objective-C. This creates a small amount of unnecessary work, but that work grows significantly when explicit modules are used in the build, because we also need to compile the explicit modules for those generated headers _just in case_ some `objc_library` further up in the build graph needs to import the header.
This is the first of a few changes that will eventually require the `generates_header` attribute to be set on targets to have the generated header emitted and propagated.
This change also removes the `swift.no_generated_header` feature, since the attribute's behavior supplants it.
PiperOrigin-RevId: …
=> Add a `generates_header` attribute to `swift_library` to control Objective-C header generation.

swift/internal/utils.bzl
This ensures that, for a `swift_library` target `t`, reading from either the direct fields of `t[CcInfo].compilation_context` or `t[SwiftInfo].direct_modules[...].clang.compilation_context` produces consistent results.
PiperOrigin-RevId: 363418185
(cherry picked from commit 027e1801cace2034b75fd9732e6fa8670ea252ea)
=> Distinguish between direct and transitive information when creating the `CcInfo` for a `swift_library`.

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/providers.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_common.bzl, swift/internal/swift_library.bzl, swift/internal/swift_toolchain.bzl, swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl
-   When propagating implicit deps in the toolchain, merge and propagate the providers instead of the `Target` object itself. The `Target` object is fairly heavyweight and not intended to be propagated around the build graph.
-   Remove the `swift.minimal_deps` feature and the distinction between "required" and "optional" implicit deps.
PiperOrigin-RevId: 367044294
(cherry picked from commit 665ea7576e0794dc2d72cc7302714056ba143211)
=> Simplify and cleanup how implicit toolchain dependencies are managed.

examples/apple/objc_interop/BUILD
PiperOrigin-RevId: 362932692
(cherry picked from commit 1bcdd5756d044a4caa264dab4cac6aa321776478)
=> Update examples/tests with `generates_header = True` where necessary before flipping the attribute.

swift/internal/attrs.bzl
To generate a header, `generates_header` must be set to `True` on the target.
PiperOrigin-RevId: 367012879
(cherry picked from commit 413cc02802fff11916e5bf4738767f99cb1cf1e3)
=> Make `swift_library` not generate an Objective-C header by default.

swift/internal/swift_clang_module_aspect.bzl, swift/internal/swift_common.bzl
This API allows custom rules to opt-in to "lightweight Swift interop". If they are already propagating a `CcInfo` with a compilation context, then `swift_clang_module_aspect` will detect this provider and generate a module name/module map (if necessary), and also compile the explicit module (if enabled). This frees the custom rule from having to understand details of the Swift compilation APIs, or even having to have a dependency on the Swift toolchain at all.
PiperOrigin-RevId: 367251939
(cherry picked from commit 9be992e3d6c696978ea62a5b2def7d7e977b8df1)
=> Add `swift_common.create_swift_interop_info`.

swift/internal/swift_binary_test.bzl, swift/internal/swift_clang_module_aspect.bzl, swift/internal/swift_common.bzl, swift/internal/swift_library.bzl, swift/swift.bzl
RELNOTES: swift_clang_module_aspect is directly exported instead of being in swift_common.
PiperOrigin-RevId: 367673524
(cherry picked from commit bf8243d1732b7cc48e99c045ebd03387014e620e)
=> Move swift_clang_module_aspect out of swift_common and directly expose it.

swift/internal/compiling.bzl
PiperOrigin-RevId: 368004995
(cherry picked from commit ec941966bd596ff55f5c957d5993abeb0fbf5210)
=> Update the module name derivation algorithm to handle any sequence of non-identifier characters safely.

swift/internal/features.bzl, swift/internal/xcode_swift_toolchain.bzl
The information is identical, and we would like to migrate all uses to
cpp fragment so that we can delete the info in objc fragment.
PiperOrigin-RevId: 370899517
(cherry picked from commit 3e53aa28a558b7cb690cae10afd63ca98b221a35)
=> Use cpp fragment, instead of objc fragment, to determine whether to generate dsym

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/xcode_swift_toolchain.bzl, tools/worker/swift_runner.cc, tools/worker/swift_runner.h
PiperOrigin-RevId: 369323385
(cherry picked from commit e4912a311f32f7c5ae2c5a61f549f03a4b0aab16)
=> Add Xcode toolchain support for an optional binary that can rewrite the generated header of a Swift module after compilation.

swift/internal/swift_clang_module_aspect.bzl
`swift_clang_module_aspect` assumes that CcInfo contains all of the necessary compiler flags to be able to find the headers that are used when compiling an explicit module. This is true for all flags except the header search path in the Objc provider's `strict_include` field. This means that the `strict_include` field needs to be explicitly translated to an equivalent CcInfo when compiling the module.
PiperOrigin-RevId: 370991285
(cherry picked from commit 1aca023d007646d44da3512bac05ebbad64e8135)
=> Make the strict include paths from `objc_proto_library` targets available so headers can be found when `swift_clang_module_aspect` compiles a module.

swift/internal/compiling.bzl, swift/internal/feature_names.bzl
PiperOrigin-RevId: 371693623
(cherry picked from commit 06322f12a2dcbcafb33e598416486c25bef621c8)
=> Rename `swift.strict_modules` to `swift.layering_check` to match the C++ feature name.

swift/BUILD, swift/internal/BUILD, swift/internal/attrs.bzl, swift/internal/build_settings.bzl, swift/internal/swift_library.bzl
The flag accepts a comma separated list of "target=copts" pairs, where "target" is a fully qualified target label and "copts" is a colon separated list of Swift copts.
PiperOrigin-RevId: 371728552
(cherry picked from commit de9c4e1a00f779af382b2a9b96a2685b54a3f93a)
=> Add a user settable build setting to specify additional swiftcopts for a swift_libray target.

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, test/BUILD, test/module_cache_settings_tests.bzl
This adds a new feature, that can be enabled by passing `--features=swift.use_global_module_cache` and `--features=swift.global_module_cache_uses_tmpdir` to the build command.
This feature, when enabled, will makes the Swift compilation actions use the shared Clang module cache path written to `/private/tmp/__build_bazel_rules_swift/swift_module_cache/REPOSITORY_NAME`. This makes the embedded Clang module breadcrumbs deterministic between Bazel instances, because they are always embedded as absolute paths. Note that the use of this cache is non-hermetic--the cached modules are not wiped between builds, and won't be cleaned when invoking bazel clean; the user is responsible for manually cleaning them.
Additionally, this can be used as a workaround for a bug in the Swift compiler that …
=> Add `swift.global_module_cache_uses_tmpdir` feature

swift/internal/compiling.bzl, swift/internal/swift_protoc_gen_aspect.bzl
This flag hasn't been used by Bazel for a very very very very very long time.
PiperOrigin-RevId: 373845026
(cherry picked from commit 05f18b8b495a6b3385b708d2d906b224a8913be6)
=> Stop passing `uses_swift` to `new_objc_provider`.

.bazelci/presubmit.yml, doc/BUILD.bazel, doc/aspects.md, swift/internal/BUILD
Refactor the doc/BUILD file in prep for adding two more generated pages.
Fixed bzl_library mistakes that caused stardoc to fail.
=> Enable CI testing for docgen

WORKSPACE, doc/BUILD.bazel, doc/api.md, doc/stardoc.pr103.patch
Compare existing doc
https://github.com/bazelbuild/rules_swift/blob/master/doc/api.md
with newly generated
https://github.com/bazelbuild/rules_swift/blob/4dd6fae8ead1152531f63cd34889acd2037c8408/doc/api.md
=> Generate api.md from sources

doc/BUILD.bazel, doc/setup.md, doc/stardoc.pr103.patch, swift/BUILD
This is the last doc that should be generated from sources, but wasn't, from what I can tell.
Fixes #468
=> Generate setup.md from sources

third_party/bazel_protos/README.md, third_party/bazel_protos/worker_protocol.proto, tools/worker/work_processor.cc
And now set the request ID on the response proto
=> Update the worker protocol proto

swift/internal/compiling.bzl, swift/internal/swift_clang_module_aspect.bzl, swift/internal/utils.bzl
PiperOrigin-RevId: 372240650
(cherry picked from commit cc15b6eb5fb7bcd129eaa4960ff60e5c44d9a7eb)
=> Include the headers from direct dependencies of a Swift target when compiling the explicit module for its generated header.

swift/internal/compiling.bzl
The Swift compiler determines which module to import a symbol from based on the module that defines that symbol. Due to modular re-exports (which are particularly common among system frameworks), this may not be the same framework that the user imported from Swift and added to their dependencies.
(For example, most users will import and depend on `Foundation` to use `NSObject`, but Swift will import it from the module it is actually defined in, `ObjectiveC`.)
PiperOrigin-RevId: 371919747
(cherry picked from commit d8a381c0174d3a445389c3decc3727d41b80b255)
=> Disable layering checks when compiling the explicit module for a Swift generated header.

swift/internal/compiling.bzl
```
<unknown>:0: error: invalid argument '-fsystem-module' only allowed with '-emit-module'
```
This happens because ClangImporter changes the invocation's action to `GenerateModule` *after* the invocation is created by parsing the `-Xcc` flags from the Swift command line, and Clang's argument parser emits a diagnostic if `-fsystem-module` is used with any other action.
PiperOrigin-RevId: 375942286
(cherry picked from commit c497e6ed8ca6ea1cf006f950e577e433065f2d6b)
=> Get rid of spurious diagnostics when compiling system modules with Xcode 12.5:

tools/common/file_system.cc, tools/common/file_system.h, tools/worker/output_file_map.cc, tools/worker/output_file_map.h, tools/worker/work_processor.cc
By doing this, for some parts of the build graph, the swiftmodule doesn't have to be recreated. Here is an example with Swift 5.5:
Before:
```console
remark: Incremental compilation: Enabling incremental cross-module building
remark: Incremental compilation: May skip current input:  {compile: A.swift.o <= A.swift}
remark: Incremental compilation: Skipping input:  {compile: A.swift.o <= A.swift}
remark: Incremental compilation: Not skipping job: Merging module A; Missing output 'bazel-out/darwin-fastbuild/bin/A.swiftmodule'
remark: Starting Merging module A
remark: Finished Merging module A
remark: Skipped Compiling A.swift
```
After:
```console
remark: Incremental compilation: Enabling incremental cross-module building
remark: Incremental compilation: May skip current input:  {compile: …
```
=> Reuse swiftmodule for incremental builds

tools/worker/work_processor.cc
Missed with 84286ada38264db60fdfc907bb72863471de6fd7.
Also reverts the hard error on not creating directories. It could try to create the same directory multiple times, and the previous behavior silently errored on those. This can get fixed up in a later change to only try to create each directory once, and to only error if the directory doesn't already exist.
=> Add returns

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/repositories.bzl, tools/worker/BUILD, tools/worker/swift_runner.cc, tools/worker/swift_runner.h
swift and clang write index data based on the status of what resides in
`index-store-path`. When using a transient per-swift-library index, it
writes O( M imports * N libs) indexer data and slows down compilation
significantly: to the tune of 300% slow down and 6GB+ index data in my
testing. Bazel likes to use per `swift_library` data in order to remote
cache them, which needs extra consideration to work with the design of
swift and clang and preserve the performance
This PR does 2 things to make index while building use the original
model of the index-store so we don't have to patch clang and swift for
this yet. When the flag `-Xwrapped-swift-enable-global-index-store` is
set:
1. it writes to a global index cache, `bazel-out/global_index_store`
2. it copies indexstore data (records and …
=> Implement global index store cache

swift/internal/xcode_swift_toolchain.bzl
This change adds the search path for StoreKitTest/XCTest now available on watchOS in Xcode 12.5, and retires a number of workarounds and/or conditional code paths that are for older versions of Xcode that we don't care about anymore. For example, statically linking the Swift runtime is no longer supported on Darwin with modern versions of Xcode.
PiperOrigin-RevId: 377920556
(cherry picked from commit bf5fccc55f83e0583c193c97cbbc7913ac005715)
=> Modernize `xcode_swift_toolchain` features and linkopts.

tools/common/file_system.cc
If there are 2 concurrent processes creating the same directories, the existing code fails. I suspect this is "transient" errors we saw in #  567's final CI run, but this is unrelated to the PR. 
I suspect invalidating the worker or other updates triggered big rebuilds. Myself and a co-worker hit this today when we bumped rules_swift. 
This manifests in many ways when using anything that needs a directory e.g.
```
<unknown>:0: error: error opening 'bazel-out/macos-x86_64-applebin_macos-darwin_x86_64-dbg-ST-15eaacdcbb7d/bin/_swift_incremental/tests/macos/xcconfig/array_key_xcconfig_swift_objs/empty.swift.swiftdeps' for output: No such file or directory
```
Note: I don't have a perfect repro - at a 10% rate: invoking Bazel to build 2 swift libraries in the same BUILD file seemed to do the …
=> Fix race condition in MakeDirs

doc/api.md, swift/internal/linking.bzl, swift/internal/swift_common.bzl
This should have been deleted in the previous change that refactored the linker flags. It no longer works because it tries to access a provide field that no longer exists, but nothing broke because nothing calls it anymore. Yay weak typing.
PiperOrigin-RevId: 378673728
(cherry picked from commit 503c9cc8c116599c217ba0c6743998fbfa865f4b)
=> Delete the `swift_common.swift_runtime_linkopts` function.

BUILD, third_party/BUILD, third_party/bazel_protos/BUILD
So they are copied over in integration tests in rules_apple
Though I'm not sure how we've gotten away without this until now?
=> Add files in third_party to :for_bazel_tests

swift/repositories.bzl
Not sure why this works sometimes and not others but we need to
terminate this where the BUILD file lives
=> Fix index_import label

tools/common/bazel_substitutions.cc, tools/common/file_system.cc, tools/worker/output_file_map.cc, tools/worker/swift_runner.h, tools/worker/work_processor.cc
This way, incidental edits in these files in subsequent PRs won't cause diffs
=> Run clang-format over all cpp files in the repo

swift/internal/actions.bzl, swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl, test/BUILD, test/ast_file_tests.bzl, test/fixtures/multiple_files/BUILD, test/fixtures/multiple_files/Empty.swift, test/fixtures/multiple_files/Empty2.swift, test/rules/provider_test.bzl, tools/worker/swift_runner.cc, tools/worker/swift_runner.h, tools/worker/work_processor.cc
Some tooling (namely https://github.com/square/Cleanse/tree/master/cleansec) operates over dumped swift AST files.
In order to dump AST files, (almost) complete `swiftc` invocations are required, in addition to the `-dump-ast` flag.
Because almost the same set of arguments as module compilation are used for dumping the AST, it is nearly impossible for a bazel user to reconstruct them by hand (or via a standalone rule).
This new output group (and action) serves to dump AST files for each swift source file in a `swift_library` swift module.
=> Add the ability to dump ast to a file

tools/worker/swift_runner.cc
We need an early return to completely avoid consuming the WMO-enabling arg
=> Truly silence warnings about using -wmo with -dump-ast

swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_common.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_import.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl, swift/internal/utils.bzl, test/private_deps_tests.bzl, test/split_derived_files_tests.bzl
`swift_common.compile` now returns a tuple with two elements, very similar to `cc_common.compile`:
1. A "module context" (the same kind of value returned by `swift_common.create_module` that has `clang` and `swift` fields)
2. A `CcCompilationOutputs` object containing the object files.
The returned module context is slightly different than those propagated by the rules previously, in that its `clang` field will be present even if the Swift module doesn't propagate a Clang module. This is so that callers can easily retrieve its `compilation_context` and return it in a `CcInfo` provider. Therefore, callers who want to know whether a module context exposes a Clang module should check the `clang.module_map` field rather than just the `clang` field; it will be `None` if there is no Clang …
=> Refactor the Swift compilation APIs to use a style similar to the C++ APIs.

.bazelci/presubmit.yml
I'm trying to remove parts from our Docker containers that are only used by one or few projects on CI.
Instead, we can download & extract them during the shell_commands step of the projects. This also allows the projects themselves to control the exact versioning of their dependencies and makes it easier to test upgrades.
=> Fetch the Swift toolchain as part of the CI job

.bazelci/presubmit.yml, doc/api.md, swift/internal/swift_binary_test.bzl, test/split_derived_files_tests.bzl
This is required for the `autolink_extract` to extract linker flags from
the import statements from those source files.
=> Collect linking context from `swift_{binary,test}` if they have `srcs`.

doc/api.md, swift/internal/providers.bzl
PiperOrigin-RevId: 391051966
(cherry picked from commit 19dcd00853c07404743aa524d727579435d8e1c6)
=> Allow both the `clang` and `swift` arguments of `swift_common.create_module` to be `None`.

doc/api.md, swift/internal/providers.bzl, swift/internal/swift_clang_module_aspect.bzl
Also clarify the purpose of the `compilation_context` argument in `swift_common.create_clang_module` and how it should and should not be used.
PiperOrigin-RevId: 391067469
(cherry picked from commit a81c59152799e96a9318ba2c6564a9aeb4d6b909)
Conflicts:
swift/internal/swift_clang_module_aspect.bzl
=> Make sure to pass strict dependency include paths from the `apple_common.Objc` provider when compiling the explicit module for a target.

swift/internal/derived_files.bzl, swift/internal/swift_binary_test.bzl, tools/xctest_runner/xctest_runner.sh.template
If your binary gets an rpath like `@loader_path/../foo`, when we moved
this into the xctest bundle directory that path would become invalid.
By setting the binary path directly to the link, bazel processes these
for us.
Note in the current release version of bazel this path gets duplicated
unnecessarily to
`Foo.xctest/Contents/MacOS/Foo.xctest/Contents/MacOS/Foo`, but this was
fixed in
https://github.com/bazelbuild/bazel/commit/b4cc44c978bc0e25b6652b66018b6aad12bff820
and doesn't seem to cause problems besides being unnecessary.
=> Fix breaking swift_test rpaths on macOS

swift/internal/swift_autoconfiguration.bzl
Sometimes on Linux your clang binary name has the version in it, this
enforces the binary at least looks like clang but less strictly.
https://github.com/bazelbuild/rules_swift/issues/43#issuecomment-914527561
=> Loosen CC requirement

swift/internal/compiling.bzl, test/BUILD, test/output_file_map_tests.bzl, test/rules/output_file_map_test.bzl
Adds the file path of `llvm-bc` files to the output file maps created by rules_swift, when `-embed-bitcode` is requested.
Without this file path, on Xcode13, we get compile errors due to object files not created in the correct paths - the paths specified as `object` in the output file maps are ignored.
Fixes https://github.com/bazelbuild/rules_swift/issues/682.
=> Fixes for using -embed-bitcode on Xcode13

doc/api.md, swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/providers.bzl, swift/internal/swift_library.bzl
Declares `.swiftsourceinfo` as an output file of a compile action and threads the file through to be an output of the swift_library rule.
PiperOrigin-RevId: 398579438
(cherry picked from commit 4e45e790f642d29309e3f6f5fffc706a2593655c)
> Conflicts:
>	swift/internal/compiling.bzl
Fixes #496
Closes #523
=> Produce `.swiftsourceinfo` file as output of swift_library rule.

swift/internal/swift_autoconfiguration.bzl
This was added in #683. `CC` may not be set in the env, in which case it will be `None`, which will fail with an error like `TypeError: argument of type 'NoneType' is not iterable`
It was going to fail anyway, but now it will fail with the right error.
=> swift_autoconfiguration: handle case where `CC` isn't set

swift/internal/features.bzl
PiperOrigin-RevId: 393352196
(cherry picked from commit 5b669040e15627c3ed35ceb2a101991699a50572)
=> Fix a bug that permitted false positive matches in Swift feature allowlists.

swift/internal/compiling.bzl, swift/internal/feature_names.bzl
PiperOrigin-RevId: 398758812
(cherry picked from commit 69bc3ede9176a02207b916a3c87801ce30639fb2)
=> Add a feature to switch back to the legacy Swift driver in Swift 5.5 and higher.

.bazelci/presubmit.yml
We are dropping 4.x support in order to land 5.0 required changes. This changes the CI to test against the 5.0 rc instead of 4.2.1.
=> Test 5.0 rc for now

swift/internal/features.bzl, swift/internal/xcode_swift_toolchain.bzl
This reverts commit 1b4e4c06ad71e4fc6383d72d64d517ff6674995b.
=> Revert "Add support for older bazel versions for now"

swift/internal/autolinking.bzl, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl
From a tip in a BazelCon talk today.
=> Use `progress_message` placeholders for more performant rules

swift/internal/compiling.bzl
This reverts commit ff330612baa088ef93ddf3b40b20a084149578c4 and cherry picks b71c3fc878ca7aab42d6e09f526c4721f1f5639f
=> Revert "Pass framework search paths directly to clang for pcms"

swift/internal/compiling.bzl
We don't need to pass the whole `CcInfo` as a prerequisite, and this better unifies the interfaces of the `SwiftCompile` and `SwiftPrecompileCModule` actions.
PiperOrigin-RevId: 403414208
(cherry picked from commit 790b8d40c83ae5415b54be02b5750efc73831c33)
=> Use `CcCompilationContext` internally when configuring compilation actions.

swift/internal/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 406856595
(cherry picked from commit 764b3db76c2ce5016ac1ac3723faa5d8677c396a)
=> Migrate from `ctx.fragments.apple.bitcode_mode` to `ctx.fragments.cpp.apple_bitcode_mode`.

swift/internal/compiling.bzl, swift/internal/features.bzl
This lets Bazel create the necessary module map for C++/Obj-C layering checks (which is distinct from the module map generated for Swift, by design), ensuring that generated headers are recognized as belonging to the module they came from.
PiperOrigin-RevId: 409147264
(cherry picked from commit 61199fa039b69b9146b04ad6bece66bb42aa5ab4)
=> Use `cc_common.compile` to create the compilation context for a Swift module with a generated header.

swift/internal/compiling.bzl
Various changes since this was added (nearly 5 years ago) appear to have made this obsolete, and it reduces dependence on `ObjcProvider`.
PiperOrigin-RevId: 411838591
(cherry picked from commit c8b58b504842b6c16c2791e78db1137204f74a6d)
=> Remove the use of `-disable-autolink-framework`.

test/BUILD, test/ast_file_tests.bzl, test/coverage_settings_tests.bzl, test/debug_settings_tests.bzl, test/generated_header_tests.bzl, test/module_cache_settings_tests.bzl, test/output_file_map_tests.bzl, test/pch_output_dir_tests.bzl, test/private_deps_tests.bzl, test/split_derived_files_tests.bzl, test/swift_through_non_swift_tests.bzl
Silences the buildifier warning, but also provides an name so tools like
buildozer that work on the AST can better handle the BUILD files where they are
called.
RELNOTES: None
PiperOrigin-RevId: 420123866
(cherry picked from commit 14b8cfcc4956e2c38f66f855783cbeccec2bd6f3)
=> Add name arguments to the test suites.

test/rules/provider_test.bzl
The providers are used as markers themselves, and it isn't that the fields are
undeclared, they have no fields.
RELNOTES: None
PiperOrigin-RevId: 420275818
(cherry picked from commit a4a91acf440f89deadace4aee5a6cebf59a43fa3)
=> Add empty `fields` to providers that don't have fields.

tools/common/process.cc
In the case that swiftc crashed, the worker would return that it exited
0. This was because calling WEXITSTATUS when WIFEXITED is not true is
invalid and happened to return 0 in that case. We now handle the case
where swiftc exits from a signal, and return the signal it exited with
instead. There might be some other cases here that we have to handle in
the future, so for now those are failures so we don't return an invalid
value.
Also see https://github.com/bazelbuild/bazel/issues/14543
=> Fix exit code for swiftc crashes

swift/internal/compiling.bzl
This is no longer needed.  It was leftover from the compile info
migration because (primarily) IDE still relied on it to get direct
header information.  We just migrated those use cases to CcInfo as
well.
PiperOrigin-RevId: 421187175
(cherry picked from commit 5804b272c07f0749d9356ae52baf4c4d2e21acd5)
=> Stop adding headers to ObjcProvider

swift/internal/compiling.bzl, swift/internal/feature_names.bzl
Taking this just to reduce the chance of merge conflicts with upstream
=> Add a feature that allows the ASAN version compatibility check to be disabled, for folks who _know what they're doing._

swift/internal/swift_protoc_gen_aspect.bzl
Avoids having to go look up what the function is doing since it is just fetching
a field.
RELNOTES: None
PiperOrigin-RevId: 422556605
(cherry picked from commit c410bdb263b95261a9f0015e4d3594ba10a804fa)
=> Move to lambdas since the helper is so simple.

tools/common/file_system.cc
This applies https://github.com/bazelbuild/rules_swift/commit/aa8b3c66609964768840b40e65f30d69012d4a5f which was a variation of https://github.com/bazelbuild/rules_swift/commit/ebd617515ec0a994caf3225021a61c35cf624abe
=> Take upstream MakeDirs fix

swift/BUILD, swift/internal/swift_grpc_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl, third_party/com_github_apple_swift_protobuf/BUILD.overlay, third_party/com_github_grpc_grpc_swift/BUILD.overlay, tools/protoc_wrapper/BUILD, tools/worker/BUILD
This adds a new boolean flag
`--@build_bazel_rules_swift//swift:universal_tools` that when used will
force all the tools used in this repository to be compiled into
universal binaries. This allows execution running on different macOS
platforms (`arm64` and `x86_64`) to be compatible with each other and
can run natively on both.
=> Add a flag to allow tools to be compiled as universal binaries

swift/internal/xcode_swift_toolchain.bzl
`apple_fragment.single_arch_cpu` was returning the default macos cpu for
the host platform for tools while it should return the cpu of the
execution platform.
=> Retrieve single arch cpu from `cc_toolchain` instead of from `apple_fragment`

swift/internal/xcode_swift_toolchain.bzl
Reverts bazelbuild/rules_swift#694
https://buildkite.com/bazel/rules-apple-darwin/builds/5009#d6c8bbc5-4ae2-4958-98bd-189d5ae9f7ff
=> Revert "Retrieve single arch cpu from `cc_toolchain` instead of from `apple_fragment`"

swift/internal/xcode_swift_toolchain.bzl
This should be the wrapper target so that it can be configured to be
built as a universal binary.
Missing change from 2f9d3ac2afdea672f280eb0b88e0e0d76e39febb.
=> Fix worker target

swift/internal/xcode_swift_toolchain.bzl
`ctx.fragments.apple.single_arch_cpu` is returning the default macos
cpu for the host platform for tools while it should return the cpu of
the execution platform.
~The original patch relied on `ctx.fragments.apple.single_arch_platform`
which can also be wrong in some cases. Now we only look at the platform
prefix in the cpu string instead.~
~There is a caveat with this workaround: When building a `swift_library`
directly without a `--cpu` flag, the `cpu` value would be the cpu value
of the exec platform, regardless of the `--apple_platform_type` value.~
=> Reland: Retrieve single arch cpu from `cc_toolchain` instead of from `ctx.fragments.apple`

swift/repositories.bzl
Otherwise this can't be referenced when building from other workspaces.
=> Make patch label absolute

swift/internal/linking.bzl
Previously this caused this issue:
```
ERROR: path/to/BUILD:14:13: in swift_binary rule //tools/deadcode:deadcode:
Traceback (most recent call last):
File "/private/var/tmp/_bazel_ksmiley/751b7cfc481e6eb168e92ffcfb919baa/external/build_bazel_rules_swift/swift/internal/swift_binary_test.bzl", line 305, column 61, in _swift_binary_impl
_, linking_outputs, providers = _swift_linking_rule_impl(
File "/private/var/tmp/_bazel_ksmiley/751b7cfc481e6eb168e92ffcfb919baa/external/build_bazel_rules_swift/swift/internal/swift_binary_test.bzl", line 245, column 50, in _swift_linking_rule_impl
linking_outputs = register_link_binary_action(
File "/private/var/tmp/_bazel_ksmiley/751b7cfc481e6eb168e92ffcfb919baa/external/build_bazel_rules_swift/swift/internal/linking.bzl", line 251, column 54, in …
```
=> Fix swift_binary depending on apple_static_framework_import

swift/internal/compiling.bzl
PiperOrigin-RevId: 423448286
(cherry picked from commit 34e7ea5b113ac8a1af5f9397e57a24196d21ce77)
=> Ensure debug paths embedded in DWARF segments of PCM files built for Swift are workspace-relative.

swift/repositories.bzl
This isn't a long term solve for the github issues, but avoids them
until they're fixed.
=> Replace zip archives for now

swift/internal/xcode_swift_toolchain.bzl
Since
https://github.com/apple/swift/commit/e24eef4b35290135634c11a9a83e652de1e4919d
Swift now emits a warning about the old driver being deprecated. If you
enable the old driver flag we can assume you are doing that
intentionally for now and know that isn't a forever solution.
=> Add SWIFT_AVOID_WARNING_USING_OLD_DRIVER to environment

examples/apple/objc_interop/BUILD, examples/xplatform/c_from_swift/BUILD, swift/repositories.bzl, test/fixtures/private_deps/BUILD, test/fixtures/swift_through_non_swift/BUILD, third_party/com_github_grpc_grpc_swift/BUILD.overlay, third_party/com_github_nlohmann_json/BUILD.overlay, tools/common/BUILD
This repo has been abandoned in favor of the `@_builtins` repo
(Starlark rules implemented in Bazel's core).
=> Remove `rules_cc` as a dependency

swift/internal/compiling.bzl, swift/internal/derived_files.bzl
Previously we required this file to be produced by adding it to the
outputs of compile actions. Starting with Swift 5.6 in incremental mode
the driver no longer produces these files, and instead separates
compilation from a single module creation step, instead of producing
partial modules and merging them. This leads to this file never being
created, and a build failure. This file is never consumed elsewhere, so
we don't need to ensure it's created.
https://github.com/apple/swift-driver/commit/e0c3e5c740e68202e0a7777d3f6af795d9150296
Fixes https://github.com/bazelbuild/rules_swift/issues/775
=> Drop partial swiftmodule from other_outputs

swift/internal/compiling.bzl, swift/internal/derived_files.bzl
Reverts bazelbuild/rules_swift#781
It turns out my tests for this weren't valid because of the inherent non-deterministic behavior when using incremental compilation. In the case you actually hit the incremental case of a build you could get a new error like:
```
ERROR: /Users/codyv/Developer/incremental-alley/Modules/Fingerprint/A/BUILD:3:14: output 'Modules/Fingerprint/A/FingerprintA.swiftmodule' was not created
ERROR: /Users/codyv/Developer/incremental-alley/Modules/Fingerprint/A/BUILD:3:14: output 'Modules/Fingerprint/A/FingerprintA.swiftdoc' was not created
ERROR: /Users/codyv/Developer/incremental-alley/Modules/Fingerprint/A/BUILD:3:14: output 'Modules/Fingerprint/A/FingerprintA.swiftsourceinfo' was not created
ERROR: /Users/codyv/Developer/incremental-alley/Modules/Fingerprint/A/BUI …
```
=> Revert "Drop partial swiftmodule from other_outputs"

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/swift_autoconfiguration.bzl, swift/internal/xcode_swift_toolchain.bzl
This fixes https://github.com/bazelbuild/rules_swift/issues/775 by
disabling the optimization intended by https://github.com/apple/swift-driver/commit/e0c3e5c740e68202e0a7777d3f6af795d9150296
Ideally we wouldn't disable it, but that caused other issues
https://github.com/bazelbuild/rules_swift/pull/784 and this is no worse
than what Swift 5.5 was doing until we find a better fix.
=> Pass -no-emit-module-separately by default

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/swift_autoconfiguration.bzl, swift/internal/xcode_swift_toolchain.bzl
Reverts bazelbuild/rules_swift#785
This is the right fix instead https://github.com/bazelbuild/rules_swift/pull/786
=> Revert "Pass -no-emit-module-separately by default"

swift/internal/linking.bzl
Previously we passed every dependent framework binary on the command
line to the link invocation. This resulted in duplicate symbols in the
case that multiple dependencies depended on the same
apple_static_framework_import. This now treats static frameworks just
like dynamic frameworks and uses `-F` + `-framework` to discover these.
Allowing the linker to dedup them.
=> Fix apple_static_framework_import duplication

swift/internal/linking.bzl, test/BUILD, test/fixtures/linking/BUILD, test/fixtures/linking/fake_framework.bzl, test/fixtures/linking/main.swift, test/linking_tests.bzl, test/rules/action_command_line_test.bzl
Wrapping these in a depset caused these flags to be de-duplicated, which
meant if a single dependency added `-framework foo -framework bar` it
would turn into the invalid `-framework foo bar`. This mode is also
discouraged by the documentation:
https://docs.bazel.build/versions/main/skylark/lib/cc_common.html#create_linker_input
We now use a list instead.
=> Fix dependency linker flags being de-duped

swift/repositories.bzl
Reverts bazelbuild/rules_swift#791
The protoc binary in https://github.com/protocolbuffers/protobuf/releases/download/v3.20.0/protoc-3.20.0-osx-aarch_64.zip was an x86_64 binary.
=> Revert "Update rules_proto"

swift/BUILD, swift/internal/BUILD
Generating stardoc that depends upon `rules_swift` fails without these declarations.
=> Add missing `bzl_library` declarations.

.bazelci/presubmit.yml, swift/repositories.bzl
I had to disable grpc tests on linux here because the version of grpc-swift we're on is very old and no longer compiles on Linux. Updating it is quite difficult since it has changed to a large dependency tree on nio
=> Bump Linux and Swift version

tools/common/process.cc, tools/common/process.h
This removes the definition of `ExecProcess` which is unused currently.
=> common: remove dead code (NFCI)

tools/common/BUILD
Avoid unnecessary vertical whitespace in `project` call.  This has a
single parameter and can be compressed to a single line instead of 5.
=> common: trivial cleanup of `BUILD`

swift/internal/actions.bzl, tools/worker/BUILD, tools/worker/compile_with_worker.cc, tools/worker/work_processor.cc, tools/worker/work_processor.h, tools/worker/worker_protocol.cc, tools/worker/worker_protocol.h
This avoids having the proto compiler—a large dependency—be in the critical path of every Swift compilation.
Upstream version of https://github.com/bazelbuild/rules_swift/pull/657
Fixes https://github.com/bazelbuild/rules_swift/issues/516
PiperOrigin-RevId: 441799750
(cherry picked from commit af37ae712fdea608a9678c289785ce458fdeb5fc)
=> Migrate the Swift worker to use the JSON protocol instead of binary protos.

tools/common/BUILD, tools/common/temp_file.h, tools/worker/BUILD
Use C++17 more heavily here to avoid the use of `fts.h` making the code
easier to port.  Reduce the string manipulation by using
`std::filesystem::path` and use that to additionally locate the
temporary file location.  Emulate the POSIX semantics for `mkdtemp` and
`mkstemp` as much as possible to provide equivalent behaviour on
Windows.
=> common: port `temp_file` to C++17 and Windows

tools/worker/compile_with_worker.cc, tools/worker/worker_protocol.h
Remove an unnecessary inclusion of the Unix standard header
(`unistd.h`).  Add a missing C++ include for `std::optional`.
=> worker: alter includes for Windows friendliness

tools/BUILD, tools/common/BUILD, tools/worker/BUILD
This adds a working form of the constraints to get the correct flags by
default when building with cl (MSVC or clang) for Windows.
=> build: make the build constraints for MSVC work

.bazelci/presubmit.yml, .bazelrc, tools/common/process.cc
Add a build-only partial CI coverage for Windows.  This should ensure
that we do not regress on the C++ portions of the Windows support.
Having this coverage should enable us to begin focusing on the Starlark
rules support for Windows.
Bump the C++ dependency when building for Windows to C++20 to use
designated initializers.
=> ci: add an initial configuration for Windows builds

tools/common/temp_file.h
`path.size()` would give the size of the string without the trailing
null terminator, which would then assert (on debug) or abort on opt.
This would prevent the worker from ever executing the child.
=> common: fix off-by-one error in `_mktemp_s` call

swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_toolchain.bzl, swift/internal/toolchain_config.bzl
When building on Windows, we should suffix the executable tool with the
executable suffix.  This ensures that the worker can actually launch the
process.  If the user specified the swift_executable, ensure that we do
not double suffix the tool.
=> swift: use executable suffixes for tool invocation

tools/common/process.cc
The `{pattern}` form did not fill out the entire array with the desired
pattern.  Explicitly initialize the array appropriately for the debug
builds.
=> common: fix initialization of variable on Windows

test/fixtures/linking/BUILD
This test adds invalid frameworks just to build a command line for
testing, this marks them as manual so they aren't built when testing
everything.
=> Fix test ... for linking

doc/api.md, swift/internal/compiling.bzl, swift/internal/providers.bzl, swift/internal/swift_common.bzl
This adds a new struct to `SwiftInfo` modules that exposes the information used during compilation of a Swift target. The main use case is aspects, in particular ones for IDE integration. The attributes exposed mirror some of those found in `CcInfo.compliation_context` and `ObjcProvider`.
The initial attributes are ones that I personally need right now, but we can add more later as they are identified.
=> Add `compilation_context` to `SwiftInfo` modules

doc/api.md, swift/internal/compiling.bzl, swift/internal/providers.bzl, swift/internal/swift_common.bzl
This reverts commit 42036b5212fedcd0e1377100d34d7a83e79e7ed6.
```
Traceback (most recent call last):
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/swift_library.bzl", line 173, column 93, in _swift_library_impl
module_context, cc_compilation_outputs, other_compilation_outputs = swift_common.compile(
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/compiling.bzl", line 1883, column 29, in compile
run_toolchain_action(
File "/private/var/tmp/_bazel_ksmiley/c8513c989333be3c89713e16206869b2/external/build_bazel_rules_swift/swift/internal/actions.bzl", line 249, column 42, in run_toolchain_action
action_inputs = _apply_action_configs(
File …
```
=> Revert "Add `compilation_context` to `SwiftInfo` (#815)"

swift/internal/swift_grpc_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl
When using the rules on Windows, we should use `;` rather than `:` for
the path separator.  This uses the bazel configuration to drive the
value making the selection agnostic to the platform.
=> swift: correct path separator

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/swift_autoconfiguration.bzl
Windows poorly supports DWARF (or rather DWARF poorly supports Windows)
and the swift driver poorly supports CodeView.  However, both are useful
in different scenarios.  Add a feature to use codeview, and enable it by
default.  The default is important as DWARF cannot supported by link
which is picked up as the default linker.
=> swift: introduce a feature to control debug info on Windows

.gitattributes, tools/mkdir_and_run/BUILD, tools/mkdir_and_run/mkdir_and_run.cmd
Prefer a cmd script over bash on Windows.  This allows this command to
be used across platforms.
=> tools: port mkdir_and_run to work on Windows

tools/dump_toolchains/dump_toolchains.sh
Otherwise the glob returns 1 entry with the literal *
=> Fix empty glob in toolchains

tools/common/BUILD, tools/worker/BUILD
The outliner does not correctly handle landingpads and will attempt to
outline the EH funclet which generates incorrect IR (and is also
pointless).  Workaround this for the time being.
=> build: workaround LLVM bug on Windows

tools/worker/output_file_map.cc, tools/worker/output_file_map.h, tools/worker/work_processor.cc
Fixes #819.
When a SwiftCompile action is cancelled, it can leave the incremental storage area in a corrupt state, in which all later compiles return exit code 0, but don't actually produce an output (#819).
34ce7835bda5e787b633f2ce0cc9687e90f7f952 identified a good way to tell that the storage area was in a corrupt state, but it didn't fully fix the problem. We also need to delete the existing `swiftdeps` files, which this change does.
=> Cleanup swiftdeps on corrupt incremental module

swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/feature_names.bzl
That emits the symbol graph for the Swift target to `bazel-bin`.
Symbol graphs can then be fed to tools such as [DocC](https://github.com/apple/swift-docc) or [jazzy](https://github.com/realm/jazzy) to generate documentation for a target.
For example, for [Envoy Mobile](https://github.com/envoyproxy/envoy-mobile):
```
$ ./bazelw build //library/swift:ios_lib --config=ios
$ "$(xcrun --find docc)" convert \
--index \
--fallback-display-name Envoy \
--fallback-bundle-identifier io.envoyproxy.EnvoyMobile \
--fallback-bundle-version 0.4.6 \
--output-dir Envoy.doccarchive \
--transform-for-static-hosting \
--additional-symbol-graph-dir bazel-bin/library/swift/ios_lib.symbolgraph
```
=> Add `swift.emit_symbol_graph` feature

examples/xplatform/grpc/BUILD, examples/xplatform/grpc/client_main.swift, examples/xplatform/grpc/client_unit_test.swift, examples/xplatform/grpc/server_main.swift, swift/internal/swift_grpc_library.bzl, swift/repositories.bzl, third_party/com_github_apple_swift_log/BUILD.overlay, third_party/com_github_apple_swift_nio/BUILD.overlay, third_party/com_github_apple_swift_nio_extras/BUILD.overlay, third_party/com_github_apple_swift_nio_http2/BUILD.overlay, third_party/com_github_apple_swift_nio_transport_services/BUILD.overlay, third_party/com_github_grpc_grpc_swift/BUILD.overlay
This upgrades past the 0.X series into the 1.X series which changes the
import from `SwiftGRPC` to simply `GRPC` (it's cleaner).
Fixed: #827
=> Upgrade gRPC to 1.7.3

tools/worker/work_processor.cc
Previously we would copy back incremental outputs even if compilations
failed. This meant if swift ever produced a partial set of outputs, or
partial output, the next compilation might fail because of these
invalid inputs.
Another attempt at helping with https://github.com/bazelbuild/rules_swift/issues/819
=> Exit early in worker on failures

swift/internal/compiling.bzl
lldb is failing to properly parse the dwarf data in pre-compiled modules. Adding this flag fixes the issue with Xcode 13.3 and also works with Xcode 13.2.1.
PiperOrigin-RevId: 443118640
(cherry picked from commit 02234a9b9ebd80574d748febbb894263a6ab2767)
=> Adding a new `-gmodules` flag to swift compilations to for a new lldb regression in Xcode 13.3.

swift/internal/target_triples.bzl, swift/internal/xcode_swift_toolchain.bzl
When using `--host_cpu=darwin_x86_64` on an ARM (Apple Silicon) host, the value returned by the Apple configuration fragment is wrong, and we end up compiling Swift for `arm64`. Since the C++ toolchain already has the correct triple verbatim as we want it in the `target_gnu_system_name` field, just use that, and add some generally useful utilities for manipulating the triples and their components.
Note to open-source rules maintainers: This change requires/assumes that your C++ toolchain configuration returns a complete target triple that includes minimum OS version and target environment; for example, `x86_64-apple-ios13.0-simulator`.
PiperOrigin-RevId: 429897884
(cherry picked from commit 62b33ed5ff5d699cb1573309e0714e30f4d6e225)
=> Use the target triple from the C++ toolchain instead of deriving it from values in the Apple configuration fragment.

doc/aspects.md, doc/providers.md, swift/internal/providers.bzl, swift/internal/swift_usage_aspect.bzl
It's no longer used anywhere and may interfere with toolchainification. It was previously used to retrieve the toolchain from which linker flags should be retrieved, but those are now passed via an implicit dependency.
PiperOrigin-RevId: 439394121
(cherry picked from commit 2e7227d72e0f70b68a30fe57729a4fa7882fb4a1)
=> Remove the `toolchain` field from `SwiftUsageInfo`.

.bazelci/presubmit.yml
Similar to rules_apple, just makes it more clear how much is broken when
it's just docs that need to be updated.
=> Move doc tests to separate CI job

swift/internal/xcode_swift_toolchain.bzl
We would like to migrate all such usage to CppConfiguration so that we
can delete the info in ObjcConfiguration.
PiperOrigin-RevId: 457500060
(cherry picked from commit 912d40dade63be23c325ac79a1854868ded16601)
=> Migrate ObjcConfiguration usage to equivalent info in CppConfiguration

third_party/com_github_apple_swift_nio_transport_services/BUILD.overlay
Fixes the following compilation error:
```
external/com_github_apple_swift_nio_transport_services/Sources/NIOTransportServices/NIOTSConnectionChannel.swift:20:8: error: no such module 'NIOTLS'
```
=> Fix missing dependency

.bazelci/presubmit.yml, .bazelrc
Prevents issues with non-hermetic bugs like
https://github.com/bazelbuild/rules_swift/pull/865.
=> Enable sandboxing for swift builds

swift/internal/swift_binary_test.bzl
This is similar to what `cc_binary` does. It helps to signify that the binary uses Swift, and for the case when it compiles its own sources, it exposes the `compilation_context` which isn't available any other way.
Fixes an issue found here: https://github.com/buildbuddy-io/rules_xcodeproj/pull/880#issuecomment-1205715119
=> Return `SwiftInfo` from `swift_{binary,test}`

swift/internal/swift_autoconfiguration.bzl
The autoconfigured toolchain on linux uses `x86_64` currently. Changing to use the host arch makes it easier to start working on arm64 (for instance... in a docker container on an M1 mac).
It doesn't look like Swift on Windows supports `aarch64` currently; it has the same hard-coded value, but if that changes, it's the same easy fix.
=> Use host arch for linux autoconfiguration

swift/internal/compiling.bzl, test/split_derived_files_tests.bzl
This PR attempts to fix the following issue when `split_derived_files_generation` feature is used.
When using the `split_derived_files_generation` feature, we observed that the `emit-symbol-graph` and `-emit-symbol-graph-dir` options are not passed to the `Generating derived files...` action because of which the symbol.json files were not produced.
Though the flags were passed to the compilation action, it was a no-op because of the issue described here: https://github.com/apple/swift/issues/60412.
This PR does the following:
1. If the derived files feature is not enabled, then the symbol-graph related options are passed to the compilation action. (this is the default).
2. If the derived files feature is enabled, then the symbol-graph related options are passed to the derived files …
=> Fix symbol graph with derived files

examples/xplatform/xctest/BUILD, tools/xctest_runner/xctest_runner.sh.template
rules_apple handles bundling sanitizers with test bundles that it
creates, swift_test does not handle this as it creates a very minimal
xctest bundle (ideally it wouldn't have to create that bundle at all and
you could run tests directly). Because of this we don't have the
sanitizer libs easily extracted into the bundle. Sanitizers require us
to load them when launching the binary with DYLD_INSERT_LIBRARIES, to
know which to load we can inspect the binary for these. Clang inserts an
absolute rpath to the Xcode directory containing the libraries, as well
as the library loads for each we depend on.
=> Add basic sanitizer support for swift_test

swift/internal/compiling.bzl
The upstream branch did this
https://github.com/bazelbuild/rules_swift/commit/492c48e16fae85d439aa53242cb741a1c32db376
but more importantly there's otherwise no way to disable this flag when
there are bugs https://github.com/apple/swift/pull/60636
=> Require cacheable swiftmodules for -no-clang-module-breadcrumbs

doc/rules.md, swift/internal/BUILD, swift/internal/swift_binary_test.bzl
When this feature is enabled, the `@build_bazel_apple_support//lib:swizzle_absolute_xcttestsourcelocation` target is linked into `swift_test` targets.
=> Add `apple.swizzle_absolute_xcttestsourcelocation` feature

swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl, tools/worker/BUILD, tools/worker/compile_with_worker.cc, tools/worker/compile_with_worker.h, tools/worker/compile_without_worker.cc, tools/worker/compile_without_worker.h, tools/worker/swift_runner.cc, tools/worker/swift_runner.h, tools/worker/work_processor.cc, tools/worker/work_processor.h, tools/worker/worker_main.cc
Addresses https://github.com/bazelbuild/rules_swift/pull/567/files#r645580328
=> Use runfiles for `index-import` path

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/xcode_swift_toolchain.bzl
This PR adds support for passing the `-enable-bare-slash-regex` flag by default to all the swiftc actions for Swift 5.7 and above.
**Context**
The following fails to compile on Xcode 14 toolchain:
```
func regexTest() {
let testString = "04/07/2022"
let digits = /\d+/
print(testString.ranges(of: digits))
}
```
**Analysis**
Swift evolution proposal: [Regex Literals](https://github.com/apple/swift-evolution/blob/main/proposals/0354-regex-literals.md)
As per the proposal, it explicitly needs the `-enable-bare-slash-regex` flag to successfully compile the above code. Xcode 14 passes the same by default.
=> Supporting Swift 5.7 Bare Slash Regex Literal

tools/worker/worker_main.cc
This fixes an issue with rules_spm usage.
=> Don't error if worker runfiles aren't present

tools/common/bazel_substitutions.cc
This is a speculative fix for an issue we saw where swift.remap_xcode
seemed to not take effect. My only theory is that DEVELOPER_DIR was not
set, so the value was not replaced correctly in the invocation, leading
to absolute paths leaking into the binary. With this change this case
would now fail, which make make it easier to debug why bazel didn't set
this required environment variable. This also ignores these variables on
other platforms, where I don't think we'd ever want them to be consulted
even if they were manually set by someone.
=> Make DEVELOPER_DIR required on Apple platforms

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/xcode_swift_toolchain.bzl, test/BUILD, test/features_tests.bzl, tools/worker/swift_runner.cc
This is a new flag in Swift 5.7, that mirrors the flag with the same
name in clang, meaning that it implies both -debug-prefix-map, and
-coverage-prefix map. Currently it is also the only flag that applies to
indexing info if you want to produce hermetic indexes. Ideally going
forward users should prefer this flag if they want their builds to be
hermetic instead of picking the other flags as needed, since this will
potentially also apply to new absolute paths in the future.
https://github.com/apple/swift/pull/58946
=> Add support for -file-prefix-map $PWD=.

swift/internal/compiling.bzl, swift/internal/linking.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_import.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_protoc_gen_aspect.bzl
The `Objc` provider is only created by Swift to propagate linking information to the Apple rules until that logic migrates to `CcInfo`, so this is a better home for it until it can disappear for good.
PiperOrigin-RevId: 423827285
(cherry picked from commit 899eb1e5ca6f5c8b488dbbe4cb64653ccf77604f)
Conflicts:
swift/internal/compiling.bzl
swift/internal/linking.bzl
swift/internal/swift_grpc_library.bzl
swift/internal/swift_import.bzl
swift/internal/swift_library.bzl
swift/internal/swift_module_alias.bzl
swift/internal/swift_protoc_gen_aspect.bzl
=> Move the internal `new_objc_provider` helper function from `compiling.bzl` to `linking.bzl`.

swift/internal/linking.bzl
Required for https://github.com/bazelbuild/rules_apple/pull/1698 when
linking swift_binary targets
=> Add support for imported_library when linking

swift/internal/BUILD, swift/internal/compiling.bzl, swift/internal/explicit_module_map_file.bzl, swift/internal/feature_names.bzl, test/features_tests.bzl, test/fixtures/basic/BUILD, test/fixtures/basic/first.swift, test/fixtures/basic/second.swift, test/rules/action_command_line_test.bzl
As of Swift 5.6 and this PR https://github.com/apple/swift/pull/39887
the new json format used for entirely explicit module builds can be used
without entirely disabling implicit modules. This provides an
alternative to VFS overlays for discovering dependencies without `-I`
search paths. This is theoretically about the same but I expect this
file format to have better support in general than VFS overlays for
things like the new incremental compilation support, which currently
doesn't support VFS overlays, and this shouldn't have any downsides vs
VFS files.
This format does support some more keys than just the 2 we pass, as far
as I can tell they are unused today, so I'm opting not to pass them. We
may have to revisit this in the future.
This kind of cherry picks …
=> Add feature for partially explicit modules

MODULE.bazel, doc/setup.md, swift/extensions.bzl, swift/repositories.bzl
This is an initial implementation of bzlmod support in `rules_swift`. Still some things left to figure out, but I was able to compile a basic iOS app with WIP implementations of `rules_apple`, `rules_swift` and `apple_support`.
=> Add initial bzlmod support

tools/protoc_wrapper/BUILD
Since `--cpu` won't change unless a `platform_mappings` file is set up,
these won't build.
=> Skip building universal targets by default

MODULE.bazel
This was discovered while registering the latest rules_swift release into the BCR and running the validation pipelines there. It was tricky to debug, but it seems like either a recent change in rules_swift or bzlmod and Bazel caused this to be required.
https://github.com/bazelbuild/bazel-central-registry/pull/327
Now that bzlmod is more stable, we should likely look into adding a bzlmod verification pipeline directly in this repo so we can catch regressions earlier.
=> [bzlmod] Add dependency on platforms

.bazelci/presubmit.yml
Reverts bazelbuild/rules_swift#918 and unblocks https://github.com/bazelbuild/rules_swift/pull/963.
=> Revert "Workaround CI issue temporarily"

tools/worker/worker_main.cc
When building Swift code with `--enable_bzlmod`, it currently fails due to the worker failing to find the `index-import` executable in the runfiles. This is because the naming is different under bzlmod and the C++ runfiles library was updated to support this new mapping as described in this [talk](https://www.youtube.com/watch?v=5NbgUMH1OGo). Since rules_swift supports both Bazel 5 and 6, we need to check `BAZEL_CURRENT_REPOSITORY` is defined to  simply make use of the new constructor which will make it so the runfiles lookup will happen relative to the `rules_swift` repo under Bazel 6.
I tested this locally with a `local_path_override` while iterating on getting the `rules_xcodeproj` to work under bzlmod (and also continues to work with bzlmod disabled in Bazel 6): …
=> Fix runfiles lookup under bzlmod in Bazel 6

examples/xplatform/xctest/BUILD
When a feature name doesn't start with `swift.` we check if it's enabled
by checking against the C++ features, not against all features.
Previously the Linux CC toolchain didn't support sanitizers so these
just never worked on Linux and the features were silently ignored from
Swift. Today these features were added to the Linux CC toolchain
https://github.com/bazelbuild/bazel/commit/abae5ca3e8142f93cf0c2597e3410ed955c4dd59
which broke Linux CI because ubsan doesn't work with Swift on Linux and
asan fails because of a memory leak in Swift
=> Fix sanitizers on Linux

test/module_cache_settings_tests.bzl, test/rules/action_command_line_test.bzl
This adds string replacement for the workspace name since it is `_main`
when using bzlmod
=> Fix tests for bzlmod

MODULE.bazel, swift/repositories.bzl
This is now supported by bzlmod. This also removes the comment about
removing protobuf since we do directly depend on it, just previously we
relied on rules_proto to pull it in for us, so we can't remove it here.
=> Use rules_proto with bzlmod

.bazelci/presubmit.yml, examples/apple/objc_interop/BUILD, examples/xplatform/grpc/BUILD, examples/xplatform/grpc/client_unit_test.swift, examples/xplatform/grpc/main.swift, third_party/com_github_grpc_grpc_swift/BUILD.overlay
This way you can do `bazel test ...`. It also means we're testing gRPC
which was fixed at some point.
=> Fix testing everything on Linux

MODULE.bazel
This was the version we were getting from rules_proto anyways, so this
silences a bzlmod warning
=> Bump protobuf

swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
https://github.com/bazelbuild/bazel/issues/14127#issuecomment-1396053583
=> Remove obsolete `incompatible_use_toolchain_transition`

swift/internal/explicit_module_map_file.bzl
Without this value you get UB https://github.com/apple/swift/pull/63119
This hit us where it defaults to true with Swift 5.7.2 on Ubuntu 22.04,
but not on Ubuntu 20.04. I don't think this ever needs to be true for
bazel
=> Always add isFramework to explicit module map

swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
This reverts commit da30f00a2aae92bd32feb5f0cef0af23d6dabcfc.
We need to keep this until we drop Bazel 5 support: https://github.com/bazelbuild/bazel/issues/14127#issuecomment-1402082370.
=> Revert "Remove obsolete `incompatible_use_toolchain_transition` (#988)"

third_party/com_github_apple_swift_nio/BUILD.overlay, third_party/com_github_grpc_grpc_swift/BUILD.overlay
Allows https://github.com/bazelbuild/rules_swift/pull/995 to apply cleanly.
=> Remove overlay glob patterns with empty results

.bazelci/presubmit.yml
Always surprised that build_flags aren't used for the test invocation
=> Fix bzlmod for tests as well

doc/rules.md, examples/apple/test_filter/BUILD, examples/apple/test_filter/FailTests.swift, examples/apple/test_filter/PassFailTests.swift, examples/apple/test_filter/PassTests.swift, examples/apple/test_filter/TestHelper.swift, swift/internal/swift_binary_test.bzl, tools/xctest_runner/xctest_runner.sh.template
Implement `--test_filter` support, as detailed in https://github.com/bazelbuild/rules_swift/issues/997. This can be engaged via a `swift_test` target like so:
```
bazel test //:Tests --test_filter=TestModuleName.TestClassName/testMethodName
```
**Note:** If `--test_filter` is not passed into the test invocation, we fallback to the original behavior (pass `All` into the xctest invocation.
- IMPROVED:
- Implement `test_filter`, allowing users to inject a specific test scope into `swift_test` execution
=> Implement --test_filter support

swift/repositories.bzl, test/features_tests.bzl
I mainly wanted this to have CI pull down the `build_bazel_rules_swift_index_import` repository. Later we can add tests that would verify the interaction of `swift.use_global_index_store` and `swift.file_prefix_map`.
=> Add simple feature tests for `swift.use_global_index_store`

swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_toolchain.bzl
All versions of Swift we support can use this
=> Enable swift.use_response_files by default on Linux

swift/internal/compiling.bzl, test/fixtures/linking/fake_framework.bzl
When linking with the objc provider, we use `-F` and `-framework` to
link dynamic frameworks. With CcInfo we pass the binary path directly to
the linker instead, meaning any autolink commands like `-framework foo`
are invalid.
=> Disable autolinking for dynamic frameworks

swift/internal/feature_names.bzl, swift/internal/linking.bzl
This can then be used by a toolchain that needs the behavior to ensure
all Swift code makes it into the final binary.
PiperOrigin-RevId: 516553733
(cherry picked from commit b48dda98f02cb6ea63990560eb3c21d55af0e4b0)
=> Add a private feature for force alwayslink=True.

README.md, swift/internal/xcode_swift_toolchain.bzl, tools/common/BUILD, tools/common/bazel_substitutions.cc
Previously we did some amount of handling if you passed a custom
toolchain identifier. This didn't handle the case that the toolchain
required new compatibility libraries to actually link your binary. To
handle this we have to pass a new -L to the path in the root of the
toolchain. We do this with a custom env var that we replace, similar to
the DEVELOPER_DIR variable. Ideally this would be cached in memory, but
we can't do that without editing bazel, luckily xcrun has a cache that
makes this likely fast enough (about 0.01s for a cached invocation).
=> Add proper support for custom Swift toolchains

tools/worker/BUILD
With `--incompatible_use_host_features`, the select as it was no longer works, as it’s evaluated as `--host_fearture` instead of `—feature`.
=> Always add `index_import` to `data` for Apple based `swift_worker`

swift/internal/swift_autoconfiguration.bzl
This makes sure the rule is evaluated whenever a new Bazel server starts, which gives it a chance to regenerate the `swift-version` file which will be used in the resulting action keys.
One example to reproduce the issue without `local = True`:
```sh
ln -sf /opt/swift-5.7/bin/swift* /usr/local/bin/
bazel build //:swift-binary
cat $(bazel info output_base)/external/build_bazel_rules_swift_local_config/swift_version
bazel shutdown
ln -sf /opt/swift-5.8/bin/swift* /usr/local/bin/
bazel build //:swift-binary # cache hit (should be a miss)
cat $(bazel info output_base)/external/build_bazel_rules_swift_local_config/swift_version
```
with `local = True` the example above works as expected.
Fixes #1041
=> Mark swift_autoconfiguration as local

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/xcode_swift_toolchain.bzl, test/output_file_map_tests.bzl, test/split_derived_files_tests.bzl
Now that Xcode 14.1 is the minimum supported to the App Store, and Xcode
14.0 dropped support for bitcode, we don't need to handle these flags
anymore.
This keeps support for emitting LLVM Bitcode (confusing naming) for use
with LTO. This changes the relevant tests to test that behavior instead.
(cherry picked from commit 797660a758f924d9121689ba666d3f92044c2e5a)
=> Remove Bitcode support

.bazelrc
XCTest with Xcode 14.3 has a minimum target OS of 12.0, meaning any
tests we try to link below that version produce a warning
=> Fix minimum macOS version for tests

.bazelrc
This is required for testing tools in the host configuration with the
new Xcode otherwise it's possible the binary doesn't launch on your OS
=> Add --host_macos_minimum_os to .bazelrc

.bazelrc
With Xcode 15 XCTest is built for 13.0+, this should be ok since we
require Xcode 14.1+ which requires macOS 13.0+
=> Bump minimum test version to macOS 13.0

tools/common/process.cc
std::cerr is ignored when this code is being run with workers.
=> Fix stderr with workers

.bazelci/presubmit.yml
Realistically we're mostly getting 14.2 anyways since 14.3 isn't rolled
out on CI. This should make that more clear and will make sure we don't
get 14.3 machines as it starts rolling out again until we ask for it.
=> Move CI back to 14.2

swift/repositories.bzl, test/features_tests.bzl, test/fixtures/global_index_store/BUILD, test/fixtures/global_index_store/first.swift, test/fixtures/global_index_store/second.swift
Previously only arguments were validated, now we validate that the
actions actually succeed, which makes sure we successfully run
index-import
=> Add test validating global index store builds

swift/internal/xcode_swift_toolchain.bzl, test/coverage_settings_tests.bzl, test/debug_settings_tests.bzl, test/features_tests.bzl
This makes it easier to understand this variable is different from
`$DEVELOPER_DIR` and also makes it "absolute" so that tools like
index-import don't try to absolutize it.
=> Replace DEVELOPER_DIR remapping with '/PLACEHOLDER_DEVELOPER_DIR'

doc/api.md, doc/rules.md, swift/internal/BUILD, swift/internal/actions.bzl, swift/internal/compiling.bzl, swift/internal/swift_common.bzl, swift/internal/swift_import.bzl, swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl, swift/toolchains/BUILD, swift/toolchains/config/BUILD, swift/toolchains/config/compile_module_interface_config.bzl, test/BUILD, test/fixtures/module_interface/BUILD, test/fixtures/module_interface/Client.swift, test/fixtures/module_interface/ToyModule.swift, test/module_interface_tests.bzl, test/rules/swift_library_artifact_collector.bzl
(cherry picked from commit 47b464853d7a78cd387a095ebfeb61bf6f132410)
=> Add an API to compile a `.swiftinterface` file into a `.swiftmodule`.

swift/internal/swift_autoconfiguration.bzl, swift/internal/swift_toolchain.bzl
Checking `CC=clang` in the implementation of the `repository_rule` doesn't work when using `--incompatible_enable_cc_toolchain_resolution` (for example when using https://github.com/grailbio/bazel-toolchain to bring a hermetic LLVM toolchain).
Moving the check for LLVM the `repository_rule` to the Swift toolchain impl used by all `rule`s instead solves this issue.
I tested that the check (the failure message) is triggered on Linux with:
- only `gcc` installed
- a LLVM toolchain configured in `WORKSPACE` but without `--incompatible_enable_cc_toolchain_resolution`
TODO (maybe?):
Fixes #991
=> Move check for LLVM toolchain outside of repository_rule

swift/internal/compiling.bzl, test/module_interface_tests.bzl
This failed to compile previously because we passed -Xfrontend to
something that was already a frontend invocation
=> Fix compile_module_interface with explicit module map

.bazelci/presubmit.yml
There's a hole in bazel where target_compatible_with isn't enough https://github.com/bazelbuild/rules_swift/issues/1093
=> Disable apple tests on all linux CI jobs

.bazelci/presubmit.yml
Hoping the upstream branch takes the import default change to reduce
conflicts
=> Lock buildifier for now

swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/derived_files.bzl, swift/internal/feature_names.bzl, swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_clang_module_aspect.bzl, test/ast_file_tests.bzl, test/features_tests.bzl, test/generated_header_tests.bzl, test/output_file_map_tests.bzl, test/private_deps_tests.bzl
**Why it's needed?**
To be able to make builds of same framework with different module names, we need to modify output path so bazel won't have conflicts.
Right now, if we call:
`bazelisk build //PathToModule/ModuleName:Target1 //PathToModule/ModuleName:Target2`
where `Target1` and `Target2` are targets with different files but same module name
bazel will fail because it will try to build 2 different frameworks to same output.
By adding `--features=swift.add_target_name_to_output`, the output will be generated to separate folders, and as output, we will have 2 different framework binaries with different files, but same framework name
=> Added target name to output path to support multiple builds of same module

swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/derived_files.bzl, swift/internal/feature_names.bzl, swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl, swift/internal/swift_clang_module_aspect.bzl, test/ast_file_tests.bzl, test/features_tests.bzl, test/generated_header_tests.bzl, test/output_file_map_tests.bzl, test/private_deps_tests.bzl
Reverts bazelbuild/rules_swift#1082
This changes the behavior without enabling the feature in some cases. Specifically I found this in swiftlint where the output path of this target https://github.com/realm/SwiftLint/blob/b281a8d33a958a6c70c3ef18d4182378f337fd3a/BUILD#L81 ends up being `bazel-bin/swiftlint/swiftlint` instead of `bazel-bin/swiftlint` even without enabling this feature.
=> Revert "Added target name to output path to support multiple builds of same module"

swift/internal/linking.bzl, swift/internal/swift_binary_test.bzl
This was removed from bazel in https://github.com/bazelbuild/bazel//commit/ca8b39895bda7a48d7765b97ff9491794cb34edc
=> Remove grep_includes

.bazelci/presubmit.yml, platform_mappings, platform_mappings_bzlmod
Replace https://github.com/bazelbuild/rules_swift/pull/1102 with support for bzlmod
=> Add platform mappings

tools/common/process.cc
Turns out there is _environ. This isn't all of this support, we also have to process the env before exec'ing the process
=> Fix fetching env on windows

doc/BUILD.bazel, doc/rules.md, examples/xplatform/macros/BUILD, examples/xplatform/macros/StringifyUniversalClient.swift, swift/BUILD, swift/swift.bzl, swift/swift_compiler_plugin.bzl
This is useful if you populate caches using fat binaries so that they
can be shared between aarch64 and x86_64 macs
=> Add support for universal compiler plugins

swift/internal/swift_autoconfiguration.bzl, tools/worker/swift_runner.cc
This uses Swift's builtin feature detection to check what flags are
available. This probably means previous toolchains where macros weren't
complete would return true for this, but that's probably fine.
This also requires absolutizing TMPDIR since that is validated in a case
on Linux and errors otherwise. Hoping this doesn't cause issues.
=> Add macros support for Linux

swift/internal/actions.bzl, swift/internal/swift_grpc_library.bzl, swift/internal/swift_protoc_gen_aspect.bzl
Now that bazel 7.x has
https://bazel.build/reference/command-line-reference#flag--incompatible_merge_fixed_and_default_shell_env
enabled by default, we can set `use_default_shell_env = True` moving
forward. This makes actions respect `--action_env=FOO` which can be
useful for things like `TOOLCHAINS`, `ZERO_AR_DATE`, `TMPDIR`, etc.
Previously these were ignored.
=> Enable use_default_shell_env everywhere

swift/module_name.bzl
Fixes this error
```
(12:06:33) ERROR: Skipping '@build_bazel_rules_swift//examples/xplatform/xctest': error loading package '@build_bazel_rules_swift//examples/xplatform/xctest': at /private/var/tmp/_bazel_jesses/06c990151bb0d0bcaaf7ea85520191a3/external/build_bazel_rules_swift/swift/swift.bzl:55:5: at /private/var/tmp/_bazel_jesses/06c990151bb0d0bcaaf7ea85520191a3/external/build_bazel_rules_swift/swift/swift_compiler_plugin.bzl:51:6: compilation of module 'swift/module_name.bzl' failed
```
=> Fix "name 'visibility' is not defined" error on Bazel 5

.bazelrc
This is already set by Apple C++ toolchain.
=> Limit `--cxxopt='-std=c++14'` to Linux builds

.bazelci/presubmit.yml, doc/BUILD.bazel, swift/internal/swift_toolchain.bzl
This was the case before https://github.com/bazelbuild/rules_swift/commit/df485c2b62f83e2024c60ce322f8b4e2671d516b as well. This matters for windows where the compiler is `clang-cl`
=> Support clang fuzzy matches in compiler

test/BUILD, test/fixtures/xctest_runner/BUILD, test/fixtures/xctest_runner/FailingUnitTests.swift, test/fixtures/xctest_runner/PassingUnitTests.swift, test/rules/BUILD, test/rules/swift_shell_runner.sh.template, test/rules/swift_shell_test.bzl, test/xctest_runner_tests.bzl, tools/xctest_runner/xctest_runner.sh.template
Ports https://github.com/bazelbuild/rules_apple/pull/1978 into `rules_swift`.
- Updates the `xctest_runner` to fail if it doesn't execute any tests
- Adds tests for basic runner usage
- Adds tests for empty bundle cases
=> Update `xctest_runner` to fail if it doesn't execute any tests

swift/BUILD, swift/internal/BUILD, swift/internal/build_settings.bzl, swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
The Swift configuration fragment is being removed from bazel, this adds
the starlark flags necessary to replace the functionality. This differs
from the upstream solution since google doesn't have a need to support a
--host_swiftcopt replacement
(cherry picked from commit 8be724720ee6d1b73c52851106cf95b3cf158b3f)
=> Replace --swiftcopt with starlark flag

.bcr/presubmit.yml
Now that the BCR uses bzlmod the builtin toolchain is preferred which
doesn't work for us. This wouldn't be an issue if the tests in the bcr
ran within this repo
=> Disable builtin C++ toolchain in BCR presubmit

swift/internal/compiling.bzl, swift/internal/feature_names.bzl
This makes it easier for you to negate this feature and not have to
worry about command line flag ordering
=> Add swift.treat_warnings_as_errors feature

MODULE.bazel, swift/extras.bzl, swift/internal/swift_toolchain.bzl, swift/internal/target_triples.bzl, swift/internal/xcode_swift_toolchain.bzl, swift/repositories.bzl, test/output_file_map_tests.bzl, test/split_derived_files_tests.bzl
The swift fragment was removed at bazel HEAD and replaced by our custom
starlark flag for copts in rules swift. This requires a version check
that we're relying on bazel_features for if we want to be 100% accurate.
Fixes https://github.com/bazelbuild/rules_swift/issues/1148
=> Add support for removed swift fragment

doc/BUILD.bazel, doc/rules.md, swift/BUILD, swift/internal/BUILD, swift/internal/swift_library_group.bzl, swift/swift.bzl, test/fixtures/basic/BUILD
The `swift_library_group` rule acts as an alias for multiple other `{cc,objc,swift}_library`s. This will allow rules_swift_package_manager to properly map SPM’s library products to a target that can be added to other target’s `deps`.
=> Add `swift_library_group` rule

.bcr/presubmit.yml
This is needed now.
I didn't include `6.x` because it had toolchain registration issues on macOS. We can deal with that separately if we want.
=> Add bazel version to `.bcr/presubmit.yaml`

test/rules/action_command_line_test.bzl
My upstream PR renaming archives to CppArchive landed in 6.x+
Partial revert of d09eca80b0431ef53048f44782471aebf54c0a38
=> Revert CppLink workaround

proto/compilers/BUILD
This was causing `bazel test //...` to fail since `//swift/proto` is not a package
=> Fix docs build for proto compiler

swift/internal/swift_toolchain.bzl, swift/internal/xcode_swift_toolchain.bzl
This is a step towards removing it entirely.
PiperOrigin-RevId: 406230375
(cherry picked from commit d1ba795ff479881bf14ba70294693dcabace4fd4)
=> Remove uses of `incompatible_use_toolchain_transition` now that it is enabled by default.

swift/internal/compiling.bzl, swift/internal/vfsoverlay.bzl
The to_json and to_proto methods on struct are deprecated and will be
removed. The "json" and "proto" builtin modules should be used instead.
This replaces instances of `foo.to_json()` with `json.encode(foo)`.
=> Replace instances of to_json() method with json.encode(..)

.bcr/presubmit.yml
Similar to:
https://github.com/bazelbuild/rules_swift/blob/a20c38808cb7f1ac721bb5131c81e64f654e7536/.bcr/presubmit.yml#L27
This disables the `@rules_swift//examples/xplatform/deprecated_grpc/…` targets that were previously under the `@rules_swift//examples/xplatform/grpc/…` package to match the previous state on the BCR Linux machines.
=> Disable deprecated gRPC build target on BCR

swift/internal/actions.bzl, swift/internal/swift_toolchain.bzl, swift/internal/toolchain_config.bzl, swift/internal/utils.bzl, swift/internal/xcode_swift_toolchain.bzl
We'd like to retire this API, which is redundant with the `executable` and `tools` arguments to `ctx.actions.run|run_shell`.
=> Remove unnecessary uses of `ctx.resolve_tools`.

doc/rules.md, swift/internal/swift_import.bzl
Updates the `swift_import` documentation to provide more information on the `swiftinterface` attribute. This attribute is required when importing pre-built Swift targets across Xcode and/or OS versions.
Additionally, adds a warning when `swiftinterface` is used alongside `swiftmodule` as this used to just drop `swiftinterface` silently. We'll make this a failure in a new major version to not break users.
=> Update `swift_import` docs and add warning

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/xcode_swift_toolchain.bzl, test/features_tests.bzl
This should solve https://github.com/bazelbuild/rules_swift/issues/1202
and #1204
> There were issues with Swift compiler plugins (incl. macros) and nested sandboxes on macOS with Swift 5.9 that have been fixed with 5.10:
> swift: [apple/swift#70079](https://github.com/apple/swift/pull/70079)
> swift-driver: [apple/swift-driver#1493](https://github.com/apple/swift-driver/pull/1493)
> swift-package-manager: [apple/swift-package-manager#7167](https://github.com/apple/swift-package-manager/pull/7167)
I am not sure whether this flag is required on Linux too.
=> Disable Swift compiler sandboxing in Xcode 15.3+ to fix nested sandboxing

tools/worker/swift_runner.cc
This value can be assigned non-zero memory if not initialied with `false`.
I noticed when building with `file_prefix_map` feature disabled that the codepath checking for `true` was still getting hit causing global index store paths to be wrong.
=> Fix `file_prefix_pwd_is_dot_` default value

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, test/compiler_arguments_tests.bzl, test/fixtures/compiler_arguments/BUILD, test/output_file_map_tests.bzl
Add features to enable LTO (thin and full).
When passing `-lto=`, `swiftc` switches to emit bc files and the generated output-file-map must contain a mapping for `llvm-bc` instead of `object`.
=> Add features to enable LTO

MODULE.bazel
rules_swift 2.0 will have quite a few breaking changes. Users will possibly need to perform some migrations. Dependent rulesets will possibly need to make changes as well. If dependent rulesets can support both pre-2.0 and 2.0, they can use `bazel_dep.max_compatibility_level`.
=> Bump `module.compatibility_level`

examples/apple/objc_interop_modulemap/BUILD, examples/apple/objc_interop_modulemap/OIPrintStream.h, examples/apple/objc_interop_modulemap/OIPrintStream.m, examples/apple/objc_interop_modulemap/Printer.swift, examples/apple/objc_interop_modulemap/main.m, swift/internal/compiling.bzl, swift/internal/derived_files.bzl, swift/internal/feature_names.bzl, swift/internal/swift_clang_module_aspect.bzl, test/interop_hints_tests.bzl, test/private_deps_tests.bzl
Allows `objc_library` to modularly import `swift_library` targets without having to generate a similar module map.
=> Add feature to propagate the generated module map

doc/api.md, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/derived_files.bzl, swift/internal/linking.bzl, swift/internal/swift_binary_test_rules.bzl, swift/internal/swift_import.bzl, test/BUILD, test/ast_file_tests.bzl, test/features_tests.bzl, test/module_interface_tests.bzl, test/output_file_map_tests.bzl
In particular, only outputs that need to have the module name as part of the filename.
=> Apply `swift.add_target_name_to_output` only to outputs that need it

swift/internal/swift_clang_module_aspect.bzl
To make supporting Bazel 6 easier use `getattr` to conditionally get the `aspect_hints` attr. This can be removed when we drop support for Bazel 6 as `aspect_hints` are always available as an attr in Bazel 7+
=> Use `getattr` for `aspect_hints` in `swift_clang_module_aspect`

doc/api.md, proto/swift_proto_utils.bzl, swift/internal/compiling.bzl, swift/internal/swift_binary_test_rules.bzl, swift/internal/swift_clang_module_aspect.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/internal/utils.bzl, swift/swift_compiler_plugin.bzl
The choice to pass `compilation_contexts` separately was a trade-off. The compilation contexts nested inside the Clang modules aren't easily suitable for use here. We can't rely on only the direct modules' CCs because information that should still get propagated—like defines and include paths—would get lost when passing through any `objc_library` that doesn't export a module. And we don't want to process the full set of transitive modules' CCs for each compile action, as this would be a significant performance hit. The only other option considered was to propagate a copy of the CC at the top level of `SwiftInfo`, even for no-module `objc_library` targets, but there were concerns about performance here as well, and whether that context would drift from the real one.
Even with the extra …
=> Pass `compilation_contexts` and `swift_infos` instead of `deps` to `swift_common.compile`

proto/BUILD, proto/swift_proto_utils.bzl, swift/BUILD, swift/internal/BUILD, swift/internal/compiling.bzl, swift/internal/output_groups.bzl, swift/internal/swift_binary_test_rules.bzl, swift/internal/swift_library.bzl, swift/internal/swift_module_alias.bzl, swift/swift_compiler_plugin.bzl
Partial cherry-pick of `supplemental_compilation_output_groups` from 69349eeba42ed7b7365759ba208067b4aa23854d, in order to use it in another cherry-pick.
=> Cherry-pick `supplemental_compilation_output_groups`

.bazelci/presubmit.yml
Bazel CI Windows machines do not have Swift.exe installed and builds fail. Temporarily disable this until Windows machines are properly configured for Swift.
=> Temporarily disable Windows CI due to missing Swift binary

swift/BUILD, swift/internal/BUILD, swift/internal/linking.bzl, swift/internal/swift_binary.bzl, swift/internal/swift_test.bzl, swift/swift.bzl
The implementation of `swift_test` is becoming more complex and diverging from just a simple binary now that test discovery is supported, so it makes more sense to have these rules live in separate files and move common functionality into `linking.bzl` instead.
PiperOrigin-RevId: 430970577
(cherry picked from commit 9ab07198f2f678451ce627749d9fc90fa441d59d)
=> Separate `swift_binary` and `swift_test` into their own .bzl files

swift/internal/actions.bzl, swift/internal/autolinking.bzl, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/features.bzl, swift/internal/symbol_graph_extracting.bzl, swift/internal/xcode_swift_toolchain.bzl, tools/worker/swift_runner.cc, tools/worker/swift_runner.h
PiperOrigin-RevId: 439679495
(cherry picked from commit 4cc310d33290df290b729334eb6aead6127867cf)
=> Add the `-Xwrapped-swift=-bazel-target-label=...` flag to pass the label of the target that spawns the worker, for future diagnostic purposes

doc/api.md, proto/swift_proto_utils.bzl, swift/internal/BUILD, swift/internal/attrs.bzl, swift/internal/swift_binary.bzl, swift/internal/swift_clang_module_aspect.bzl, swift/internal/swift_common.bzl, swift/internal/swift_import.bzl, swift/internal/swift_library.bzl, swift/internal/swift_library_group.bzl, swift/internal/swift_module_alias.bzl, swift/internal/swift_symbol_graph_aspect.bzl, swift/internal/swift_test.bzl, swift/internal/swift_toolchain.bzl, swift/internal/toolchain_utils.bzl, swift/internal/xcode_swift_toolchain.bzl, swift/swift_compiler_plugin.bzl
This is change 1 of _N_ to migrate the Swift build rules to use new-style Bazel toolchains. This change:
*   Updates the toolchain configuration rules to wrap the `SwiftToolchainInfo` provider in `platform_common.ToolchainInfo`, for future use by `toolchain()` rules.
*   Funnels all toolchain access through a new `swift_toolchain.get_toolchain()` function that looks up the toolchain using `ctx.toolchains`, falling back to the implicit attribute.
Since `ctx.toolchains` isn't defined yet, the second change is a no-op but it simplifies future parts of the migration.
PiperOrigin-RevId: 439638938
(cherry picked from commit 884e54426535acb820c746ccff074546b5796402)
=> Introduce the `swift_common.get_toolchain` helper function

doc/doc.bzl, doc/rules.md, examples/xplatform/custom_swift_proto_compiler/rules/custom_swift_proto_compiler.bzl, examples/xplatform/custom_swift_proto_compiler/swift/BUILD, examples/xplatform/grpc/service/BUILD, examples/xplatform/proto/BUILD, examples/xplatform/proto_files/BUILD, examples/xplatform/proto_glob/BUILD, examples/xplatform/proto_library_group/service/BUILD, examples/xplatform/proto_path/protos/package_1/BUILD, examples/xplatform/proto_path/protos/package_2/BUILD, proto/compilers/BUILD, proto/compilers/swift_proto_compiler_macros.bzl, proto/proto.bzl, proto/swift_proto_library.bzl
Similar to the deprecation of `swift.bzl`.
=> Deprecate the umbrella `proto.bzl` file

swift/internal/BUILD, swift/internal/actions.bzl, swift/internal/compiling.bzl, swift/internal/toolchain_config.bzl, swift/toolchains/BUILD, swift/toolchains/xcode_swift_toolchain.bzl
Now that Bazel supports nested/capturing functions, just use those throughout.
PiperOrigin-RevId: 449500122
(cherry picked from commit ffba849c424f08c7236e3826d41cb75b63f2be1b)
=> Remove Skylib `partial` usage

.bazelci/presubmit.yml, test/symbol_graphs_tests.bzl
Swift 5.9.2 is the version shipped with Xcode 15.2 (used by the current macOS CI) so this will more correctly match versions.
=> Update Ubuntu CI to use Swift 5.9.2

swift/swift_test.bzl, tools/test_observer/BUILD
Missed in d6b7f13d42d5a030247421e795e01148f517adc2.
=> Fix `test_observer` usage

swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl, test/fixtures/linking/fake_framework.bzl
PiperOrigin-RevId: 456368560
(cherry picked from commit 0bb2adac2b2cc7dec0c62806e507d1a5c028e68d)
=> Update rules that require a cpp toolchain to use a helper function that defines the toolchain type

swift/toolchains/config/compile_config.bzl
If a propagated `.swiftmodule` is ever in a directory-based layout (`Name.swiftmodule/$TARGET.swiftmodule`), then we need to add the path to the directory containing the top-level module directory, not the path to the `.swiftmodule` directory itself.
PiperOrigin-RevId: 456263364
(cherry picked from commit 21580ead964dc0e2690ba4bb64ede3293881e258)
=> Correctly add `.swiftmodule` directories to the search path.

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/toolchains/config/compile_config.bzl
When building with explicit modules, Swift compilations do not require any of the headers to be present on disk, because the AST contains all the necessary information (save for a bug(?) in `canImport` which fails if the headers aren't also present). However, other tooling may want to inspect compilation actions and have access to those headers.
This feature is a no-op for implicit module builds, since the headers are always included to begin with, and it is off by default.
PiperOrigin-RevId: 461668350
(cherry picked from commit 81f7b547ff6dea6e67fb0ee4c59e1e5a945cd03d)
=> Add a feature to always include all headers as inputs to SwiftCompile actions, even when using explicit modules

swift/internal/target_triples.bzl
Precompiled pcm files will be generated with the target triple, however the minimum supported version for arm64 on an ios-simulator is 14.0. Any minimum OS under 14 will be raised to 14 by the swift driver and clang tools. This logic is not applied to the AST serialized into pcm object files. To ensure the AST is correctly specified, adjust the target triple to configure the lower bounds correctly.
PiperOrigin-RevId: 458248769
(cherry picked from commit b100c3ff77cd786bab452ab62f5d1a3fa469ad27)
=> When calculating the target triple for 'arm64-apple-ios<version>-simulator' targets, correctly specify the minimum supported OS

swift/toolchains/config/compile_config.bzl, swift/toolchains/xcode_swift_toolchain.bzl, test/BUILD
PiperOrigin-RevId: 462641052
(cherry picked from commit 47b464853d7a78cd387a095ebfeb61bf6f132410)
---
Cherry-pick notes: We already picked most of this in 9abae7d7340c5e9e520f5170054a085d485879e0. This is just applying missed changes and formatting changes.
=> Add an API to compile a `.swiftinterface` file into a `.swiftmodule`

swift/toolchains/config/compile_config.bzl
PiperOrigin-RevId: 467339063
(cherry picked from commit 2a1a3874718305aeb83ff5506d2c58616bf81584)
=> Support order file instrumentation in swift compile actions

swift/swift_common.bzl, swift/toolchains/xcode_swift_toolchain.bzl
RELNOTES: None
PiperOrigin-RevId: 469724398
(cherry picked from commit b6f31e71db7e9dde4bada8fddc93a0fb71bd6fbf)
=> Update a few comments for swift.bzl references.

doc/rules.md, swift/swift_import.bzl
In rules_swift 1.x specifying both `swiftinterface` and `swiftmodule` would cause the `swiftinterface` attr to be ignored. This was made into a warning then and is being upgraded to a failure now for rules_swift 2.x
=> Make it an error to specify both `swiftinterface` and `swiftmodule` in `swift_import`

swift/internal/toolchain_utils.bzl
PiperOrigin-RevId: 471276851
(cherry picked from commit d3302c7ef0c4e159699c043f6f4f5191c5ef51d5)
=> Switch the toolchain type name back to `toolchain_type`, the canonical spelling.

tools/test_observer/BazelXMLTestObserver.swift, tools/test_observer/BazelXMLTestObserverRegistration.swift
PiperOrigin-RevId: 631886302
(cherry picked from commit 36992305ad9a4f01aeea907c14838031cb80d38a)
=> Annotate the test observer with `@MainActor` where needed to be concurrency-safe

swift/toolchains/config/compile_config.bzl
PiperOrigin-RevId: 632457020
(cherry picked from commit 542ecfe9a509b68957ee4aa092b9e74a3b6dbd11)
=> Add infrastructure to ban certain Swift compiler flags

swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 474288510
(cherry picked from commit 0fb1b0f4d60e231a58d264248a14337094e372dc)
=> Use the new driver on Xcode 14.x since it contains the fixes in https://github.com/apple/swift-driver/pull/1036

swift/BUILD, swift/internal/BUILD, swift/internal/debugging.bzl, swift/internal/linking.bzl, swift/swift_binary.bzl, swift/swift_compiler_plugin.bzl, swift/swift_test.bzl
The `.swiftmodule` resulting from compilation of the target's sources was being ignored (since it cannot be a dependency of anything else), but it needs to be embedded as with any other `.swiftmodule` in order for LLDB to find it and initialize the AST context properly.
PiperOrigin-RevId: 477544434
(cherry picked from commit c0cdb8b5a2100b3962993654f7409b80f3ce96f2)
=> Fix LLDB expr evaluation for `swift_{binary,test}` targets only containing Swift in their `srcs`

swift/internal/feature_names.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 471797061
(cherry picked from commit 585e7a7f55a392050687e9b2cf90f2348cee0caa)
=> Delete the `swift.bundled_xctests` feature

swift/swift_test.bzl
Otherwise, the binary might link to XCTest when it otherwise isn't using it (strongly linking to `@rpath/libXCTestSwiftSupport.dylib`, which won't be found at runtime when not using the `xctest` launcher).
PiperOrigin-RevId: 471801873
(cherry picked from commit 5da9abdea9d67fbe80ba7246f0b2335cf6657f68)
=> Only link in the Bazel test observer when discovering tests.

swift/swift_test.bzl
When doing manual discovery, this allows the generated sources to `@testable import` that module even when building with `-c opt`.
PiperOrigin-RevId: 471809177
(cherry picked from commit 82f828b983baecd0fa3ee14a6754eb71938895c0)
=> Pass `-enable-testing` when compiling the sources in a `swift_test` in discovery mode

MODULE.bazel
It has its `max_compatibility_level` increased to support rules_swift 2.0.
=> Upgrade swift_argument_parser to 1.3.1.1

examples/xplatform/c_from_swift/BUILD, examples/xplatform/cxx_from_swift/BUILD, examples/xplatform/cxx_from_swift/counter.cc, examples/xplatform/cxx_from_swift/counter.h, examples/xplatform/cxx_from_swift/main.swift
Extends the simple "counter" example from `c_from_swift` to show how to use the [`-cxx-interoperability-mode`](https://www.swift.org/documentation/cxx-interop/project-build-setup/#mixing-swift-and-c-using-other-build-systems) build flag to invoke C++ directly from Swift.
https://www.swift.org/documentation/cxx-interop/
=> Add C++ Interoperability example

proto/swift_proto_compiler.bzl
I noticed that when I had a long list of deps for a `swift_proto_library` target, my builds would fail with an error `unrecognized argument: --param`. This is because protoc expects param files to be prefixed with `@` instead of a `--param` arg. That change + using the `multiline` file format allows everything to work as intended.
=> Fix usage of params files in _swift_proto_compile

swift/internal/symbol_graph_extracting.bzl, swift/toolchains/config/compile_config.bzl
This updates the symbol graph extract configurator to additionally include the `.swiftdoc` files created by the the Swift module compilation. This is required to produce documentation comments in the `.symbolgraphs` when using the symbol graph extract rule.
=> Update extract symbol graphs rule to include swiftdoc

.bcr/config.yml
Without this file the commit should be attributed to the BCR bot which probably makes more sense.
=> Remove BCR fixed releaser config

.bcr/config.yml
Turns out because were on bazelbuild org a fork of the registry isnt possible and so the fixed releaser must be set to tell the bot where the fork lives.
=> Re-add fixed releaser

doc/rules.md, swift/BUILD, swift/swift_library_group.bzl
While working on something else I realized that the code for `swift_library_group` was more complex than it needed to be.
=> Simplify `swift_library_group`

tools/xctest_runner/xctest_runner.sh.template
Looks like the change in https://github.com/bazelbuild/rules_swift/commit/d6b7f13d42d5a030247421e795e01148f517adc2 forgot to replace the `%executable%` reference for running coverage.
=> Fix coverage executable substitution in template

swift/internal/target_triples.bzl
The swift compiler will make this adjustment for us. Removing this fixes an issue in rules_xcodeproj where the minimum os doesn’t match what the module was built for.
=> Remove arm simulator minimum version adjustment

swift/internal/BUILD, swift/internal/swift_autoconfiguration.bzl, toolchains/BUILD
These can be used once we flip the ruleset to actual return the toolchain type from `use_swift_toolchain()`.
=> Add toolchains

doc/api.md, swift/internal/actions.bzl, swift/internal/compiling.bzl, swift/internal/toolchain_utils.bzl
This updates the following APIs:
-   `swift_common.get_toolchain` now takes an `exec_group` argument, which is will look up the toolchain under `ctx.exec_groups[NAME]` instead of `ctx`.
-   `swift_common.{compile,compile_module_interface,precompile_clang_module}` now take an `exec_group` argument, which is passed down to the underlying `ctx.actions.run` call for actions using the toolchain.
In all cases the default value of the argument is `None`, so omitting it retains the current behavior.
Most importantly, this lets us declare the Swift toolchain somewhere other than the rule/aspect's `ctx`, which ensures that in a multiple toolchain scenario, the Swift toolchain doesn't fully decide the execution platform for all actions (even non-Swift actions).
Since execution groups are somewhat in …
=> Allow the Swift toolchain to be associated with an execution group and pass an optional execution group name down to actions that use it

.bazelci/presubmit.yml, MODULE.bazel, swift/internal/toolchain_utils.bzl, swift/repositories.bzl
PiperOrigin-RevId: 503982850
(cherry picked from commit c42aad205d457f6fede1da7ab245800d3ec76641)
=> Switch the Swift rules over to toolchains

swift/BUILD, swift/internal/providers.bzl, swift/swift_module_mapping.bzl
This change only adds the new rule and its provider. The build flag (mentioned in documentation) and compilation support will be added in subsequent changes.
PiperOrigin-RevId: 486235761
(cherry picked from commit 6b56b0114674e7d88ab6f2e72d6c3fb5fb646093)
=> Add the `swift_module_mapping` rule

swift/internal/feature_names.bzl, swift/toolchains/config/compile_config.bzl, test/debug_settings_tests.bzl, tools/worker/swift_runner.h
We can use -file-prefix-map instead of -debug-prefix-map starting in Xcode 14. This has the main benefit of remapping debugging, indexing, and coverage paths, all with a single flag.
Keeping this opt-in for now, we'll test this out locally before a further rollout.
PiperOrigin-RevId: 477010867
(cherry picked from commit bead1236f52a66b705315f0334a937ad174ed3f5)
Cherry-pick notes: we implemented this in 20d7d9df4dcd8d0ad96c27d9fd477df846e8eab4. This cherry-pick just adds a couple things from upstream’s version of the same change.
=> Add -file-prefix-map support

doc/api.md, swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/swift_clang_module_aspect.bzl, swift/toolchains/config/compile_config.bzl, test/rules/expected_files.bzl, test/rules/provider_test.bzl
This allows us to index explicit PCMs once they are built and then
never again. Currently we only do this for system SDKs as we assume
that we already have source code available for other SDKs, but this
can be expanded in the future.
In addition, make swift.file_prefix_map also remap DEVELOPER_DIR.
PiperOrigin-RevId: 478594522
(cherry picked from commit a5d5c2b54055ec20edbd14a4f38ad333ff3bc919)
---
Only add "index-unit-output-path" in the output map for modular indexing
Pre Xcode 14 you'll get a warning if this is specified without having indexing enabled:
```
<unknown>:0: warning: -index-unit-output-path is ignored without -index-store-path
```
We can reconsider this in the future (e.g. to automatically set this for Xcode 14+),
but for now limit the scope based on the modular indexing …
=> Add new swift.modular_indexing feature to index explicit PCMs

swift/internal/compiling.bzl
After recent IndexStoreDB changes, relative paths are supported using the explicit unit list.
PiperOrigin-RevId: 486725675
(cherry picked from commit 5b728e690ce51eb6a67236cda1449181eb3c4a52)
=> Don't use an absolute path for index unit names

swift/BUILD
PiperOrigin-RevId: 508369461
(cherry picked from commit 7f5fbf8d9283cd1262fe625883533da419c4c5a7)
=> Add visibility to Starlark flags

doc/api.md, swift/internal/compiling.bzl
PiperOrigin-RevId: 487024190
(cherry picked from commit 4e48b7ad1cb13e5d36f6fbb4050a915b259abc9b)
=> Add copts parameter to compile_module_interface()

swift/BUILD
This makes cherry-picks easier, since it will be moved here as part of a cherry-pick that we have to take later.
=> Move the `//swift:swift` target

swift/swift_import.bzl
`swift_library` is also moving in this direction.
SwiftPM works by linking all the .o files, so this should end up in a state that seem users familiar with SwiftPM/Xcode will expect. Otherwise an `@objc` class might not be findable by name only, or a protocol conformance might not get included leading to confusing runtime problems.
PiperOrigin-RevId: 527908878
(cherry picked from commit 2cc542ab55335dff09da8af42e4c69d7f005699d)
=> `swift_import`: always link the import.

doc/BUILD, doc/doc.bzl, doc/rules.md, swift/BUILD, swift/swift_module_mapping_test.bzl, test/fixtures/module_mapping/BUILD, test/fixtures/module_mapping/Empty.swift, test/module_mapping_tests.bzl
This rule is used to validate that a `swift_module_mapping` covers the transitive closure of a set of dependencies, preventing unaliased dependencies from being added to those libraries without the target owner's knowledge.
PiperOrigin-RevId: 486711497
(cherry picked from commit 8e34b95c4305e07cede4ceca2bda2f1b98671a06)
=> Add the `swift_module_mapping_test` rule

swift/internal/feature_names.bzl, swift/internal/swift_autoconfiguration.bzl, swift/toolchains/config/compile_config.bzl, swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 523108542
(cherry picked from commit dc20ca5800e42675fd5ac249bc8e1569606a60b4)
=> Remove checks for Xcode versions prior to 14.0 and unconditionally enable features that require 14.0 or greater

swift/swift_test.bzl
PiperOrigin-RevId: 537974634
(cherry picked from commit 693b10c31fa6770a5d8170206908c4dd807f6dd9)
Cherry-pick notes: Also a slight refactor to align better with future cherry-picks.
=> Only pass test runner deps to `swift_test` test runner compile

swift/internal/feature_names.bzl, swift/toolchains/config/compile_config.bzl
PiperOrigin-RevId: 521541916
(cherry picked from commit f2022d7e2097a94979bdcb8fb4a31bf8cec693ee)
=> Add `swift.checked_exclusivity` feature

doc/api.md, doc/doc.bzl, mixed_language/BUILD, mixed_language/mixed_language_library.bzl, proto/BUILD, proto/swift_proto_library.bzl, proto/swift_proto_library_group.bzl, swift/BUILD, swift/internal/BUILD, swift/internal/compiling.bzl, swift/module_name.bzl, swift/swift_binary.bzl, swift/swift_clang_module_aspect.bzl, swift/swift_common.bzl, swift/swift_library.bzl, swift/swift_module_alias.bzl, swift/swift_test.bzl
Since rules may want to use this without the other functionality in `swift_common` (e.g., compilation), isolating it to its own file can reduce analysis churn when other parts of the rule implementations change.
PiperOrigin-RevId: 493078921
(cherry picked from commit 47bd14c2be5ac36bf1ae616ea5eb680c42f15ef2)
=> Extract `derive_swift_module_name` as a free function in its own `.bzl` file

swift/swift_clang_module_aspect.bzl
This is no longer used anywhere.
PiperOrigin-RevId: 495593700
(cherry picked from commit 3cb3d5ba8390a9e8de2d78197694059fd0bff093)
=> Remove the `swift_explicit_module` output group from `swift_clang_module_aspect`

swift/toolchains/config/compile_config.bzl
PiperOrigin-RevId: 516571440
(cherry picked from commit cda3e7f60c9822ee61c08774e8a232fe81a3418e)
=> Allow configuring clang module dependencies for precompiled c modules

swift/toolchains/xcode_swift_toolchain.bzl
Because of the complexity, I would like to disable AEGs in this rule and proceed with the rest of the migration and flip the flag. I'll come back in the near future to enable them and add `toolchain` param to the affected actions.
PiperOrigin-RevId: 567319616
(cherry picked from commit ee7f493a87e206db35f724601c52d1a18d64eb50)
=> Disable AEGs inside xcode_swift_toolchain

swift/BUILD, swift/swift_binary.bzl, swift/swift_compiler_plugin.bzl, swift/swift_import.bzl, swift/swift_test.bzl
These rules should register swift toolchain and then use it inside run_toolchain_action. Until then, AEGs will be disabled.
PiperOrigin-RevId: 567330453
(cherry picked from commit 3e50799d9a54bd84de114eb5a1660135e79b15ce)
=> Disable AEGs inside rules which uses swift toolchain from a rule's attribute

doc/providers.md, swift/internal/features.bzl, swift/providers.bzl, swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 559395644
(cherry picked from commit 191ecad86fd60d33748312f77680201e6ac0ae95)
=> Pass `language = "objc"` to `cc_common.configure_features` when targeting an Apple platform

swift/toolchains/config/compile_config.bzl
LLDB wants these files to be present on the file system to step into macro expansions, because their file paths are recorded in debug info. The compiler uses `TMPDIR` (if set) as the location for those files, so we can have the worker set `TMPDIR` to a target-specific location before spawning `swiftc`. If this location is workspace-relative, then those file paths are also remapped via `-debug-prefix-map`—an added bonus.
The `macro_expansions` group will contain a tree (directory) artifact that contains a `swift-generated-sources` subdirectory (the compiler forces that name), which contains one or more `.swift` files representing the expanded macro buffers.
PiperOrigin-RevId: 549932429
(cherry picked from commit 69349eeba42ed7b7365759ba208067b4aa23854d)
Cherry-pick notes: We already …
=> Capture macro expansions in an output group named `macro_expansions` during debug builds

swift/BUILD
PiperOrigin-RevId: 584323059
(cherry picked from commit 8be724720ee6d1b73c52851106cf95b3cf158b3f)
=> Add visibility to `copt` and `exec_copt` Starlark flags

swift/internal/compiling.bzl, test/module_mapping_tests.bzl
PiperOrigin-RevId: 491933710
(cherry picked from commit d4bb9bc4d3ba16a67bb425209050efe815ac828e)
=> Add cross-import overlay `SwiftInfo`s to compilation prerequisites when needed

doc/api.md, swift/internal/compiling.bzl
PiperOrigin-RevId: 495349646
(cherry picked from commit 283ee7bef5ac828f5643b06b08698f74698fb24c)
=> Compile a .swiftinterface file into a .swiftmodule if present in apple_sdk_module rule

doc/api.md, swift/internal/compiling.bzl, swift/swift_compiler_plugin.bzl, swift/swift_library.bzl, swift/swift_module_alias.bzl, swift/swift_test.bzl
The impetus for this change was the fact that inferred cross-import overlay providers weren't being merged into the propagated `SwiftInfo`, so compiling a target that directly depended on one would succeed but compiling something depending on that other target would fail.
Since provider merging was being done by the rules, not by the `compile` call that collected the providers, we would have had to offer a separate API for rule implementations to collect those same cross-import providers or have `compile` return them in some separate fashion.
However, all current callers of `swift_common.compile` are doing exactly the same thing: creating a new `SwiftInfo` that merges the returned module context with the deps `SwiftInfo`s that it already collected and passed to `compile`. So, it's …
=> Simplify `swift_common.compile` so that it returns a `SwiftInfo` that can be propagated by callers

swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 521551636
(cherry picked from commit 9020dbbaba6ae7fadd0e54f9757576cce601f805)
=> Enable `swift.checked_exclusivity` by default

swift/swift_clang_module_aspect.bzl, swift/swift_import.bzl
PiperOrigin-RevId: 493691217
(cherry picked from commit 359435eb76b19479f94b9877b57f46439b03f6ef)
=> Remove some lingering references to `swift_common` members that were extracted as free functions

doc/api.md, proto/BUILD, proto/swift_proto_library.bzl, swift/swift_common.bzl
No custom rules are using these today. If they need to, they can just declare whatever attributes they need on their own.
PiperOrigin-RevId: 495328434
(cherry picked from commit 28a27e1f8d9263cfba2210feb6f3192024822e80)
=> Remove `compilation_attrs` and `library_rule_attrs` from `swift_common`

swift/internal/feature_names.bzl, swift/toolchains/config/compile_config.bzl
PiperOrigin-RevId: 574234005
(cherry picked from commit c9b81c0e639a90a66c08ec349c860c6e753ffddd)
=> Add a feature that enables `-index-include-locals` for Swift compiles

swift/internal/compiling.bzl, swift/toolchains/config/compile_config.bzl, test/rules/provider_test.bzl
(cherry-picked from 18f2f8711d4fc097bf66f85c5804c9fd13c1e161)
Chery-pick notes: Still didn’t take `_maybe_create_const_protocols_file` for now, since we keeping it as a constant file.
=> Align with upstream `const_gather_protocols` change

swift/internal/actions.bzl, swift/toolchains/config/action_config.bzl, swift/toolchains/config/compile_config.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 597649558
(cherry picked from commit b67e07a6b2d29ffdec0223db7a352c192a087542 and c9932a1ee217d2d2616d886ae00ff1756779b058)
=> Use `ConfigResultInfo` to set additional tools

swift/toolchains/config/compile_module_interface_config.bzl
PiperOrigin-RevId: 647279184
(cherry picked from commit 0d9db4bfb41e24738bc074b54ef72896add268fc)
=> Remove duplicate `-enable-library-evolution` flag

swift/providers.bzl, swift/swift_clang_module_aspect.bzl
that `swift_clang_module_aspect` always returns, so that other aspects can use `required_aspect_providers` to ensure correct ordering of aspect application and thus depend on the `SwiftInfo` provider attached by the aspect without having to unconditionally require it
PiperOrigin-RevId: 617942821
(cherry picked from commit f922a1daeb3974ae9843458facacf1aadb402b17)
=> Create an empty marker provider`SwiftClangModuleAspectInfo`

swift/swift_import.bzl
PiperOrigin-RevId: 618250957
(cherry picked from commit 6d61c03390a63e3c2edc1241096ee13a6e6c668f)
=> Make sure `swift_import` propagates the `.swiftinterface` file in its `SwiftInfo` if it's given one as an input

doc/api.md, swift/internal/compiling.bzl, swift/providers.bzl
PiperOrigin-RevId: 542015885
(cherry picked from commit faf98ee8118b385a5a64ba0489e22770c42145d2)
=> Add an `is_framework` parameter to `compile_module_interface`

swift/internal/explicit_module_map_file.bzl
Check module_context and write out "isSystem" and "isFramework" attributes to swift explicit module map if present.
PiperOrigin-RevId: 542029509
(cherry picked from commit 1a449995cee878c3f4ca1fcdc947579605e8bd0f)
=> Write "isSystem" and "isFramework" in explicit swift module map

swift/toolchains/config/compile_config.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 528874942
(cherry picked from commit 9c81e82bb0fcb30593119d21fc7cd42668d8ed73)
=> Extract `command_line_objc_copts` to `compile_config.bzl`

doc/api.md, swift/internal/toolchain_utils.bzl
PiperOrigin-RevId: 634762729
(cherry picked from commit 0300b69180088274bb8accf147e3708280feff36)
=> Allow rules/aspects to optionally depend on the Swift toolchain

swift/internal/BUILD, swift/internal/features.bzl, swift/internal/swift_autoconfiguration.bzl, swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 526077161
(cherry picked from commit b7abb388db2de17a709fcf32ae791b9fca5ee276)
Cherry-pick notes: I took the liberty of unconditionally enabling some linux features that have been available in the Swift toolchain for some time now.
=> Consolidate default features logic

swift/internal/attrs.bzl, swift/internal/providers.bzl, swift/swift_binary.bzl, swift/swift_compiler_plugin.bzl, swift/swift_test.bzl
PiperOrigin-RevId: 573783919
(cherry picked from commit 6cae838e1fcbcc344fa2a29dc272261e719cba6e)
=> Allow testing of `swift_binary` targets

swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/features.bzl, swift/internal/swift_autoconfiguration.bzl, swift/toolchains/config/compile_config.bzl, swift/toolchains/xcode_swift_toolchain.bzl
PiperOrigin-RevId: 598844646
(cherry picked from commit f17ec3b27a214ab4557aa83e4d6a10be6c9f8788)
=> Add the ability to enable upcoming and experimental Swift features via Bazel features

swift/internal/feature_names.bzl, swift/internal/features.bzl, swift/internal/swift_autoconfiguration.bzl, swift/toolchains/config/compile_config.bzl, swift/toolchains/xcode_swift_toolchain.bzl
This flag is designed with ease of migration in mind. On toolchains that directly support the Swift 6 language mode (none have been released yet), enabling this feature on a target will simply pass `-swift-version 6` to the compiler. On older compilers however, it will instead pass the equivalent set of `-enable-upcoming-feature` flags as defined inside the compiler. This allows code to begin migrating to Swift 6 mode even before they switch to a Swift 6 toolchain.
PiperOrigin-RevId: 629396220
(cherry picked from commit 86f356cc3ab35d02edd3efe972a76e1d0a6a7261 , f1765e6e65ab742e332704717ec7e0129a9b60af, 8065c86800ac18ce6ee0eefe9dac4c0d4c24ef59, and 3cb393fa0bcf8b5e63c875b23ff5779daaf20acd)
=> Add the `swift.enable_v6` feature to support migration to the Swift 6 language mode

doc/BUILD, doc/doc.bzl, doc/rules.md, swift/BUILD, swift/swift_compiler_plugin_import.bzl, swift/swift_import.bzl
PiperOrigin-RevId: 633256010
(cherry picked from commit c77187bb147b1c13b0d002a17b238f4286c8c1b1)
=> Define `swift_compiler_plugin_import` to support pre-built compiler plugins, and add a `plugins` attribute to `swift_import`

swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl, test/fixtures/module_interface/Client.swift, test/fixtures/module_interface/library/ToyModule.swift
This feature also makes it an error for `.swiftinterface` files to publicly import non-resilient modules, so I've updated our `.swiftinterface` test case to stop depending on Foundation, which is not resilient on Linux.
PiperOrigin-RevId: 640123191
(cherry picked from commit b5230b0052adef0f802fafdec8dc618fa5cc6518)
=> Enable `AccessLevelOnImport` by default

.bcr/presubmit.yml
We can’t depend on dev dependences in these tests.
=> Stop running macro tests on BCR presubmit

swift/swift_test.bzl
Once we migrate to platforms/toolchains, this will avoid the default behavior where a toolchain's `exec_compatible_with` determines the action routing for all actions under that rule.
PiperOrigin-RevId: 501277236
(cherry picked from commit 11e5b45a3cff3ec240bb9fbbabb90d6572c86e54)
=> Add execution groups for actions that don't have to use the same toolchain used when building the target

swift/repositories.bzl
Regressed for WORKSPACE users in 7fafc9bc47e80ca9fb08affeb44d135818c8c8db.
=> Fix `build_file` labels

doc/BUILD, doc/api.md, doc/doc.bzl
Missed in e76d714c98ad2b621bd571faeefb836d263fd460.
=> Add back API docs for function removed from `swift_common`

doc/api.md, mixed_language/internal/library.bzl, proto/BUILD, proto/swift_proto_library_group.bzl, swift/BUILD, swift/internal/BUILD, swift/internal/attrs.bzl, swift/internal/swift_symbol_graph_aspect.bzl, swift/swift_clang_module_aspect.bzl, swift/swift_common.bzl, swift/swift_import.bzl
PiperOrigin-RevId: 559415879
(cherry picked from commit c7cf7c3c428e719b2d7ade197eb56a618cf09328)
Cherry-pick notes: Other rulesets will need to fully migrate to using toolchains, and `swift_common.get_swift_toolchain` in particular, with this change.
=> Remove `swift_common.toolchain_attrs`

proto/swift_proto_library_group.bzl, swift/swift_compiler_plugin.bzl, test/fixtures/module_mapping/apply_mapping.bzl
Rules are not required to have an implicit dependencies on the transition allowlist since Bazel knows where the file is.
PiperOrigin-RevId: 610831569
(cherry picked from commit 589e42ce5c96030ee0970d3d59a6a2ce03362fde)
=> Remove implicit dependencies of `_allowlist_function_transition` in third_party

swift/BUILD, swift/internal/attrs.bzl, swift/swift_library.bzl
This was only present to support Apple framework rules, but its design was flawed, so they no longer use it. Library evolution shouldn't be enabled for entire dependency subgraphs; authors of SDKs should explicitly enable it on their libraries with the `library_evolution` attribute.
PiperOrigin-RevId: 629786303
(cherry picked from commit 1ee51c8cc980e8e0a9cd7f21e99c5e424fbc3afa)
Cherry-pick notes: Applied the same change to the `emit_private_swiftinterface` build setting.
=> Remove the `emit_swiftinterface` build setting

doc/rules.md, swift/swift_cross_import_overlay.bzl
This can be used if either of those targets exports multiple modules.
PiperOrigin-RevId: 665873940
(cherry picked from commit 8563c97fde773118244ebd987ce44637a4a884ac)
=> Allow `swift_cross_import_overlay` to specify a disambiguating explicit module name for the declaring and/or bystanding module

swift/internal/BUILD, swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/features.bzl
Nobody is using it anymore; furthermore, it's dangerous now that we use explicit modules by default.
PiperOrigin-RevId: 681454702
(cherry picked from commit bcf0703b72b8fc51aad2b3d204b0562cbd14155b)
=> Remove the `swift.no_generated_module_map` feature

doc/api.md, swift/internal/compiling.bzl, swift/swift_clang_module_aspect.bzl, swift/swift_library.bzl
This was rarely caught in practice because it only affects implicit module compilation and only matters when a dependency has includes that depend on custom header search paths provided by one of their C dependencies.
PiperOrigin-RevId: 642596524
(cherry picked from commit 8600c56a7991b9779b0e0761c8be037455a317b4)
=> Don't drop compilation contexts for `private_deps` when compiling the target that imports them

swift/internal/attrs.bzl
I incorrectly added this as part of the cherry-pick in 5f6ac77099eda1838c36c7e3c7b4e88309caad1d.
=> Remove unnecessary `SwiftBinaryInfo` required provider from `plugins` attribute

swift/BUILD, swift/internal/build_settings.bzl
According to the Bazel documentation, this option is deprecated. config.string_list(repeatable = True) should be used instead. This PR is similar to this one, which I sent out for rules_rust:
https://github.com/bazelbuild/rules_rust/pull/2983
=> Stop using config.string(allow_multiple = True)

swift/internal/compiling.bzl
PiperOrigin-RevId: 681838149
(cherry picked from commit f2eba62788e1abf31dd4eddcbe443c4e97d9c817)
=> Make sure that the path to the generated header in the generated module map is workspace-relative when the feature configuration asks for it

swift/swift_clang_module_aspect.bzl, swift/swift_overlay.bzl
PiperOrigin-RevId: 665946723
(cherry picked from commit 6d0fc0f4f71a430958a7453d51cf8f8ea70e0520)
=> Don't drop `swift_overlay` linking contexts when an overlay depends on another library that has an overlay

swift/swift_test.bzl
Regressed in 43af3816b5bea4e0add6523ee1642d75157f783d.
=> Fix `apple.swizzle_absolute_xcttestsourcelocation` usage

swift/BUILD, swift/swift_library_group.bzl
Without this, we won’t add required linkopts to `apple_xcframework_import` targets.
=> Add implicit deps to `swift_library_group`

tools/worker/output_file_map.cc
Since we extracting `swiftconstvalues` from https://github.com/bazelbuild/rules_swift/pull/1170
But we forgot to update the path for swiftconstvalues in the incremental output file map.
It leads to the incremental feature not working.
For example, demo: https://github.com/vikage/DemoBazelSwiftIncremental
When I change file B.swift (No other file uses struct B) but log shows build A.swift and C.swift as well
I used `-driver-show-job-lifecycle` and `-driver-show-incremental` flags to show debug log
```
WARNING: Build option --swiftcopt has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
INFO: Analyzed target //:Demo (99 packages loaded, 1088 targets configured).
INFO: From Compiling Swift module //:Demo:
remark: …
```
=> Map const-values in output file map for incremental

proto/swift_proto_utils.bzl
Using `package_name` or `copt` attributes weren't being propogated down into the actual swiftc compilation.
=> Include swift_proto_library attrs in compilation

tools/worker/output_file_map.cc
Since we extracting `swiftconstvalues` from
https://github.com/bazelbuild/rules_swift/pull/1170 But we forgot to update the path for swiftconstvalues in the incremental output file map.
It leads to the incremental feature not working.
For example, demo: https://github.com/vikage/DemoBazelSwiftIncremental When I change file B.swift (No other file uses struct B) but log shows build A.swift and C.swift as well
I used `-driver-show-job-lifecycle` and `-driver-show-incremental` flags to show debug log
```
WARNING: Build option --swiftcopt has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
INFO: Analyzed target //:Demo (99 packages loaded, 1088 targets configured).
INFO: From Compiling Swift module //:Demo:
remark: …
```
=> Cherry-pick: fix for incremental compilation

.bazelci/presubmit.yml
https://github.com/bazelbuild/rules_swift/pull/1466
=> Cherry-pick 2.x: run stardoc CI on older Bazel LTS

MODULE.bazel, swift/extensions.bzl
As per https://bazelbuild.slack.com/archives/C04DFUBQGSU/p1737756347358239
I was curious about the "reproducibility" of `swift_autoconfiguration` but from a `MODULE.bazel.lock` it seems it is.
I had to bump `bazel_features` to `1.9.0` to check the availability of the `reproducible` field on `extension_metadata`.
=> Mark non_module_deps extension as reproducible

swift/internal/swift_autoconfiguration.bzl
Similar to bd0e6e009165b8826f51f682bd9bd55b9f969a0e.
=> Print a warning, instead of an error, when not finding `swiftc.exe`

mixed_language/internal/library.bzl, swift/BUILD, swift/internal/attrs.bzl, swift/internal/swift_symbol_graph_aspect.bzl, swift/swift_clang_module_aspect.bzl, swift/swift_import.bzl, swift/swift_module_alias.bzl
Partial 2.x based cherry-pick of eb2a7ff8312a0b37837836314e372af357b4764a.
=> Remove `swift_toolchain_attrs` usage

proto/BUILD, proto/swift_proto_library_group.bzl
Missed in c90092e7ff332ee3a6fef35386080336ed368555.
=> Remove another `swift_toolchain_attrs` usage

swift/internal/swift_autoconfiguration.bzl
We support all macOS execution platforms, we don’t need to specify the CPU as well. This creates half as many toolchains.
=> Create fewer Xcode toolchains

swift/internal/compiling.bzl
Currently, if we have the following setup,
```
swift_library (
name = "LibA"
plugins = ["//:Macros"],
)
swift_library (
name = "LibB"
plugins = ["//:Macros"],
deps = [":LibA"],
)
```
We would see `-load-plugin-executable /path/to/Macros#Macros` twice while compiling LibB. With a more complicated dependency graph, we are seeing hundreds of -load-plugin-executable of the same plugin on some modules.
This PR deduplicates the plugins arguments.
=> Deduplicate plugin arguments

examples/runfiles/BUILD, examples/runfiles/data/sample.txt, examples/runfiles/main.swift, swift/internal/BUILD, swift/runfiles/BUILD, swift/runfiles/README.md, swift/runfiles/Runfiles.swift, test/runfiles/BUILD, test/runfiles/RunfilesTests.swift
Cherry pick #1310 into 2.x branch.
=> Cherry-pick: Introduce a pure Swift runfiles library (#1310)

test/private_deps_tests.bzl
Adding the missing `/` in the negative path tested with `//test:private_deps_client_cc_deps_modulemaps`.
=> Fix expected path in `//test:private_deps_client_cc_deps_modulemaps`

.bazelci/presubmit.yml, MODULE.bazel, swift/repositories.bzl, swift/toolchains/xcode_swift_toolchain.bzl, tools/worker/BUILD, tools/worker/worker_main.cc
This PR updates the index-import dependency to include both version 5.8 and 6.1 as the hash algorithm changed in Swift 6.1.
To make this change backwards compatible we switch to the 5.8 version on Xcode 16.2 and under.
=> 2.x: Support index-import on all Xcode 16.x versions

MODULE.bazel, swift/repositories.bzl, swift/toolchains/xcode_swift_toolchain.bzl, tools/worker/BUILD, tools/worker/worker_main.cc
This PR updates the index-import dependency to include both version 5.8 and 6.1 as the hash algorithm changed in Swift 6.1.
To make this change backwards compatible we switch to the 5.8 version on Xcode 16.2 and under.
=> Support index-import on all Xcode 16.x versions

swift/internal/build_settings.bzl
The doc was slightly incorrect here, the copts are split on a comma.
=> Fix documentation of per_module_swiftcopt flag

swift/internal/compiling.bzl
Missed when cherry-picking from upstream as they don’t have these actions.
=> Use `exec_group` for `SWIFT_ACTION_DERIVE_FILES` and `SWIFT_ACTION_DUMP_AST`

swift/swift_binary.bzl, swift/swift_compiler_plugin.bzl
When using a `macos_unit_test` target whose test sources depend on a `swift_compiler_plugin` or `swift_binary` target, its sources are missing from the coverage manifest `COVERAGE_MANIFEST` env var that's passed to lcov.
This change mirrors what the other targets do to add coverage instrumentation info so that they are available in the resulting coverage file.
=> Add instrumented files info to `swift_binary` and `swift_compiler_plugin`

swift/repositories.bzl
Pulls in fixes for a bad dependency on brew based `zlib`: https://github.com/MobileNativeFoundation/index-import/issues/135
=> Update index-import for zlib brew dep fix

swift/internal/compiling.bzl, swift/toolchains/config/compile_config.bzl
The `compilation_context_for_explicit_module_compilation` function handles collecting the strict includes from `SwiftInfo`s and we're already using that function when compiling the header module for a mixed-language `swift_library`, so we can simply reuse that logic here.
Upstreams: https://github.com/bazelbuild/rules_swift/commit/f08dc0cbe302f907935b71a50d1263c29b8bec08
=> Upstream: Only pass the strict Obj-C include paths from _direct_ dependencies to compilation actions

swift/BUILD, swift/internal/BUILD, swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/linking.bzl, swift/internal/utils.bzl
If enabled, the toolchain's implicit dependencies will not be used when compiling Swift or Clang modules. This should only be used when building the toolchain itself.
Upstreams: https://github.com/bazelbuild/rules_swift/commit/c29e0ab6b49d3812a07bede821f8f746878eb7d0
=> Upstream: Add a feature to allow certain targets to ignore the implicit dependencies from the toolchain.

.bazelci/presubmit.yml
> Your selected Xcode version 15.4 was not available on the machine. Bazel CI automatically picked a fallback version: 16.2. Available versions are: 16.2.
=> Update CI to use Xcode 16.2

doc/api.md, swift/internal/BUILD, swift/internal/actions.bzl, swift/internal/autolinking.bzl, swift/internal/compiling.bzl, swift/internal/debugging.bzl, swift/internal/interface_synthesizing.bzl, swift/internal/linking.bzl, swift/internal/symbol_graph_extracting.bzl, swift/swift_clang_module_aspect.bzl
Cherry-picks:
- https://github.com/bazelbuild/rules_swift/commit/1532dfc73a98adfe22eaf592b9dee565762167e3
- https://github.com/bazelbuild/rules_swift/commit/7f28991db8d2b44dd41b2b0ad7436014bae9f715
=> Upstream: Add an advanced API to create a custom instance of swift_clang_module_aspect with a different toolchain type than the default

swift/swift_synthesize_interface_aspect.bzl
Cherry-pick: https://github.com/bazelbuild/rules_swift/commit/634d0d16608e03d6dde9d23a517c2b9b40ce637c
The aspect generated a file named `<target>.synthesized.swift`, which was incorrect if a target had multiple modules in its `SwiftInfo.direct_modules` field. It would also be incorrect to just switch to `<module name>.synthesized.swift`, because two targets could potentially re-export the same module.
To fully disambiguate, we create an intermediate directory named for the target, and then use the module name as the filename in that directory.
PiperOrigin-RevId: 740414505
=> Upstream: Ensure that `swift_synthesize_interface_aspect` generates unique outputs

swift/internal/BUILD, swift/internal/compiling.bzl, swift/internal/feature_names.bzl, swift/internal/features.bzl
This reverts commit 68b58f7a44026fcaa174de0f8dc678d753aadeb6. 
While we have a custom `mixed_language_library` rule that doesnt match `upstream` we must maintain this feature or we get duplicate module declaration errors as the mixed language rules depend on this feature when they create their own modulemap
Without this commit reverted we get:
```sh
bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min16.0-applebin_ios-ST-2491983d010b/bin/Code/CoreLibraries/Contacts/Aliases/AliasesLegacy/AliasesLegacy.lib_swift_modulemap/_/module.modulemap:1:8: error: redefinition of module 'AliasesLegacy'
1 | module "AliasesLegacy" {
|        ^
bazel-out/ios_sim_arm64-dbg-ios-sim_arm64-min16.0-applebin_ios-ST-2491983d010b/bin/Code/CoreLibraries/Contacts/Aliases/AliasesLegacy/AliasesLegacy.lib/AliasesLegacy/module …
```
=> Revert "Remove the `swift.no_generated_module_map` feature"

swift/internal/swift_autoconfiguration.bzl
If you have rules_swift in your dependency tree, but don't use swift
anywhere in your build, this still warns is too noisy. Likely the most
common case for this is because grpc depends on rules_apple.
=> Remove prints when toolchain is skipped

swift/toolchains/config/compile_config.bzl, tools/worker/swift_runner.cc, tools/worker/swift_runner.h
In rules_swift < 3.x the .swiftsourceinfo files are unconditionally written to the module path. In rules_swift >= 3.x these same files are no longer tracked by Bazel unless explicitly requested. When using non-sandboxed mode, previous builds will contain these files and cause build failures when Swift tries to use them, in order to work around this compatibility issue, we check the module path for the presence of .swiftsourceinfo files and if they are present but not requested, we remove them.
Testing:
- `bazel clean --expunge`
- `git checkout 2.8.2`
- `bazel build //examples/... --spawn_strategy=local` (pass)
- `git checkout master`
- `bazel build //examples/... --spawn_strategy=local` (failure)
- `git checkout <this-branch>`
- `bazel build //examples/... --spawn_strategy=local` (pass)
=> Ensure undeclared outputs are deleted when not tracked

doc/rules.md, mixed_language/mixed_language_library.bzl
At Square, we're using a headermap for the Swift generated header, so that the objective-C half of a module is able to import it using `#import <Module/Module-Swift.h>`.
This headermap target can't be placed in `deps`, as doing so creates a dependency cycle.
Here is an example of what the use case looks like: https://github.com/bazelbuild/rules_swift/compare/master...jschear:rules_swift:js/demo_swift_header_imports_in_clang_half
```
header_map(
name = "swift_headermap",
module_name = "MixedAnswer",
propagate_include = False,
deps = ["MixedAnswer_swift"],
)
mixed_language_library(
name = "MixedAnswer",
hdrs = ["MixedAnswer.h"],
clang_copts = [
"-I$(execpath :swift_headermap)",
"-I.",
],
clang_deps = [":swift_headermap"],
clang_srcs = [
"MixedAnswer.m",
"MixedAnswerPrivate.m", …
```
=> Add `clang_deps` attr to `mixed_language_library`

.bazelci/presubmit.yml, BUILD, MODULE.bazel, doc/rules.md, examples/xplatform/custom_swift_proto_compiler/protos/BUILD, examples/xplatform/grpc/service/BUILD, examples/xplatform/proto/BUILD, examples/xplatform/proto_files/BUILD, examples/xplatform/proto_glob/BUILD, examples/xplatform/proto_library_group/request/BUILD, examples/xplatform/proto_library_group/response/BUILD, examples/xplatform/proto_library_group/service/BUILD, examples/xplatform/proto_path/protos/package_1/BUILD, examples/xplatform/proto_path/protos/package_2/BUILD, proto/BUILD, proto/swift_proto_library.bzl, proto/swift_proto_library_group.bzl, swift/BUILD, swift/extras.bzl, swift/internal/BUILD, swift/repositories.bzl, swift/toolchains/BUILD, swift/toolchains/config/BUILD, third_party/BUILD, third_party/bazel_protos/BUILD, third_party/rules_proto/BUILD, tools/BUILD, tools/common/BUILD, tools/mkdir_and_run/BUILD, tools/worker/BUILD
only way i could figure to get this to work was to not assist in standing up neither `protobuf_deps()` nor `rules_cc_dependencies()` in `swift_extra_dependencies()` – this works around the ordering issue that breaks transitive dep loading of both rules_python/rules_java and our stardoc configuration
=> fix rules_cc for 7.x WORKSPACE/non-bzlmod users

tools/worker/swift_runner.cc, tools/worker/swift_runner.h, tools/worker/work_processor.cc
Similar to #1533 but when using `--strategy=worker`
In rules_swift < 3.x the .swiftsourceinfo files are unconditionally written to the module path. In rules_swift >= 3.x these same files are no longer tracked by Bazel unless explicitly requested. When using non-sandboxed mode, previous builds will contain these files and cause build failures when Swift tries to use them, in order to work around this compatibility issue, we check the module path for the presence of .swiftsourceinfo files and if they are present but not requested, we remove them.
Testing:
- `bazel clean --expunge`
- `git checkout 2.8.2`
- `bazel build @com_github_apple_swift_argument_parser//... --strategy=worker,local --worker_sandboxing=false` (pass)
- `git checkout master`
- `bazel build …
=> Fix .swiftsourceinfo readonly bugs in version 3+

swift/internal/explicit_module_map_file.bzl
In Swift 6.2, entries in `.swift-explicit-module-map.json` must have unique names, so Swift and Clang entries must be merged.
https://github.com/swiftlang/swift/commit/8dd9a12618217f43d917bf8c6e5e495197455551
=> Merge Swift and Clang entries in `.swift-explicit-module-map.json`

swift/toolchains/swift_toolchain.bzl, swift/toolchains/xcode_swift_toolchain.bzl
When using rules_swift with a custom (rules based) cc_toolchain, it is sometimes useful to propagate certain flags to every swift invocation. And while a cc_library() could potentially be used in implicit_deps to pass the usual options (-isystem, -iquote, -D, etc...), the CcInfo provider does not allow propagating every option.
Some options in particular (such as -Xclang -internal-externc-system) cannot currently be propagated that way, and they can nonetheless be necessary in certain environment.
So we're making the current toolchain rules a tad more flexible in this commit, by allowing the user to specify "objc_copts" (for xcode only) and "copts" at toolchain parameters. The content of these attributes is then added to the corresponding compilation actions.
=> feat(toolchain): add copts and objc_copts attributes to toolchains

swift/internal/compiling.bzl
This replacement causes issues with importing indexstores.
In 965c37304cbc0263b6a5b0a945529c66a593c34c this replacement was added to work around issues with `ar_wrapper`. I don't see `ar_wrapper` used anywhere in Bazel, so I believe this is safe to remove.
=> Remove space-in-path replacement

proto/swift_proto_utils.bzl
Otherwise sandboxing/REB won’t see the inputs.
=> Pass `swiftc_inputs` to `swift_common.compile` in `compile_swift_protos_for_target`

swift/internal/feature_names.bzl, swift/toolchains/config/compile_config.bzl, swift/toolchains/xcode_swift_toolchain.bzl, tools/worker/swift_runner.cc
Cherry-picks:
- https://github.com/bazelbuild/rules_swift/commit/038b5bd71e3fad04e2cfa5a4d080533bde4f350d
- https://github.com/bazelbuild/rules_swift/commit/2767c641ea1dd7f305bbfd0e560f1dfad0753b1e
- https://github.com/bazelbuild/rules_swift/commit/fa2f3cd42394eacb7f6497777592eebc3442f5a4
=> Ensure that PCMs are hermetic on Xcode 16 and higher.

swift/toolchains/config/compile_config.bzl
Cherry-pick: fbe3074ba98b42e5c3d277dfe33f654734000018
=> Make sure that .swiftinterface compile actions also use `-file-prefix-map`, so that indexstores emitted by those actions are also deterministic.
